### ISSUE TITLE
Using node-cache causes a bug

### ISSUE THREAD

**Issue by mschakulat** [brillout/vite-plugin-ssr#1005]
### Description

`Error: [vite-plugin-ssr@0.4.117][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at get (/Users/mschakul/Projects/Projects_AS/ac-delivery/packages/deliveries/node_modules/.pnpm/vite-plugin-ssr@0.4.117_vite@4.3.2/node_modules/vite-plugin-ssr/dist/cjs/utils/require-shim.js:72:41)
    at graphqlClient.ts:1:34
    at instantiateModule (file:///Users/mschakul/Projects/Projects_AS/ac-delivery/packages/deliveries/node_modules/.pnpm/vite@4.3.2_@types+node@18.16.1_sass@1.62.1/node_modules/vite/dist/node/chunks/dep-7efa13d7.js:54352:15)`

**Comment by brillout** [comment]
Update to the latest version. If you still get this let me know and I'll re-open it.

**Comment by mschakulat** [comment]
Still get an error. I'am using node-cache in the `onBeforeRender` hook: 
```
nodeCache.get<string>('bazinga') ?? ''
```

> 11:00:14 AM [vite-plugin-ssr][request(1)][Error] An error was thrown:
ReferenceError: __dirname is not defined
    at eval (/src/main.ts:16:14)
    at async instantiateModule (file:///Users/biskit/Projects/projects/ac/packages/del/node_modules/.pnpm/vite@4.3.2_@types+node@18.16.1_sass@1.62.1/node_modules/vite/dist/node/chunks/dep-7efa13d7.js:54352:9)
11:00:14 AM [vite-plugin-ssr][request(1)] HTTP response / ERR

**Comment by brillout** [comment]
Doesn't seem related to VPS.
