### ISSUE TITLE
Error on integrating with nextjs to vitejs migration.

### ISSUE THREAD

**Issue by pmsmanishchauhan** [brillout/vite-plugin-ssr#1035]
### Description

```
Error: [vite-plugin-ssr@0.4.133][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at assertOutDirResolved (D:\self\jhattse-consumer\node_modules\vite-plugin-ssr\dist\cjs\utils\getOutDirs.js:88:29)
    at resolveOutDir (D:\self\jhattse-consumer\node_modules\vite-plugin-ssr\dist\cjs\utils\getOutDirs.js:28:9)
    at config (D:\self\jhattse-consumer\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\buildConfig.js:35:55)
    at runConfigHook (file:///D:/self/jhattse-consumer/node_modules/vite/dist/node/chunks/dep-33545781.js:64476:31)
    at resolveConfig (file:///D:/self/jhattse-consumer/node_modules/vite/dist/node/chunks/dep-33545781.js:63966:14)
    at Module.build (file:///D:/self/jhattse-consumer/node_modules/vite/dist/node/chunks/dep-33545781.js:46246:20)
    at triggerFullBuild (D:\self\jhattse-consumer\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\autoFullBuild.js:74:5)      
    at Object.handler (D:\self\jhattse-consumer\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\autoFullBuild.js:30:25)       
    at async Promise.all (index 0)
    at PluginDriver.hookParallel (file:///D:/self/jhattse-consumer/node_modules/rollup/dist/es/shared/node-entry.js:24335:9)
    at file:///D:/self/jhattse-consumer/node_modules/rollup/dist/es/shared/node-entry.js:25690:13
    at catchUnfinishedHookActions (file:///D:/self/jhattse-consumer/node_modules/rollup/dist/es/shared/node-entry.js:24770:20)
    at build (file:///D:/self/jhattse-consumer/node_modules/vite/dist/node/chunks/dep-33545781.js:46405:22)
    at CAC.<anonymous> (file:///D:/self/jhattse-consumer/node_modules/vite/dist/node/cli.js:812:9)
error Command failed with exit code 1.
```

**Comment by brillout** [comment]
Insert the following before line `26` of `D:\self\jhattse-consumer\node_modules\vite-plugin-ssr\dist\cjs\utils\getOutDirs.js` and report back:

```diff
 function resolveOutDir(config) {
     const outDir = getOutDirFromUserConfig(config) || 'dist';
+    console.log('outDir', outDir);
     if (!isOutDirRoot(outDir)) {
```

**Comment by pmsmanishchauhan** [comment]
outDir dist/client

**Comment by brillout** [comment]
You shoudn't set it to `dist/client`, set it to anything else that doesn't end with `client/` or `server/`.
