### ISSUE TITLE
build stage of my ssr vite site fails

### ISSUE THREAD

**Issue by Maikpwwq** [brillout/vite-plugin-ssr#1046]
### Description

If I run `pnpm run build` it reports: 

```
✓ 3341 modules transformed.
Error: [vite-plugin-ssr@0.4.133][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at assertOutDirResolved (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/vite-plugin-ssr@0.4.133_vite@4.4.8/node_modules/vite-plugin-ssr/dist/cjs/utils/getOutDirs.js:88:29)
    at resolveOutDir (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/vite-plugin-ssr@0.4.133_vite@4.4.8/node_modules/vite-plugin-ssr/dist/cjs/utils/getOutDirs.js:28:9)
    at config (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/vite-plugin-ssr@0.4.133_vite@4.4.8/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/buildConfig.js:35:55)
    at runConfigHook (file:///media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/vite@4.4.8_sass@1.64.2_stylus@0.59.0/node_modules/vite/dist/node/chunks/dep-75f53616.js:66223:31)
    at resolveConfig (file:///media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/vite@4.4.8_sass@1.64.2_stylus@0.59.0/node_modules/vite/dist/node/chunks/dep-75f53616.js:65666:14)
    at Module.build (file:///media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/vite@4.4.8_sass@1.64.2_stylus@0.59.0/node_modules/vite/dist/node/chunks/dep-75f53616.js:47803:20)
    at triggerFullBuild (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/vite-plugin-ssr@0.4.133_vite@4.4.8/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/autoFullBuild.js:74:5)
    at Object.handler (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/vite-plugin-ssr@0.4.133_vite@4.4.8/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/autoFullBuild.js:30:25)
    at async Promise.all (index 0)
    at PluginDriver.hookParallel (file:///media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/rollup@3.27.0/node_modules/rollup/dist/es/shared/node-entry.js:25284:9)
    at file:///media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/rollup@3.27.0/node_modules/rollup/dist/es/shared/node-entry.js:26596:13
    at catchUnfinishedHookActions (file:///media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/rollup@3.27.0/node_modules/rollup/dist/es/shared/node-entry.js:25722:16)
    at build (file:///media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/vite@4.4.8_sass@1.64.2_stylus@0.59.0/node_modules/vite/dist/node/chunks/dep-75f53616.js:47962:22)
    at CAC.<anonymous> (file:///media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/vite@4.4.8_sass@1.64.2_stylus@0.59.0/node_modules/vite/dist/node/cli.js:822:9)
 ELIFECYCLE  Command failed with exit code 1.
```

Then if I run `pnpm run generate`

```
✓ built in 1.06s
vite-plugin-ssr v0.4.133 pre-rendering HTML...
(node:84472) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/@mui+material@5.14.3_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.18_react-dom@18.2.0_react@18.2.0/node_modules/@mui/material/Table/index.js:3
export { default } from './Table';
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1187:20)
    at Module._compile (node:internal/modules/cjs/loader:1231:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Function.Module._load (node:internal/modules/cjs/loader:965:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
 ELIFECYCLE  Command failed with exit code 1.
```

And if I run `pnpm run dev` and open my site

```
comunidad-dezzpo@1.0.0 dev /media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA
> node server

Server running at http://localhost:5173

/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6047
  throw new Error('Element type is invalid: expected a string (for built-in ' + 'components) or a class/function (for composite components) ' + ("but got: " + (type == null ? type : typeof type) + "." + info));
        ^
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at renderElement (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6047:9)
    at renderNodeDestructiveImpl (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderNode (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6263:12)
    at renderChildrenArray (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6215:7)
    at renderNodeDestructiveImpl (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6145:7)
    at renderNodeDestructive (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderElement (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5975:9)
    at renderNodeDestructiveImpl (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderIndeterminateComponent (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5789:7)
    at renderElement (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5950:7)
    at renderNodeDestructiveImpl (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderContextProvider (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5924:3)
    at renderElement (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6021:11)
    at renderNodeDestructiveImpl (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderIndeterminateComponent (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5789:7)
    at renderElement (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5950:7)
    at renderNodeDestructiveImpl (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderElement (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5975:9)
    at renderNodeDestructiveImpl (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderIndeterminateComponent (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5789:7)
    at renderElement (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5950:7)
    at renderNodeDestructiveImpl (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at retryTask (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6532:5)
    at performWork (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6580:7)
    at /media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6904:12
    at scheduleWork (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:78:3)
    at startWork (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6903:3)
    at renderToStringImpl (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6977:3)
    at Proxy.renderToString (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:7065:10)
    at render (/media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/src/renderer/_default.page.server.jsx:21:42)
    at file:///media/oem/MyFiles/8_DEVELOPMENT/Comunidad-Dezzpo-PWA/server.js:89:29
 ELIFECYCLE  Command failed with exit code 1.
```

How can I handle to solved?

**Comment by brillout** [comment]
> Error: [vite-plugin-ssr@0.4.133][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).

Fixed. Let me know if there is anything else.

Also, in case your company is up for it: https://github.com/sponsors/brillout.
