### ISSUE TITLE
vite-plugin-ssr bug

### ISSUE THREAD

**Issue by hanyaxxx** [brillout/vite-plugin-ssr#1053]
### Description

D:\work\code\learn\hernest2\sandwich-react\node_modules\vite-plugin-ssr\dist\cjs\utils\filesystemPathHandling.js:23
    (0, assert_1.assert)(!path.includes(sepWin32), errMsg(path));
                        ^
Error: [vite-plugin-ssr@0.4.134][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error; 
a maintainer will fix the bug (usually under 24 hours). Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): Not a posix path: D:\work\code\learn\hernest2\sandwich-react\template\hernest-m\src\assets\scss\antcover.scss
    at assertPosixPath (D:\work\code\learn\hernest2\sandwich-react\node_modules\vite-plugin-ssr\dist\cjs\utils\filesystemPathHandling.js:23:25)
    at getFilePathVite (D:\work\code\learn\hernest2\sandwich-react\node_modules\vite-plugin-ssr\dist\cjs\utils\getFilePathAbsolute.js:47:50)
    at getPrettyErrorWithCodeSnippet (D:\work\code\learn\hernest2\sandwich-react\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\shared\loggerNotProd\errorWithCodeSnippet.js:51:88)  
    at logErr (D:\work\code\learn\hernest2\sandwich-react\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\shared\loggerNotProd.js:86:86)
    at logViteErrorContainingCodeSnippet (D:\work\code\learn\hernest2\sandwich-react\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\shared\loggerNotProd.js:63:5)
    at Object.config.logger.<computed> [as error] (D:\work\code\learn\hernest2\sandwich-react\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\shared\loggerVite.js:40:67)
    at file:///D:/work/code/learn/hernest2/sandwich-react/node_modules/vite/dist/node/chunks/dep-75f53616.js:41988:43

**Comment by brillout** [comment]
Fix released in `0.4.135`. I didn't try the fix: let me know if you still run into any issue.

Btw. in case your company is up for it: https://github.com/sponsors/brillout.
