### ISSUE TITLE
I've stumbled upon a bug in vite-plugin-ssr's source code

### ISSUE THREAD

**Issue by Cameleopardus** [brillout/vite-plugin-ssr#1061]
### Description

I am using Vike/vite-pluggin-ssr to build out pages and turn them into pdf with wkhtmltopdf.
This works great locally in using vite dev server, but in production I am running into this issue where the first request succeeds and serves me the file, but any subsequent request after that fails and throws an errror with the traceback below.
After that things work fine again until I generate and respond with another file.

At first I suspected that the error was related using pipe(res) to return the content, but the traceback indicates the error is actually in renderPage.

```

Error: [vite-plugin-ssr@0.4.135][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at assertEnv (/app/vue_pages/node_modules/vite-plugin-ssr/dist/cjs/utils/assertIsNotProductionRuntime.js:40:29)
    at renderPage (/app/vue_pages/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:43:27)
    at /app/vue_pages/server/index.js:61:35
    at Layer.handle [as handle_request] (/app/vue_pages/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/vue_pages/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/app/vue_pages/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/app/vue_pages/node_modules/express/lib/router/layer.js:95:5)
    at /app/vue_pages/node_modules/express/lib/router/index.js:284:15
    at param (/app/vue_pages/node_modules/express/lib/router/index.js:365:14)
    at param (/app/vue_pages/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/app/vue_pages/node_modules/express/lib/router/index.js:421:3)
    at next (/app/vue_pages/node_modules/express/lib/router/index.js:280:10)
    at serveStatic (/app/vue_pages/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/app/vue_pages/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/vue_pages/node_modules/express/lib/router/index.js:328:13)
    at /app/vue_pages/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/vue_pages/node_modules/express/lib/router/index.js:346:12)
    at next (/app/vue_pages/node_modules/express/lib/router/index.js:280:10)
    at /app/vue_pages/node_modules/body-parser/lib/read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (/app/vue_pages/node_modules/raw-body/index.js:231:16)
    at done (/app/vue_pages/node_modules/raw-body/index.js:220:7)
    at IncomingMessage.onEnd (/app/vue_pages/node_modules/raw-body/index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
Server running at http://localhost:3000```

**Comment by brillout** [comment]
I'll need a minimal reproduction for that. I suspect some unsual setup on your part.

**Comment by brillout** [comment]
> I'll put something together and follow up

Looking forward to it.

Alternatively, you can debug this yourself by digging into `/app/vue_pages/node_modules/vite-plugin-ssr/dist/cjs/utils/assertIsNotProductionRuntime.js`. The code is fairly self-explanatory. Let me know if you find the culprit.

**Comment by Cameleopardus** [comment]
I've found out what it was, somewhere in the code there vite.config.js was being imported to get some values, which was for whatever reason setting `env.isVite` and `env.shouldBeVite` to true causing the failed assertion.

Thanks for the prompt reply!

**Comment by brillout** [comment]
👍 Btw. would your company be up for [sponsoring](https://github.com/sponsors/brillout)?
