### ISSUE TITLE
500 Error - Log says "a bug in vite-plugin-ssr's source code"

### ISSUE THREAD

**Issue by luisgregson** [brillout/vite-plugin-ssr#1088]
### Description

Hey, i got a runtime 500 error on a request to my vite server and the server has the following log:

```
Error: [vite-plugin-ssr@0.4.43][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust. 

    at assertUrlPathname (/node_modules/vite-plugin-ssr/dist/cjs/utils/parseUrl.js:130:25)

    at analyzeBaseUrl (/node_modules/vite-plugin-ssr/dist/cjs/utils/parseUrl.js:134:5)

    at parseUrl (/node_modules/vite-plugin-ssr/dist/cjs/utils/parseUrl.js:48:36)

    at hasSuffix (/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage/handlePageContextRequestUrl.js:15:65)

    at handlePageContextRequestUrl (/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage/handlePageContextRequestUrl.js:8:10)

    at initializePageContext (/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:136:140)

    at runMicrotasks (<anonymous>)

    at async renderPage_ (/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:30:41)

    at async renderPage (/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:155:16)

    at async /packages/client/server/index.ts:43:25

```

vite.config.ts:

```
import react from "@vitejs/plugin-react";
import ssr from "vite-plugin-ssr/plugin";
import { UserConfig } from "vite";
import { resolve } from 'path'

const config: UserConfig = {
  plugins: [
    react({
      babel: {
        babelrc: false,
        configFile: false,
        plugins: [
          [
            "babel-plugin-styled-components",
            {
              ssr: true,
            },
          ],
        ],
      },
    }),
    ssr({ prerender: false }),
  ],
  resolve: {
    alias: {
      "@src": resolve(__dirname, "./src"),
    },
  },
};

export default config;
```

versions:

```
    "@vitejs/plugin-react": "^2.0.1",
    "vite": "^3.0.9",
    "vite-plugin-ssr": "^0.4.41"
```

**Comment by brillout** [comment]
Update to the latest version. Let me know if you still get the issue and I'll re-open.
