### ISSUE TITLE
Getting "TypeError: __getAllUserFiles is not a function" when running production server

### ISSUE THREAD

**Issue by stephensamra** [brillout/vite-plugin-ssr#11]
Hi there,

When I run `yarn server:prod` the server starts fine (I see the `server running at http://localhost:3000` message) but, when I try to make a request from the browser I get an error message in the console and the browser never receives a response.

The dev server (`yarn dev`) does not have this problem.

I followed the "Manual Installation" section of the README for React + TypeScript so it's possible I missed something but, as far as I can tell, what I have is the same as the react-typescript boilerplate. 

Error message:
```
(node:27112) UnhandledPromiseRejectionWarning: TypeError: __getAllUserFiles is not a function
    at Object.getAllUserFiles (.../node_modules/vite-plugin-ssr/user-files/infra.node.ts:13:10)
    at Object.getUserFiles (.../node_modules/vite-plugin-ssr/user-files/getUserFiles.shared.ts:18:38)
    at Object.getPageIds (.../node_modules/vite-plugin-ssr/route.node.ts:166:21)
    at renderPage (.../node_modules/vite-plugin-ssr/renderPage.node.ts:48:22)
    at .../index.ts:25:20
```

package.json script:
```
"scripts": {
    // ...
    "server:prod": "cross-env NODE_ENV=production ts-node ./server",
},
```

server/index.ts:
```ts
import express from 'express'
import { createPageRender } from 'vite-plugin-ssr'
import * as vite from 'vite'

const isProduction = process.env.NODE_ENV === 'production'
const root = `${__dirname}/..`

async function startServer() {
  const app = express()

  let viteDevServer: vite.ViteDevServer | undefined

  if (isProduction) {
    app.use(express.static(`${root}/dist/client`, { index: false }))
  } else {
    viteDevServer = await vite.createServer({ root, server: { middlewareMode: true }})
    app.use(viteDevServer.middlewares)
  }

  const renderPage = createPageRender({ viteDevServer, isProduction, root })

  app.get('*', async (req, res, next) => {
    const url = req.originalUrl
    const contextProps = {}
    const result = await renderPage({ url, contextProps })
    if (result.nothingRendered) return next()
    res.status(result.statusCode).send(result.renderResult)
  })

  const port = 3000
  app.listen(port, () => {
    console.log(`🚀 server running at http://localhost:${port}`)
  })
}

startServer()
```

Any help would be appreciated. Thanks in advance.

**Comment by brillout** [comment]
What Vite version are you using?

**Comment by stephensamra** [comment]
```sh
➜ vite -v
vite/2.1.0 darwin-x64 node-v14.3.0
```

**Comment by brillout** [comment]
I can reproduce, let me fix this.

**Comment by stephensamra** [comment]
Thank you!

**Comment by brillout** [comment]
You need one more thing.

**Comment by brillout** [comment]
There is aslo a bug https://github.com/vitejs/vite/issues/2390 and a pending PR https://github.com/vitejs/vite/pull/2519.

But I wrote a patch `@brillout/vite-fix-2390` you can use until the PR is merged.

```shell
yarn add vite-plugin-ssr@0.1.0-beta.15
yarn add vite@2.1.2
yarn add @brillout/vite-fix-2390
yarn vite-fix-2390 # It should say `Vite already patched`
rm -r dist/ node_modules/.vite
yarn build
yarn server:prod
```

Let me know if you run into any issue.

**Comment by stephensamra** [comment]
Works perfectly - thanks so much!
