### ISSUE TITLE
error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.

### ISSUE THREAD

**Issue by alxistn** [brillout/vite-plugin-ssr#1102]
### Description

Hello,

I follow the getting started by running `yarn create vite-plugin-ssr` then go in the folder and run `yarn install` and `yarn dev`.

But I immediately get the following error : 

```
yarn run v1.22.19
warning package.json: No license field
$ npm run server:dev

> server:dev
> npm run server


> server
> node --loader ts-node/esm ./server/index.ts

(node:27166) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/project-srr/node_modules/ts-node/src/index.ts:859
return new TSError(diagnosticText, diagnosticCodes, diagnostics);
^
TSError: ⨯ Unable to compile TypeScript:
error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.

at createTSError (/project-srr/node_modules/ts-node/src/index.ts:859:12)
at reportTSError (/project-srr/node_modules/ts-node/src/index.ts:863:19)
at /project-srr/node_modules/ts-node/src/index.ts:1379:34
at Object.compile (/project-srr/node_modules/ts-node/src/index.ts:1458:13)
at transformSource (/project-srr/node_modules/ts-node/src/esm.ts:400:37)
at /project-srr/node_modules/ts-node/src/esm.ts:278:53
at async addShortCircuitFlag (/project-srr/node_modules/ts-node/src/esm.ts:409:15)
at async nextLoad (node:internal/modules/esm/loader:163:22)
at async ESMLoader.load (node:internal/modules/esm/loader:601:20)
at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:11) {
diagnosticCodes: [ 5110 ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by brillout** [comment]
Indeed, the new TypeScript 5.2 release [made a breaking change about this](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#module-and-moduleresolution-must-match-under-recent-node-js-settings).

The boilerplates are fixed and you can try again `$ yarn create vite-plugin-ssr` &mdash; it should now work.

Let me know if you still run into issues.

**Comment by alxistn** [comment]
No more issues, thanks ! :)
