### ISSUE TITLE
BasePath Error

### ISSUE THREAD

**Issue by henriqueabdala-mb** [brillout/vite-plugin-ssr#1126]
### Description

I'm trying to deploy a clean vue vanila vite-plugin-ssr application, but I'm getting this error... my only changes were the base-path in vite.config.js and add the HOST IP in express...

```
> server
> node ./server

2023-09-18T19:00:50.377Z vite:config bundled config file loaded in 1595.43ms
2023-09-18T19:00:50.969Z vite:esbuild 387.02ms tsconfck init /app
2023-09-18T19:00:52.476Z vite:config using resolved config: {
  base: '/uni/',
  plugins: [
    'vite:optimized-deps',
    'vite:watch-package-data',
    'vite:pre-alias',
    'alias',
    'vite-plugin-ssr:resolveVpsConfig',
    'vite-plugin-ssr:setGlobalContext',
    'vite:modulepreload-polyfill',
    'vite:resolve',
    'vite:html-inline-proxy',
    'vite:css',
    'vite:esbuild',
    'vite:json',
    'vite:wasm-helper',
    'vite:worker',
    'vite:asset',
    'vite:vue',
    'vite-plugin-ssr:commonConfig-1',
    'vite-plugin-ssr:importUserCode',
    'vite-plugin-ssr:devConfig',
    'vite-plugin-ssr:previewConfig',
    'vite-plugin-ssr:extractAssets-4',
    'vite-plugin-ssr:extensionsAssets',
    'vite:wasm-fallback',
    'vite:css-post',
    'vite:worker-import-meta-url',
    'vite:asset-import-meta-url',
    'vite:dynamic-import-vars',
    'vite:import-glob',
    'vite-plugin-ssr:commonConfig-2',
    'vite-plugin-ssr:devConfig:addSsrMiddleware',
    'vite-plugin-ssr:extractExportNames',
    'vite-plugin-ssr:importBuild:config',
    'vite-plugin-ssr:baseUrls',
    'vite-plugin-ssr:env',
    'vite:client-inject',
    'vite:import-analysis',
    'vite:define'
  ],
  root: '/app',
  server: {
    preTransformRequests: true,
    middlewareMode: true,
    sourcemapIgnoreList: [Function: isInNodeModules],
    fs: { strict: true, allow: [Array], deny: [Array] },
    port: 3000
  },
  resolve: {
    mainFields: [ 'module', 'jsnext:main', 'jsnext' ],
    browserField: true,
    conditions: [],
    extensions: [
      '.mjs',  '.js',
      '.mts',  '.ts',
      '.jsx',  '.tsx',
      '.json'
    ],
    dedupe: [ 'vue' ],
    preserveSymlinks: false,
    alias: [ [Object], [Object] ]
  },
  define: { __VUE_OPTIONS_API__: true, __VUE_PROD_DEVTOOLS__: false },
  ssr: {
    format: 'esm',
    target: 'node',
    external: [ 'vite-plugin-ssr', 'vite-plugin-ssr/server' ],
    optimizeDeps: { disabled: true, esbuildOptions: [Object] }
  },
  appType: 'custom',
  experimental: { importGlobRestoreExtension: true, hmrPartialAccept: false },
  optimizeDeps: {
    disabled: 'build',
    exclude: [
      'vite-plugin-ssr/client',
      'vite-plugin-ssr/client/router',
      'vite-plugin-ssr/routing',
      '@brillout/json-serializer/parse',
      '@brillout/json-serializer/stringify',
      '@brillout/picocolors'
    ],
    esbuildOptions: { preserveSymlinks: false },
    include: [],
    entries: [
      '/app/renderer/_default.page.client.js',
      '/app/renderer/_error.page.vue',
      '/app/pages/about/index.page.vue',
      '/app/pages/index/index.page.vue'
    ]
  },
  build: {
    target: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
    cssTarget: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
    outDir: 'dist/client',
    assetsDir: 'assets',
    assetsInlineLimit: 4096,
    cssCodeSplit: true,
    sourcemap: false,
    rollupOptions: {},
    minify: 'esbuild',
    terserOptions: {},
    write: true,
    emptyOutDir: null,
    copyPublicDir: true,
    manifest: false,
    lib: false,
    ssr: false,
    ssrManifest: false,
    ssrEmitAssets: false,
    reportCompressedSize: true,
    chunkSizeWarningLimit: 500,
    watch: null,
    commonjsOptions: { include: [Array], extensions: [Array] },
    dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] },
    modulePreload: { polyfill: true },
    cssMinify: true
  },
  envPrefix: [ 'VITE_', 'BASE_SERVER', 'BASE_ASSETS' ],
  _baseOriginal: '/uni/',
  configFile: '/app/vite.config.js',
  configFileDependencies: [ '/app/vite.config.js' ],
  inlineConfig: { root: '/app/server/..', server: { middlewareMode: true } },
  rawBase: '/uni/',
  publicDir: '/app/public',
  cacheDir: '/app/node_modules/.vite',
  command: 'serve',
  mode: 'development',
  isWorker: false,
  mainConfig: null,
  isProduction: false,
  css: undefined,
  esbuild: { jsxDev: true },
  preview: {
    port: 3000,
    strictPort: undefined,
    host: undefined,
    https: undefined,
    open: undefined,
    proxy: undefined,
    cors: undefined,
    headers: undefined
  },
  envDir: '/app',
  env: {
    BASE_SERVER: '/uni/',
    BASE_ASSETS: '/uni/',
    BASE_URL: '/uni/',
    MODE: 'development',
    DEV: true,
    PROD: false
  },
  assetsInclude: [Function: assetsInclude],
  logger: {
    hasWarned: false,
    info: [Function (anonymous)],
    warn: [Function (anonymous)],
    warnOnce: [Function: warnOnce],
    error: [Function (anonymous)],
    clearScreen: [Function: clearScreen],
    hasErrorLogged: [Function: hasErrorLogged]
  },
  packageCache: Map(1) {
    'fnpd_/app' => {
      dir: '/app',
      data: [Object],
      hasSideEffects: [Function: hasSideEffects],
      webResolvedImports: {},
      nodeResolvedImports: {},
      setResolvedCache: [Function: setResolvedCache],
      getResolvedCache: [Function: getResolvedCache]
    },
    set: [Function (anonymous)]
  },
  createResolver: [Function: createResolver],
  worker: {
    format: 'iife',
    plugins: [
      'vite:optimized-deps',
      'vite:watch-package-data',
      'vite:pre-alias',
      'alias',
      'vite:modulepreload-polyfill',
      'vite:resolve',
      'vite:html-inline-proxy',
      'vite:css',
      'vite:esbuild',
      'vite:json',
      'vite:wasm-helper',
      'vite:worker',
      'vite:asset',
      'vite:wasm-fallback',
      'vite:define',
      'vite:css-post',
      'vite:worker-import-meta-url',
      'vite:asset-import-meta-url',
      'vite:dynamic-import-vars',
      'vite:import-glob',
      'vite:client-inject',
      'vite:import-analysis'
    ],
    rollupOptions: {},
    getSortedPlugins: [Function: getSortedPlugins],
    getSortedPluginHooks: [Function: getSortedPluginHooks]
  },
  getSortedPlugins: [Function: getSortedPlugins],
  getSortedPluginHooks: [Function: getSortedPluginHooks],
  configVpsPromise: Promise {
    {
      disableAutoFullBuild: null,
      extensions: [],
      prerender: false,
      includeAssetsImportedByServer: true,
      baseServer: '/uni/',
      baseAssets: '/uni/',
      redirects: {},
      disableUrlNormalization: false,
      trailingSlash: false
    }
  }
}
2023-09-18T19:00:53.469Z vite:deps scanning for dependencies...
Server running at http://0.0.0.0:5000
2023-09-18T19:00:53.577Z vite:deps Crawling dependencies using entries: 
  /app/renderer/_default.page.client.js
  /app/renderer/_error.page.vue
  /app/pages/about/index.page.vue
  /app/pages/index/index.page.vue
2023-09-18T19:00:53.974Z vite:resolve 0.85ms ./app -> /app/renderer/app.js
2023-09-18T19:00:54.268Z vite:resolve 0.67ms ./Counter.vue -> /app/pages/index/Counter.vue
2023-09-18T19:00:54.273Z vite:resolve 0.83ms vue -> /app/node_modules/vue/dist/vue.runtime.esm-bundler.js
2023-09-18T19:00:54.370Z vite:resolve 0.24ms ./PageShell.vue -> /app/renderer/PageShell.vue
2023-09-18T19:00:54.467Z vite:resolve 84.25ms ./usePageContext -> /app/renderer/usePageContext.js
2023-09-18T19:00:54.869Z vite:resolve 0.24ms ./Link.vue -> /app/renderer/Link.vue
2023-09-18T19:00:55.372Z vite:deps Scan completed in 1902.51ms: 
  vue -> /app/node_modules/vue/dist/vue.runtime.esm-bundler.js
2023-09-18T19:00:56.369Z vite:resolve 0.95ms @vue/runtime-dom -> /app/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js
2023-09-18T19:00:56.474Z vite:resolve 1.23ms @vue/runtime-core -> /app/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js
2023-09-18T19:00:56.577Z vite:resolve 0.43ms @vue/shared -> /app/node_modules/@vue/shared/dist/shared.esm-bundler.js
2023-09-18T19:00:57.071Z vite:resolve 0.81ms @vue/reactivity -> /app/node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js
2023-09-18T19:00:58.372Z vite:deps Dependencies bundled in 2902.70ms
7:01:18 PM [vite-plugin-ssr][request(1)] HTTP request: /
2023-09-18T19:01:18.600Z vite:resolve 1.09ms virtual:vite-plugin-ssr:importUserCode:server -> virtual:vite-plugin-ssr:importUserCode:server
2023-09-18T19:01:18.604Z vite:load 1.95ms [plugin] virtual:vite-plugin-ssr:importUserCode:server
2023-09-18T19:01:21.780Z vite:resolve 0.84ms /pages/about/index.page.vue -> /app/pages/about/index.page.vue
2023-09-18T19:01:21.780Z vite:resolve 0.89ms /pages/index/index.page.vue -> /app/pages/index/index.page.vue
2023-09-18T19:01:21.780Z vite:resolve 0.89ms /renderer/_error.page.vue -> /app/renderer/_error.page.vue
2023-09-18T19:01:21.780Z vite:resolve 0.89ms /renderer/_default.page.server.js -> /app/renderer/_default.page.server.js
2023-09-18T19:01:21.780Z vite:resolve 0.89ms /renderer/_default.page.client.js?extractExportNames&lang.js -> /app/renderer/_default.page.client.js?extractExportNames&lang.js
2023-09-18T19:01:21.781Z vite:import-analysis 3.76ms [5 imports rewritten] virtual:vite-plugin-ssr:importUserCode:server
2023-09-18T19:01:21.783Z vite:transform 3179.03ms virtual:vite-plugin-ssr:importUserCode:server
Error: [vite-plugin-ssr@0.4.141][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at removeBaseServer (file:///app/node_modules/vite-plugin-ssr/dist/esm/utils/parseUrl-extras.js:31:5)
    at getPermanentRedirect (file:///app/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage.js:329:28)
    at renderPageAndPrepare (file:///app/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage.js:89:40)
    at file:///app/node_modules/vite-plugin-ssr/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:68:35
    at renderPage (file:///app/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage.js:46:50)
    at file:///app/server/index.js:57:25
```

**Comment by brillout** [comment]
Thanks for the bug report, let me have a look.

**Comment by brillout** [comment]
Hm, I don't see why this is happening. Can you publish a reproductoin?

**Comment by henriqueabdala-mb** [comment]
no.. i can't...

i change to production mode look this logs:
```

> server
> node ./server

Server running at http://0.0.0.0:5000
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
```

i will google this

**Comment by brillout** [comment]
> I'm trying to deploy a clean vue vanila vite-plugin-ssr application [...] my only changes were the base-path in vite.config.js and add the HOST IP in express...

Why can't you publish a reproduction then?

**Comment by henriqueabdala-mb** [comment]
sry...


https://github.com/henriqueabdala-mb/vite-error

**Comment by brillout** [comment]
What are the reproduction steps?

**Comment by henriqueabdala-mb** [comment]
It's complicated to set up a reproduction step, since I'm not using any container system like Docker.

Btw. I found the problem, it is related to the writeEarlyHints function, I don't have permission to access the folder. I had to change my infrastructure access to map.

**Comment by brillout** [comment]
> it is related to the writeEarlyHints 

So it isn't related to vite-plugin-ssr after all? I guess we can close this then.
