### ISSUE TITLE
Vue-router with vite-ssr

### ISSUE THREAD

**Issue by alsyapukov** [brillout/vite-plugin-ssr#14]
The problem was when using sсoped styles together with a router-link in one component, I took a ready-made example that was here but it gave an error

file: pages/Home.vue

```
<template>
  <h1>Home</h1>
  <p>This content is rendered to HTML.</p>
  <router-link to="/lol">Home</router-link>
</template>

<style scoped>
h1 {
  color: green;
}
</style>
```

Error

```
Error: Unable to parse {"file":"/","line":4,"column":299}
2  |      <html>
3  |        <body>
4  |          <div id="app"><!--[--><div><a aria-current="page" href="/" class="router-link-active router-link-exact-active">Home</a> | <a href="/about" class="">About</a><!--[--><h1 data-v-7f245110>Home</h1><p data-v-7f245110>This content is rendered to HTML.</p><a href="/lol" class="" data-v-7f245110 data-v-7f245110>Home</a><!--]--></div><div><button>count is: 0</button></div><!--]--></div>
   |
                                                                                     ^
5  |        </body>
6  |      </html>
    at traverseHtml (D:\vite-plugin-ssr-master\vite-plugin-ssr-master\examples\vue-router\node_modules\vite\dist\node\chunks\dep-efe32886.js:23936:15)
    at async devHtmlHook (D:\vite-plugin-ssr-master\vite-plugin-ssr-master\examples\vue-router\node_modules\vite\dist\node\chunks\dep-efe32886.js:59458:5)
    at async applyHtmlTransforms (D:\vite-plugin-ssr-master\vite-plugin-ssr-master\examples\vue-router\node_modules\vite\dist\node\chunks\dep-efe32886.js:24202:21)
    at async applyViteHtmlTransform (D:\vite-plugin-ssr-master\vite-plugin-ssr-master\examples\vue-router\node_modules\vite-plugin-ssr\dist\renderPage.node.js:227:20)
    at async renderPageId (D:\vite-plugin-ssr-master\vite-plugin-ssr-master\examples\vue-router\node_modules\vite-plugin-ssr\dist\renderPage.node.js:114:20)
    at async renderPage (D:\vite-plugin-ssr-master\vite-plugin-ssr-master\examples\vue-router\node_modules\vite-plugin-ssr\dist\renderPage.node.js:63:24)
    at async D:\vite-plugin-ssr-master\vite-plugin-ssr-master\examples\vue-router\server\index.js:28:20
[vite-plugin-ssr][Warning] No `_error.page.js` found. We recommend creating a `_error.page.js` file. (This warning is not shown in production.)
```

**Comment by alsyapukov** [comment]
Thanks for the answer. I want to use a vue-router so that the transition to a certain route does not reload the page and when a new page is loaded, a pure html without styles is not loaded (it does not look very good), and the transition from route to route can be animated with some kind of preloader.

**Comment by brillout** [comment]
I'm actually working on this right now: after the new beta release (ETA today) you'll be able to easily do client-side routing with `vite-plugin-ssr`'s built-in router.

I'm also going to improve the Routing doc section to explain why client-side routing is opt-in and not the default (in a nutshell: because it complexities the architecture of your app - but if you're aware and fine with that then go ahead with CSR).

It'd be nice if you open this ticket on the Vite repo. You found an important bug and the Vite folks should know about it.

I'll let you know once CSR is implemented and released.

**Comment by alsyapukov** [comment]
Thank's, I'm created issue https://github.com/vitejs/vite/issues/2644
While that will work with FS routing

**Comment by brillout** [comment]
It's implemented and I'm polishing now; I'll release it tomorrow.

**Comment by brillout** [comment]
Client-side Routing has landed.

https://github.com/brillout/vite-plugin-ssr#routing

Let me know if you have questions.

**Comment by brillout** [comment]
Also let me know if `useClientRouter()` works for you as a replacement to Vue Router. I'm curious.

**Comment by alsyapukov** [comment]
@brillout Sorry for the long answer, it doesn't work for me, I get this error
```
npm run dev

> @ dev D:\work\vite-plugin-ssr-master\examples\vue
> ts-node ./server

failed to load config from D:\work\vite-plugin-ssr-master\examples\vue\vite.config.ts
(node:17628) UnhandledPromiseRejectionWarning: D:\work\vite-plugin-ssr-master\examples\vue\node_modules\vite-plugin-ssr\plugin\index.ts:1
import { Plugin, UserConfig } from 'vite'
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at require.extensions.<computed> (D:\work\vite-plugin-ssr-master\examples\vue\node_modules\ts-node\src\index.ts:1045:43)
    at Object.require.extensions.<computed> [as .ts] (D:\work\vite-plugin-ssr-master\examples\vue\node_modules\vite\dist\node\chunks\dep-6e02b235.js:46332:13)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:\work\vite-plugin-ssr-master\examples\vue\vite.config.ts:31:32)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
(node:17628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17628) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by brillout** [comment]
What is your Node.js version?

**Comment by alsyapukov** [comment]
@brillout v12.6.0

**Comment by brillout** [comment]
vite-plugin-ssr uses named exports which IIRC is available only from >=v12.7

**Comment by brillout** [comment]
I doubled checked and yes Node.js added support for subpath exports in `v12.7.0`.

**Comment by brillout** [comment]
Actually, Node.js initially shipped a buggy implementation. It should work with `v12.19.0`. Let me know if you run into any other issue.
