### ISSUE TITLE
Issue upgrading from from 0.1.0-beta.17 to 0.1.0-beta.18

### ISSUE THREAD

**Issue by chrisvariety** [brillout/vite-plugin-ssr#17]
running `vite build && vite build --ssr` in beta.17 works great, on beta.18 I'm seeing:

```
yarn build
yarn run v1.22.10
$ vite build && vite build --ssr
vite v2.1.2 building for production...
✓ 739 modules transformed.
dist/client/assets/logo.3cedc8da.svg                                     0.70kb
dist/client/manifest.json                                                1.54kb
dist/client/assets/_error.page.b5099f66.js                               0.34kb / brotli: 0.18kb
dist/client/assets/all.page.92fdd9ff.js                                  0.20kb / brotli: 0.12kb
dist/client/assets/index.page.e794d9eb.js                                0.44kb / brotli: 0.21kb
dist/client/assets/all.page.route.75506379.js                            0.05kb / brotli: 0.05kb
dist/client/assets/signup.page.route.774ca72d.js                         0.08kb / brotli: 0.08kb
dist/client/assets/signup.page.993c3da0.js                               29.28kb / brotli: 9.13kb
dist/client/assets/pages/_default/_default.page.client.tsx.cc6ca426.js   243.40kb / brotli: 67.29kb
vite v2.1.2 building SSR bundle for production...
 > node_modules/vite/dist/node/chunks/dep-efe32886.js:31549:7: error: [vite:dep-scan] No known conditions for "." entry in "vite-plugin-ssr" package
    31549 │   throw new Error(
          ╵         ^
    at bail (/Users/chrismcc/workspace/ss/node_modules/vite/dist/node/chunks/dep-efe32886.js:31549:8)
    at resolve$1 (/Users/chrismcc/workspace/ss/node_modules/vite/dist/node/chunks/dep-efe32886.js:31605:32)
    at resolveExports (/Users/chrismcc/workspace/ss/node_modules/vite/dist/node/chunks/dep-efe32886.js:32022:12)
    at resolvePackageEntry (/Users/chrismcc/workspace/ss/node_modules/vite/dist/node/chunks/dep-efe32886.js:31950:22)
    at tryNodeResolve (/Users/chrismcc/workspace/ss/node_modules/vite/dist/node/chunks/dep-efe32886.js:31847:11)
    at Context.resolveId (/Users/chrismcc/workspace/ss/node_modules/vite/dist/node/chunks/dep-efe32886.js:31730:28)
    at Object.resolveId (/Users/chrismcc/workspace/ss/node_modules/vite/dist/node/chunks/dep-efe32886.js:43592:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async resolve (/Users/chrismcc/workspace/ss/node_modules/vite/dist/node/chunks/dep-efe32886.js:43786:26)
    at async /Users/chrismcc/workspace/ss/node_modules/vite/dist/node/chunks/dep-efe32886.js:43871:34

   node_modules/vite/dist/node/chunks/dep-efe32886.js:43861:18: note: This error came from the "onResolve" callback registered here
    43861 │             build.onResolve({
          ╵                   ~~~~~~~~~
    at setup (/Users/chrismcc/workspace/ss/node_modules/vite/dist/node/chunks/dep-efe32886.js:43861:19)
    at handlePlugins (/Users/chrismcc/workspace/ss/node_modules/esbuild/lib/main.js:686:7)
    at Object.buildOrServe (/Users/chrismcc/workspace/ss/node_modules/esbuild/lib/main.js:903:44)
    at /Users/chrismcc/workspace/ss/node_modules/esbuild/lib/main.js:1436:17
    at new Promise (<anonymous>)
    at Object.build (/Users/chrismcc/workspace/ss/node_modules/esbuild/lib/main.js:1435:14)
    at Object.build (/Users/chrismcc/workspace/ss/node_modules/esbuild/lib/main.js:1326:51)
    at /Users/chrismcc/workspace/ss/node_modules/vite/dist/node/chunks/dep-efe32886.js:43740:54
    at Array.map (<anonymous>)

   pages/_default/_default.page.server.tsx:6:21: note: The plugin "vite:dep-scan" was triggered by this import
        6 │ import { html } from 'vite-plugin-ssr';
          ╵                      ~~~~~~~~~~~~~~~~~

error during build:
Error: Build failed with 1 error:
node_modules/vite/dist/node/chunks/dep-efe32886.js:31549:7: error: [vite:dep-scan] No known conditions for "." entry in "vite-plugin-ssr" package
    at failureErrorWithLog (/Users/chrismcc/workspace/ss/node_modules/esbuild/lib/main.js:1216:15)
    at buildResponseToResult (/Users/chrismcc/workspace/ss/node_modules/esbuild/lib/main.js:936:32)
    at /Users/chrismcc/workspace/ss/node_modules/esbuild/lib/main.js:1035:20
    at /Users/chrismcc/workspace/ss/node_modules/esbuild/lib/main.js:568:9
    at handleIncomingPacket (/Users/chrismcc/workspace/ss/node_modules/esbuild/lib/main.js:657:9)
    at Socket.readFromStdout (/Users/chrismcc/workspace/ss/node_modules/esbuild/lib/main.js:535:7)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Seems like it may stem from this change: https://github.com/brillout/vite-plugin-ssr/commit/4cfe4ef30aeb3c1f6b276cd04c6b405538914bf8#diff-cc5a2f170768969f124108ad3be7fdbcbed774c11774d99a87a3a78fef4ab97bR24

**Comment by brillout** [comment]
I could reproduce, I will have a look at it.

**Comment by brillout** [comment]
It's fixed on the latest release; pin your vps dep to `0.1.0-beta.20` and also pin Vite to `2.1.3`.

**Comment by chrisvariety** [comment]
Works like a charm, thanks so much ✨

**Comment by brillout** [comment]
Let me know if there is anything else. I'm more than open for critical feedback.
