### ISSUE TITLE
useRoute and useRouter return undefined

### ISSUE THREAD

**Issue by u007** [brillout/vite-plugin-ssr#193]
I'am unable to get both within my vue project,
using:
```
  "vue-router": "^4.0.12"
```

```
import { useRoute, useRouter } from 'vue-router';
const $route = useRoute()
const $router = useRouter()
console.log('router?', $route, $router)
```
got these:
```
[Vue warn]: injection "Symbol([vue-router]: route location)" not found.
[Vue warn]: injection "Symbol([vue-router]: router)" not found.
router? undefined undefined
```

**Comment by brillout** [comment]
This doesn't seem related to vite-plugin-ssr

**Comment by u007** [comment]
but it didnt happen with my other project running on voie and vite

**Comment by brillout** [comment]
I need you to 1. dig more before you ask for help and 2. provide a minimal reproduction showcasing in what ways `vite-plugin-ssr` is causing you a problem.

**Comment by u007** [comment]
sample repo https://github.com/u007/vuerouterissue1

**Comment by u007** [comment]
Hi,
accessing http://localhost:3330/login returns:

```
[Vue warn]: injection "Symbol([vue-router]: router)" not found.
[Vue warn]: injection "Symbol([vue-router]: route location)" not found.
[Vue warn]: injection "Symbol([vue-router]: router)" not found.
router? undefined undefined
[Vue warn]: Unhandled error during execution of setup function 
  at <Login>
TypeError: Cannot read property 'query' of undefined
    at setup (/home/james/www/vuerouterissue1/components/login/login.vue:47:30)
    at _sfc_main.setup (/components/login/login.vue:219:23)
    at callWithErrorHandling (/home/james/www/vuerouterissue1/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6599:22)
    at setupStatefulComponent (/home/james/www/vuerouterissue1/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6225:29)
    at setupComponent (/home/james/www/vuerouterissue1/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6181:11)
    at renderComponentVNode (/home/james/www/vuerouterissue1/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)
    at renderVNode (/home/james/www/vuerouterissue1/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)
    at renderComponentSubTree (/home/james/www/vuerouterissue1/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
    at /home/james/www/vuerouterissue1/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:211:29

```

**Comment by brillout** [comment]
I don't see where you integrate `vue-router`?

**Comment by u007** [comment]
inside components/login/login.vue

**Comment by u007** [comment]
https://github.com/u007/vuerouterissue1/blob/master/components/login/login.vue

**Comment by brillout** [comment]
This doesn't seem to be related to vite-plugin-ssr

**Comment by u007** [comment]
ya sorry realise it happen to vue and vite without this plugin
thank you
