### ISSUE TITLE
React 18 renderToPipeableStream  + pre-rendering throws error

### ISSUE THREAD

**Issue by icaraps** [brillout/vite-plugin-ssr#203]
Hi, first of all hats off ! This is an awesome plugin 👍 

I'm trying to run the plugin with React 18 `renderToPipeableStream` + `hydrateRoot` + `render` API changes and its runs fine but if I try to do pre-rendering, it throws the following error: 

```
Error: [vite-plugin-ssr@0.3.26][Internal Failure] You stumbled upon a bug in `vite-plugin-ssr`'s source code (an internal `assert()` failed). This should definitely not be happening, and you should create a new GitHub issue at https://github.com/brillout/vite-plugin-ssr/issues/new that includes this error stack (the error stack is usually enough to debug internal errors). Or reach out on Discord. A fix will be written promptly.
    at Writable.write [as _write] (/project/node_modules/vite-plugin-ssr/dist/cjs/node/html/stream.js:66:32)
    at write (/project/node_modules/vite-plugin-ssr/dist/cjs/node/html/stream.js:212:42)
    at /project/node_modules/vite-plugin-ssr/dist/cjs/node/html/stream.js:215:47
    at Array.forEach (<anonymous>)
    at writeData (/project/node_modules/vite-plugin-ssr/dist/cjs/node/html/stream.js:215:32)
    at write (/project/node_modules/vite-plugin-ssr/dist/cjs/node/html/stream.js:150:13)
    at onData (/project/node_modules/vite-plugin-ssr/dist/cjs/node/html/stream.js:173:13)
    at async Writable.write [as _write] (/project/aio-site-template/node_modules/vite-plugin-ssr/dist/cjs/node/html/stream.js:242:17)
```

**Comment by brillout** [comment]
In principle, pre-rendering does support a streaming integration.

Let me have a look.

**Comment by brillout** [comment]
It's an encoding issue. Can you insert

```diff
  // node_modules/vite-plugin-ssr/dist/cjs/node/html/stream.js:66:32
+ console.log('encoding: '+encoding)
  (0, utils_1.assert)(encoding === 'utf8');
```
and tell me the result.

**Comment by brillout** [comment]
Also let's remove the assert and see what happens.

**Comment by icaraps** [comment]
yes `ReactDOMServer.renderToNodeStream` works fine

encoding: buffer

and it works fine if I remove the assert

**Comment by brillout** [comment]
Fix released in `v0.3.27`.

**Comment by icaraps** [comment]
Thanks for the swift responses 🚀

**Comment by snake-py** [comment]
Hmm I also try to switch over to `renderToPipeableStream` while using SSG. Is there an example how this would look?
