### ISSUE TITLE
Build error with 0.3.30

### ISSUE THREAD

**Issue by magne4000** [brillout/vite-plugin-ssr#208]
```
Error: [vite-plugin-ssr@0.3.30][Internal Failure] You stumbled upon a bug in `vite-plugin-ssr`'s source code (an internal `assert()` failed). This should definitely not behappening, and you should create a new GitHub issue at https://github.com/brillout/vite-plugin-ssr/issues/new that includes this error stack (the error stack is usually enough to debug internal errors). Or reach out on Discord. A fix will be written promptly.
    at getRoot (/home/magne/workspace/website-patch-notes/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/build.js:84:24)
    at browserEntryPoints (/home/magne/workspace/website-patch-notes/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/build.js:63:18)
    at entryPoints (/home/magne/workspace/website-patch-notes/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/build.js:49:16)
    at Object.config (/home/magne/workspace/website-patch-notes/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/build.js:15:59)
    at resolveConfig (/home/magne/workspace/website-patch-notes/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:68223:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async doBuild (/home/magne/workspace/website-patch-notes/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42986:20)
    at async build (/home/magne/workspace/website-patch-notes/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42974:16)
    at async CAC.<anonymous> (/home/magne/workspace/website-patch-notes/node_modules/vite/dist/node/cli.js:737:9)
```

**Comment by brillout** [comment]
Let me have a look

**Comment by magne4000** [comment]
I found what triggered it, I added a `root: '.'` in my vercel config during testing, removing it fixes the issue. Is this intended?

**Comment by brillout** [comment]
`vite-plugin-ssr` expects an absolute path. I thought Vite would normalize `root` and provide an absolute path to plugins. Did you update VIte recently?

**Comment by magne4000** [comment]
yes, yesterday to latest version

**Comment by brillout** [comment]
I'll have a look it.

Provide an absolute path in the meantime.

**Comment by brillout** [comment]
Checked Vite's source code; it does normalize `root`.

> I added a root: '.' in my vercel config during testing

Where exactly did you add `root: '.'`? Is that in your Vercel's serverless function? (I'm wondering if Vercel maybe has an erroneous `path.resolve()` shim.)

**Comment by magne4000** [comment]
I added it in `vite.config.js`, that's all

**Comment by brillout** [comment]
It will now show a proper error message telling you to use an absolute path.

Let me know if that's a problem for you.

**Comment by magne4000** [comment]
Not an issue :+1:
