### ISSUE TITLE
Error when opening a pre-rendered page. It shows a white screen.

### ISSUE THREAD

**Issue by DhvanilPatel** [brillout/vite-plugin-ssr#252]
Error: [vite-plugin-ssr@0.3.36][Internal Failure] You stumbled upon a bug in the source code of vite-plugin-ssr (an internal assertion failed). This should not be happening: please reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). Please do reach out as it helps make vite-plugin-ssr more robust. A fix will be written promptly (usually under 24 hours). Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): `{"url":"//wp/wp-includes/wlwmanifest.xml"}`.

```
at parseUrl (/home/node/app/node_modules/vite-plugin-ssr/dist/cjs/shared/utils/parseUrl.js:55:29)
at handlePageContextRequestSuffix (/home/node/app/node_modules/vite-plugin-ssr/dist/cjs/shared/utils/getFileUrl.js:42:46)
at _parseUrl (/home/node/app/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:658:117)
at initializePageContext (/home/node/app/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:109:50)
at renderPage (/home/node/app/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:21:31)
at renderPageWithoutThrowing (/home/node/app/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:126:33)
at /home/node/app/server/index.js:34:31
at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
at next (/home/node/app/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/home/node/app/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
at /home/node/app/node_modules/express/lib/router/index.js:281:22
at param (/home/node/app/node_modules/express/lib/router/index.js:354:14)
at param (/home/node/app/node_modules/express/lib/router/index.js:365:14)
at Function.process_params (/home/node/app/node_modules/express/lib/router/index.js:410:3)
at next (/home/node/app/node_modules/express/lib/router/index.js:275:10)
at SendStream.error (/home/node/app/node_modules/serve-static/index.js:121:7)
at SendStream.emit (events.js:315:20)
at SendStream.error (/home/node/app/node_modules/send/index.js:270:17)
at SendStream.onStatError (/home/node/app/node_modules/send/index.js:421:12)
at onstat (/home/node/app/node_modules/send/index.js:726:26)
at FSReqCallback.oncomplete (fs.js:183:21)
```

**Comment by brillout** [comment]
Fix released in `v0.3.51`.
