### ISSUE TITLE
Error when evaluating SSR module

### ISSUE THREAD

**Issue by NunoSav** [brillout/vite-plugin-ssr#259]
While this might be a Vite issue maybe i can get a hint why i get this behaviour.

I created a new project with:
```
npm init vite-plugin-ssr@latest
```
added `@ionic/vue@6.05` and `vue-router@4.0.12` as dependencies

on `renderer/app.ts`:
```ts
(...)
import { IonicVue } from "@ionic/vue";
(...)
const app = createSSRApp(PageWithLayout).use(IonicVue)
(...)
```

`vite.config.ts`:
```ts
import vue from '@vitejs/plugin-vue'
import ssr from 'vite-plugin-ssr/plugin'
import { UserConfig } from 'vite'

const config: UserConfig = {
  plugins: [vue(), ssr()],
  optimizeDeps: {
    include: ['@ionic/core', '@stencil/core']
  }
}

export default config
```

<details><summary>Trying to run this will return the following errors:</summary>
<p>

```
16:44:21 [vite] Error when evaluating SSR module /renderer/app.ts:
/Users/nur/Desktop/Work/playground/vite-ssr-project/node_modules/@ionic/core/components/ion-accordion.js:4
import { HTMLElement, h, Host, proxyCustomElement } from '@stencil/core/internal/client';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/nur/Desktop/Work/playground/vite-ssr-project/node_modules/@ionic/vue/dist/index.js:6:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
16:44:21 [vite] Error when evaluating SSR module /renderer/_default.page.server.ts:
/Users/nur/Desktop/Work/playground/vite-ssr-project/node_modules/@ionic/core/components/ion-accordion.js:4
import { HTMLElement, h, Host, proxyCustomElement } from '@stencil/core/internal/client';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/nur/Desktop/Work/playground/vite-ssr-project/node_modules/@ionic/vue/dist/index.js:6:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```
</p></details>

<details><summary>Full list of dependencies:</summary>
<p>

```
  "dependencies": {
    "@ionic/vue": "6.0.5",
    "@types/compression": "^1.7.2",
    "@types/express": "^4.17.13",
    "@types/node": "^17.0.16",
    "@vitejs/plugin-vue": "^2.2.0",
    "@vue/server-renderer": "^3.2.30",
    "compression": "^1.7.4",
    "cross-env": "^7.0.3",
    "express": "^4.17.2",
    "ts-node": "^10.5.0",
    "typescript": "^4.5.5",
    "vite": "^2.8.0",
    "vite-plugin-ssr": "^0.3.51",
    "vue": "^3.2.30",
    "vue-router": "^4.0.12"
  }
```

</p></details>

I've went through the issues on Vite repo and tried the suggested fixes but nothing worked. Any help is much appreciated.

**Comment by brillout** [comment]
Not only is it unrelated to vite-plugin-ssr but it's also unrelated to Vite.

**Comment by naveennamani** [comment]
I may be late, I don't know if you solved it or not, but I faced the same issue with `@mdx-js/react` package. You can have a look at my blog post on how I was able to solve it. https://dev.to/naveennamani/using-vite-plugin-ssr-with-mdx-js-solving-esm-only-library-problems-understanding-vite-configuration-and-writing-vite-plugins-3b24
