### ISSUE TITLE
Error: You stumbled upon a bug 

### ISSUE THREAD

**Issue by jiv-e** [brillout/vite-plugin-ssr#268]
Hi!

Doing as instructed. Thanks!

```
Error: [vite-plugin-ssr@0.3.58][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. (In case you are curious: a `assert()` failed.) Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it actullay helps make vite-plugin-ssr more robust. 
    at renderTemplate (/projectPath/node_modules/vite-plugin-ssr/dist/cjs/node/html/renderHtml.js:184:24)
    at renderHtml (/projectPath/node_modules/vite-plugin-ssr/dist/cjs/node/html/renderHtml.js:37:24)
    at executeRenderHook (/projectPath/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:567:58)
    at async renderPage (/projectPath/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:89:30)
    at async renderPageWithoutThrowing (/projectPath/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:131:16)
    at async /projectPath/server/index.js:35:25
```

**Comment by brillout** [comment]
What's your `escapeInject` string that leads to that error?

**Comment by jiv-e** [comment]
I accidentally called escapeInject as a function, like this:
```
const documentHtml = escapeInject('test')
```
It caused the error above. It would be nice to catch that with a helpful error message.
Using it as a string literal seems to work as it should.

```
const documentHtml = escapeInject`test`
```

**Comment by brillout** [comment]
Yes.

> actullay

I'm also seeing there is a typo.

**Comment by brillout** [comment]
Done. Let me know if you run into any other paper cuts. I do intent to make vps paper-cut-free.

**Comment by jiv-e** [comment]
Nice! Thank you. 🙂
