### ISSUE TITLE
Debian not supported by playwright

### ISSUE THREAD

**Issue by jrson83** [brillout/vite-plugin-ssr#283]
It should really be mentioned in the [CONTRIBUTING.md](https://github.com/brillout/vite-plugin-ssr/blob/master/CONTRIBUTING.md), that `playwright`, which needs to be installed in order to run the tests, [only supports Ubuntu](https://github.com/microsoft/playwright/issues/8361) and not Debian.

Since the guide has the note `(Windows may work but there are no guarantees.)`, I setup a completely new VM with Debian 11 just to make sure everything is working. After finishing all the code and wanted to run the tests and get the error:

```shell
> @ test:jest /var/www/html/vite-plugin-ssr/libframe/test
> jest --config=./jest.config.ts --runInBand --bail "examples/nano-jsx-client-routing/"

Error: 
╔════════════════════════════════════════════════════════════╗
║ Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     sudo npx playwright install-deps                       ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
    at validateDependenciesLinux (/var/www/html/vite-plugin-ssr/node_modules/.pnpm/playwright-core@1.18.1/node_modules/playwright-core/lib/utils/dependencies.js:204:11)
    at Registry._validateHostRequirements (/var/www/html/vite-plugin-ssr/node_modules/.pnpm/playwright-core@1.18.1/node_modules/playwright-core/lib/utils/registry.js:484:43)
    at Chromium._launchProcess (/var/www/html/vite-plugin-ssr/node_modules/.pnpm/playwright-core@1.18.1/node_modules/playwright-core/lib/server/browserType.js:200:7)
    at Chromium._innerLaunch (/var/www/html/vite-plugin-ssr/node_modules/.pnpm/playwright-core@1.18.1/node_modules/playwright-core/lib/server/browserType.js:127:9)
    at ProgressController.run (/var/www/html/vite-plugin-ssr/node_modules/.pnpm/playwright-core@1.18.1/node_modules/playwright-core/lib/server/progress.js:101:22)
    at Chromium.launch (/var/www/html/vite-plugin-ssr/node_modules/.pnpm/playwright-core@1.18.1/node_modules/playwright-core/lib/server/browserType.js:81:21)
    at BrowserServerLauncherImpl.launchServer (/var/www/html/vite-plugin-ssr/node_modules/.pnpm/playwright-core@1.18.1/node_modules/playwright-core/lib/browserServerImpl.js:60:21)
    at PlaywrightRunner.launchServer (/var/www/html/vite-plugin-ssr/node_modules/.pnpm/jest-playwright-preset@1.7.0_jest@27.5.1/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:69:44)
    at PlaywrightRunner.getTests (/var/www/html/vite-plugin-ssr/node_modules/.pnpm/jest-playwright-preset@1.7.0_jest@27.5.1/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:90:36)
    at PlaywrightRunner.runTests (/var/www/html/vite-plugin-ssr/node_modules/.pnpm/jest-playwright-preset@1.7.0_jest@27.5.1/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:123:30)

 ELIFECYCLE  Command failed with exit code 1.
Error: Command failed: pnpm run test:jest examples/nano-jsx-client-routing/
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at runScript (/var/www/html/vite-plugin-ssr/libframe/test/runAll.ts:19:3)
    at Object.<anonymous> (/var/www/html/vite-plugin-ssr/libframe/test/runAll.ts:16:1)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Module.m._compile (/var/www/html/vite-plugin-ssr/node_modules/.pnpm/ts-node@9.1.1_typescript@4.5.5/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/var/www/html/vite-plugin-ssr/node_modules/.pnpm/ts-node@9.1.1_typescript@4.5.5/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
 ELIFECYCLE  Test failed. See above for more details.
 ELIFECYCLE  Test failed. See above for more details.
```
I tried to find some alternative packages but gave up now. Gonna try to run the tests tomorrow with windows again.

**Comment by brillout** [comment]
PR welcome to add a note about this in CONTRIBUTING.md

Closing in the meantime.

**Comment by brillout** [comment]
# Testing on Debian

To run the test suite on Debian, additional dependencies are needed to install [playwright](https://github.com/microsoft/playwright).

  #### Installing playwright

  When running the test suite on Debian, playwright prompts to install its dependencies using:

  ```shell
  npx playwright install-deps
  ```

  According to the playwright's [system requirements](https://playwright.dev/docs/library#system-requirements), only Ubuntu is officially supported, so when running the command, it tries to install the required packages `libjpeg-turbo8` and `libicu66` with apt-get, which does not exist in the Debian sources list.

  #### Resolve missing dependencies

  To resolve the missing dependencies, you can:

  1. either follow the error messages and install all dependencies manually
  2. add `non-free` sources to `sources.list` and install `libjpeg-turbo8` and `libicu66` manually

  To add the `non-free` sources to `deb` and `deb-src`:

  ```shell
  sudo nano /etc/apt/sources.list

  # add the sources

  deb http://deb.debian.org/debian/ bullseye main non-free
  deb-src http://deb.debian.org/debian/ bullseye main non-free

  # update package information

  sudo apt-get update
  ```

  Download the official Ubuntu `libjpeg-turbo8` and `libicu66` packages from [pkgs.org](https://pkgs.org/) using `wget`:

  - [libjpeg-turbo8](https://pkgs.org/download/libjpeg-turbo8)
  - [libicu66](https://pkgs.org/download/libicu66)

  You should be able to install both packages, since the required dependencies will be resolved automatically through the non-free sources:

  ```shell
  wget <url-topackage>.deb
  dpkg -i <package>.deb
  ```

  With all packages successfully installed, you can finally install `playwright`:

  ```shell
  npx playwright install-deps
  ``` 
</details>
