### ISSUE TITLE
Prerendering: require() of ES Module is not supported

### ISSUE THREAD

**Issue by naveennamani** [brillout/vite-plugin-ssr#289]
I'm using `examples/react-full` template for the following issue.

I'm using mdx-js MDXProvider to pass components to mdx pages. I tried to use `@mdx-js/react` as an providerImportSource option in config file as explained in [mdxjs website](https://mdxjs.com/docs/using-mdx/#mdx-provider). The changes in `vite.config.js` are

```diff
// vite.config.js
- plugins: [react(), mdx(), ssr()]
+ plugins: [react(), mdx({providerImportSource: "@mdx-js/react"}), ssr()]
```
When I build the modules for ssr using `vite build --ssr` the following is the output for the build files in `dist/server/assets` folder.

```js
// filename: markdown.page.abcdef.js

"use strict";
exports[Symbol.toStringTag] = "Module";
var jsxRuntime = require("react/jsx-runtime");
var react = require("@mdx-js/react");
var Counter = require("./Counter.e9df5995.js");
require("react");
const documentProps = {
  title: "Some Markdown Page"
};
function MDXContent(props = {}) {
  const { wrapper: MDXLayout } = Object.assign({}, react.useMDXComponents(), props.components);
  return MDXLayout ? jsxRuntime.jsx(MDXLayout, Object.assign({}, props, {
    children: jsxRuntime.jsx(_createMdxContent, {})
  })) : _createMdxContent();
  function _createMdxContent() {
    const _components = Object.assign({
      h1: "h1",
      p: "p",
      em: "em"
    }, react.useMDXComponents(), props.components);
    return jsxRuntime.jsxs(jsxRuntime.Fragment, {
      children: [jsxRuntime.jsx(_components.h1, {
        children: "Markdown"
      }), "\n", jsxRuntime.jsxs(_components.p, {
        children: ["This page is written in ", jsxRuntime.jsx(_components.em, {
          children: "Markdown"
        }), "."]
      }), "\n", jsxRuntime.jsxs(_components.p, {
        children: ["MDX allows us to include interactive components in the markdown. ", jsxRuntime.jsx(Counter.Counter, {})]
      })]
    });
  }
}
exports["default"] = MDXContent;
exports.documentProps = documentProps;
```

As can be observed in the built file, there is a `require("@mdx-js/react")` statement. When `vite-plugin-ssr prerender` is run, the import statement is failing as `@mdx-js/react` is an ESM only module. The following is the error output.
```
/workspace/vite-plugin-ssr/examples/react-full/dist/server/assets/markdown.page.b180d62f.js:4
var react = require("@mdx-js/react");
            ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /workspace/vite-plugin-ssr/node_modules/.pnpm/@mdx-js+react@2.0.0_e32785dbcafa2fde92a71a8f50f52ce6/node_modules/@mdx-js/react/index.js from /workspace/vite-plugin-ssr/examples/react-full/dist/server/assets/markdown.page.b180d62f.js not supported.
Instead change the require of index.js in /workspace/vite-plugin-ssr/examples/react-full/dist/server/assets/markdown.page.b180d62f.js to a dynamic import() which is available in all CommonJS modules.
    at Module.<anonymous> (/workspace/vite-plugin-ssr/examples/react-full/dist/server/assets/markdown.page.b180d62f.js:4:13)
    at /workspace/vite-plugin-ssr/examples/react-full/dist/server/pageFiles.js:8:12
    at async /workspace/vite-plugin-ssr/vite-plugin-ssr/dist/cjs/shared/loadPageIsomorphicFiles.js:17:33
    at async Promise.all (index 0)
    at async loadPageIsomorphicFiles (/workspace/vite-plugin-ssr/vite-plugin-ssr/dist/cjs/shared/loadPageIsomorphicFiles.js:10:61)
    at async loadPageFiles (/workspace/vite-plugin-ssr/vite-plugin-ssr/dist/cjs/node/renderPage.js:322:82)
    at async /workspace/vite-plugin-ssr/vite-plugin-ssr/dist/cjs/node/prerender.js:72:31 {
  code: 'ERR_REQUIRE_ESM'
}
```

This kind of errors may appear with other ESM only packages also. How to overcome this problem without having CJS modules?

**Comment by brillout** [comment]
AFAICT this is unrelated to vps.
