### ISSUE TITLE
Extending Array prototype throws an "You stumbled upon a bug" error

### ISSUE THREAD

**Issue by akolov** [brillout/vite-plugin-ssr#297]
I'm trying to extend Array prototype and import ts file somewhere in my project. Doing so, however, throws the following error:
```
> dev
> npm run server


> server
> ts-node -r tsconfig-paths/register ./server

Server running at http://localhost:3000
Error: [vite-plugin-ssr@0.3.61][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust.
    at addString (/Users/alex/Developer/gated-art-web/node_modules/vite-plugin-ssr/dist/cjs/node/html/renderHtml.js:141:28)
    at renderTemplate (/Users/alex/Developer/gated-art-web/node_modules/vite-plugin-ssr/dist/cjs/node/html/renderHtml.js:151:9)
    at renderHtml (/Users/alex/Developer/gated-art-web/node_modules/vite-plugin-ssr/dist/cjs/node/html/renderHtml.js:37:24)
    at executeRenderHook (/Users/alex/Developer/gated-art-web/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:567:58)
    at async renderPage (/Users/alex/Developer/gated-art-web/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:89:30)
    at async renderPageWithoutThrowing (/Users/alex/Developer/gated-art-web/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:131:16)
    at async /Users/alex/Developer/gated-art-web/server/index.ts:42:25
```

My array extension code is as follows:
```ts
export { }

declare global {

  interface Array<T> {
    compactMap<E>(callback: (t: T) => E | null): Array<E>
  }

}

if (!Array.prototype.compactMap) {

  Array.prototype.compactMap = function<T, E>(callback: (t: T) => E | null): Array<E> {
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    return this.map(callback).filter(x => !!x).map(x => x!)
  }

}
```

Also made a bare bones project to reproduce the issue: https://github.com/akolov/vite-ssr-array-prototype-bug

Is there anything I'm doing wrong?

**Comment by akolov** [comment]
I'm using unmodified project created via `npm init vite-plugin-ssr@latest`.
And escapeInject template is also unmodified:
```ts
const documentHtml = escapeInject`<!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <link rel="icon" href="${logoUrl}" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="${desc}" />
        <title>${title}</title>
      </head>
      <body>
        <div id="app">${dangerouslySkipEscape(appHtml)}</div>
      </body>
    </html>`
```

**Comment by brillout** [comment]
I can't reproduce.

Publish a reproduction and I'll have a look at it.

**Comment by akolov** [comment]
Reproduction project is here https://github.com/akolov/vite-ssr-array-prototype-bug.git
Can reproduce every time, maybe something is odd about my environment. Not sure so any guidance would be greatly appreciated!

```
➜  vite-ssr-array-prototype-bug git:(main) npm run dev

> dev
> npm run server


> server
> ts-node ./server

Server running at http://localhost:3000
Error: [vite-plugin-ssr@0.3.61][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust.
    at addString (/Users/alex/Developer/vite-ssr-array-prototype-bug/node_modules/vite-plugin-ssr/dist/cjs/node/html/renderHtml.js:141:28)
    at renderTemplate (/Users/alex/Developer/vite-ssr-array-prototype-bug/node_modules/vite-plugin-ssr/dist/cjs/node/html/renderHtml.js:151:9)
    at renderHtml (/Users/alex/Developer/vite-ssr-array-prototype-bug/node_modules/vite-plugin-ssr/dist/cjs/node/html/renderHtml.js:37:24)
    at executeRenderHook (/Users/alex/Developer/vite-ssr-array-prototype-bug/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:567:58)
    at async renderPage (/Users/alex/Developer/vite-ssr-array-prototype-bug/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:89:30)
    at async renderPageWithoutThrowing (/Users/alex/Developer/vite-ssr-array-prototype-bug/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:131:16)
    at async /Users/alex/Developer/vite-ssr-array-prototype-bug/server/index.ts:33:25
^C⏎
➜  vite-ssr-array-prototype-bug git:(main) node --version
v16.14.0
```

**Comment by brillout** [comment]
I could reproduce.

This is quite weird indeed. I will dig.

**Comment by brillout** [comment]
Make your Array extension non-enumerable, that'll fix it.

**Comment by akolov** [comment]
This indeed has worked. Thank you for helping!
