### ISSUE TITLE
assertion failure on removePageContextUrlSuffix or getFileUrl with percent encoded query

### ISSUE THREAD

**Issue by vopaldragon** [brillout/vite-plugin-ssr#307]
while I use vite-plugin-ssr/client/router/navigate with percent encoded query(like `navigate("/?keyword=あ")`), I encounterd assertion failure as follows: 

Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): `{"url":"/index.pageContext.json?keyword=%E3%81%82"}`.
    at removePageContextUrlSuffix (\node_modules\vite-plugin-ssr\dist\cjs\utils\getFileUrl.js:54:25)
    at handlePageContextRequestSuffix (\node_modules\vite-plugin-ssr\dist\cjs\utils\getFileUrl.js:46:50)
    at _parseUrl (\node_modules\vite-plugin-ssr\dist\cjs\node\renderPage.js:693:117)
    at initializePageContext (\node_modules\vite-plugin-ssr\dist\cjs\node\renderPage.js:114:50)
    at renderPage (\node_modules\vite-plugin-ssr\dist\cjs\node\renderPage.js:22:31)
    at renderPageWithoutThrowing (\node_modules\vite-plugin-ssr\dist\cjs\node\renderPage.js:131:33)
    at \server\index.ts:30:31
    at Layer.handle [as handle_request] (\node_modules\express\lib\router\layer.js:95:5)
    at next (\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (\node_modules\express\lib\router\layer.js:95:5)
    at \node_modules\express\lib\router\index.js:281:22
    at param (\node_modules\express\lib\router\index.js:360:14)
    at param (\node_modules\express\lib\router\index.js:371:14)
    at Function.process_params (\node_modules\express\lib\router\index.js:416:3)
    at Immediate.next [as _onImmediate] (\node_modules\express\lib\router\index.js:275:10)

If I use encodeURIComponent( `navigate("/?keyword=" + encodeURIComponent("あ"))`), then, assertion at getFileUrl.js fails.

the vite-plugin-ssr maintainers; you can ignore this): `{"url":"/?keyword=%E3%81%82"}`.
    at getFileUrl (getFileUrl.js?v=785fd94f:20:9)
    at retrievePageContext (getPageContext.js?v=785fd94f:80:28)
    at runOnBeforeRenderServerHooks (getPageContext.js?v=785fd94f:187:45)
    at executeOnBeforeRenderHooks (getPageContext.js?v=785fd94f:165:30)
    at loadPageContextAfterRoute (getPageContext.js?v=785fd94f:40:48)
    at async getPageContext (getPageContext.js?v=785fd94f:17:33)
    at async fetchAndRender (useClientRouter.js?v=785fd94f:75:37)
    at async navigateFunction (useClientRouter.js?v=785fd94f:28:9)
    at async navigate (useClientRouter.js?v=785fd94f:125:5)

It seems searchString is decoded while url is still encoded. If I delete assertion, application works correctly.

**Comment by brillout** [comment]
Fix released in `0.3.63`.

**Comment by brillout** [comment]
Actually, use `v0.3.64`.
