### ISSUE TITLE
[bug] Error showing up infrequently in error logs

### ISSUE THREAD

**Issue by keithk** [brillout/vite-plugin-ssr#310]
Hey there, got this showing up _very_ infrequently in the server logs while running this plugin (which is excellent, thank you!!). Let me know if you need any more details beyond the stack trace. 

**Stacktrace:**

Error: [vite-plugin-ssr@0.3.64][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust.

at resolveAsStaticPath (/opt/glitch-community/node_modules/vite-plugin-ssr/dist/cjs/shared/route/resolveFilesystemRoute.js:14:24)
 at resolveFilesystemRoute (/opt/glitch-community/node_modules/vite-plugin-ssr/dist/cjs/shared/route/resolveFilesystemRoute.js:6:12)
 at /opt/glitch-community/node_modules/vite-plugin-ssr/dist/cjs/shared/route.js:54:79
  at Array.map (<anonymous>)
  at route (/opt/glitch-community/node_modules/vite-plugin-ssr/dist/cjs/shared/route.js:49:47)
  at async renderPage (/opt/glitch-community/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:28:25)
   at async renderPageWithoutThrowing (/opt/glitch-community/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:131:16)
 at async /opt/glitch-community/server/server.js:148:21

**Comment by brillout** [comment]
What's the URL when this error occurs? Seems like the URL ends with `//`, choking vite-plugin-ssr.

**Comment by keithk** [comment]
@brillout Ahah. That appears to be it, tracking down the actual bug in sentry shows it happening on an (accidental) double `//` page. Thanks!

**Comment by brillout** [comment]
Fixed, which I will release along `0.4`.
