### ISSUE TITLE
Unable to add custom styles tags on HTML

### ISSUE THREAD

**Issue by fenos** [brillout/vite-plugin-ssr#317]
I'm putting together vite-ssr with react MUI to be server-side rendered.
MUI is using emotion under the hood as CSS in JS solution. 

Following their [documentation](https://emotion.sh/docs/ssr#advanced-approach), i simply need to call a couple of functions that extract the CSS from the app and I will get back a string
with the styles tags ex:

```ts
// _default.page.server.tsx

async function render(pageContext: PageContextBuiltIn & PageContext) {
  const cache = createEmotionCache();
  const { extractCriticalToChunks, constructStyleTagsFromChunks } = createEmotionServer(cache);

  const { Page, pageProps } = pageContext
  const pageHtml = ReactDOMServer.renderToString(
      <CacheProvider value={cache}>
        <App pageContext={pageContext}>
          <Page {...pageProps} />
        </App>
      </CacheProvider>,
  )

  const emotionChunks = extractCriticalToChunks(pageHtml);
  const styles = constructStyleTagsFromChunks(chunks)

  // the styles const will be a string as following: 
 //  <style>...css</style><style>...css</style>

  const documentHtml = escapeInject`<html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>My site</title>
      ${dangerouslySkipEscape(styles)} <-- NOTE here we are injecting the styles
    </head>
       <body>
        <div id="page-view">${dangerouslySkipEscape(pageHtml)}</div>
      </body>
    </html>`

  return {
    documentHtml,
    pageContext: {},
  }
}
```

Until here is super straightforward, except, it doesn't work. 

When I try to load the page, I get

```
Error: Failed to resolve entry for package "D:/Code/portals/web-ui". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "D:/Code/portals/web-ui". The package may have incorrect main/module/exports s
pecified in its package.json.
    at packageEntryFailure (D:\Code\portals\web-ui\node_modules\vite\dist\node\chunks\dep-88bd5805.js:40672:11)
    at resolvePackageEntry (D:\Code\portals\web-ui\node_modules\vite\dist\node\chunks\dep-88bd5805.js:40668:9)
    at tryResolveFile (D:\Code\portals\web-ui\node_modules\vite\dist\node\chunks\dep-88bd5805.js:40384:38)
    at tryFsResolve (D:\Code\portals\web-ui\node_modules\vite\dist\node\chunks\dep-88bd5805.js:40366:16)
    at Context.resolveId (D:\Code\portals\web-ui\node_modules\vite\dist\node\chunks\dep-88bd5805.js:40254:56)
    at Object.resolveId (D:\Code\portals\web-ui\node_modules\vite\dist\node\chunks\dep-88bd5805.js:38848:55)
    at async ModuleGraph.resolveUrl (D:\Code\portals\web-ui\node_modules\vite\dist\node\chunks\dep-88bd5805.js:57411:26)
    at async ModuleGraph.ensureEntryFromUrl (D:\Code\portals\web-ui\node_modules\vite\dist\node\chunks\dep-88bd5805.js:57364:41)
    at async D:\Code\portals\web-ui\node_modules\vite\dist\node\chunks\dep-88bd5805.js:56244:21
    at async Promise.all (index 0)
```

After hours of debugging i can't find a way around.

This happens when I'm trying to insert any style tag in the head of the page. For instance, if i do this:

```ts
const documentHtml = escapeInject`<html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>My site</title>
      <style> .hardCodedStyle{} </style> <--- NOT WORKING
    </head>`
```

I get the same error.

There is something funky with transforming the html from the server., it seems it traverses all styles tags and converts them into a url to load, i suppose is done for development purpose, but how can i avoid it?

Do you have any tips to have this work?

**Comment by brillout** [comment]
Seems unrelated to vps.

Dig into Vite's stack trace. Report back your findings.

Closing in the meantime since it doesn't seem related to the plugin.
