### ISSUE TITLE
Url ending in %20 crash

### ISSUE THREAD

**Issue by steenhansen** [brillout/vite-plugin-ssr#322]
The offending url : http://localhost:3000/steenhansen1942/gmail.com/cakes%20

The error message : Cannot GET /steenhansen1942/gmail.com/cakes%20

`{"url":"/steenhansen1942/gmail.com/cakes ","pathnameWithBaseUrl":"/steenhansen1942/gmail.com/cakes","urlWithoutSearch":"/steenhansen1942/gmail.com/cakes ","origin":null}`.
    at parseUrl (C:\Users\16043\Desktop\_js\vite\zz\node_modules\vite-plugin-ssr\dist\cjs\utils\parseUrl.js:69:29)
    at handlePageContextRequestSuffix (C:\Users\16043\Desktop\_js\vite\zz\node_modules\vite-plugin-ssr\dist\cjs\utils\getFileUrl.js:42:46)
    at _parseUrl (C:\Users\16043\Desktop\_js\vite\zz\node_modules\vite-plugin-ssr\dist\cjs\node\renderPage.js:693:117)
    at initializePageContext (C:\Users\16043\Desktop\_js\vite\zz\node_modules\vite-plugin-ssr\dist\cjs\node\renderPage.js:114:50)
    at renderPage (C:\Users\16043\Desktop\_js\vite\zz\node_modules\vite-plugin-ssr\dist\cjs\node\renderPage.js:22:31)
    at renderPageWithoutThrowing (C:\Users\16043\Desktop\_js\vite\zz\node_modules\vite-plugin-ssr\dist\cjs\node\renderPage.js:131:33)
    at C:\Users\16043\Desktop\_js\vite\zz\server-app\index.js:110:36

When a space replaces %20 in the url the browser trims away the ending space

**Comment by brillout** [comment]
So you're getting a 404? Isn't that what you want?

**Comment by steenhansen** [comment]
I saw the "Error: [vite-plugin-ssr@0.3.64][Bug']" and thought it best to tell you. I have no problem, as I am the one producing the url. And thank you for the fast response and especially for the project, I do not miss WebPack. Close away sir

**Comment by brillout** [comment]
I'll fix this a little later, since it's not urgent :-). Thanks for reaching out. FYI the goal is to have the user never see a `[Bug]` message. (These are internal assertions that should never fail.)

So keep them coming :-).

**Comment by brillout** [comment]
This is fixed in vps 0.4.

If you need the fix for vps 0.3, let me know.
