### ISSUE TITLE
Stumbled on following error when generating SSR for Cloudflare worker with react spectrum

### ISSUE THREAD

**Issue by jalagari** [brillout/vite-plugin-ssr#337]
### Description

My react application uses react spectrum and after including spectrum css in vite configuration I am getting error in resolving scripts source.

### Error Stack

    at resolveScriptSrc (worker.js:2464:28)
    at getPageAssets (worker.js:2338:64)
    at async Object._getPageAssets (worker.js:3848:32)
    at async injectAssetsBeforeRender (worker.js:2412:28)
    at async injectAssets (worker.js:2397:22)
    at async renderHtml (worker.js:3091:26)
    at async executeRenderHook (worker.js:4064:28)
    at async renderPage2 (worker.js:3612:34)
    at async renderPageWithoutThrowing (worker.js:3651:18)
    at async handleSsr (worker.js:89724:25)
    at async handleFetchEvent (worker.js:89783:25)

**Comment by brillout** [comment]
See https://github.com/brillout/vite-plugin-ssr/commit/51e56619a878bce22f560330de5e80bcf6c047ce.

Since you posted on Discord as well, you must have read the `welcome` Rules. Respect the rules.

Dig, dig, dig. Only after you dig will we be ready to help.
