### ISSUE TITLE
Errors for `pageContext.urlParsed.[hashString|searchString]` even when not using them

### ISSUE THREAD

**Issue by AaronBeaudoin** [brillout/vite-plugin-ssr#377]
### Description

When building my project, I get the following errors:

```
Error: [vite-plugin-ssr@0.4.10][Warning] `pageContext.urlParsed.hashString` has been renamed to `pageContext.urlParsed.hashOriginal`
    at assertWarning (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/vite-plugin-ssr/dist/cjs/utils/assert.js:63:22)
    at Object.get hashString [as hashString] (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/vite-plugin-ssr/dist/cjs/shared/addComputedUrlProps.js:53:39)
    at JSON.stringify (<anonymous>)
    at serializer (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/@brillout/json-s/dist/cjs/stringify.js:13:38)
    at stringify (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/@brillout/json-s/dist/cjs/stringify.js:14:12)
    at serializePageContextClientSide (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/vite-plugin-ssr/dist/cjs/node/serializePageContextClientSide.js:27:59)
    at getPageContextTag (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/vite-plugin-ssr/dist/cjs/node/html/injectAssets.js:132:136)
    at htmlSnippet (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/vite-plugin-ssr/dist/cjs/node/html/injectAssets.js:77:32)
    at getHtmlSnippet (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/vite-plugin-ssr/dist/cjs/node/html/injectAssets/injectHtmlSnippet.js:60:46)
    at /Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/vite-plugin-ssr/dist/cjs/node/html/injectAssets/injectHtmlSnippet.js:48:25
Error: [vite-plugin-ssr@0.4.10][Warning] `pageContext.urlParsed.searchString` has been renamed to `pageContext.urlParsed.searchOriginal`
    at assertWarning (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/vite-plugin-ssr/dist/cjs/utils/assert.js:63:22)
    at Object.get searchString [as searchString] (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/vite-plugin-ssr/dist/cjs/shared/addComputedUrlProps.js:57:39)
    at JSON.stringify (<anonymous>)
    at serializer (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/@brillout/json-s/dist/cjs/stringify.js:13:38)
    at stringify (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/@brillout/json-s/dist/cjs/stringify.js:14:12)
    at serializePageContextClientSide (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/vite-plugin-ssr/dist/cjs/node/serializePageContextClientSide.js:27:59)
    at getPageContextTag (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/vite-plugin-ssr/dist/cjs/node/html/injectAssets.js:132:136)
    at htmlSnippet (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/vite-plugin-ssr/dist/cjs/node/html/injectAssets.js:77:32)
    at getHtmlSnippet (/Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/vite-plugin-ssr/dist/cjs/node/html/injectAssets/injectHtmlSnippet.js:60:46)
    at /Users/aryse/Projects/vite-plugin-ssr-example-base/node_modules/vite-plugin-ssr/dist/cjs/node/html/injectAssets/injectHtmlSnippet.js:48:25
```

I don't actually use those properties though. I am, however, passing `urlParsed` to the client via `passToClient`:

```js
export const passToClient = [
  "urlParsed",
  "pageProps"
];
```

Is it possible to hide these errors unless I actually try and use the properties in question? Otherwise these messages are clutter and "scare crows" in the terminal.

### Error Stack

N/A

**Comment by brillout** [comment]
I'll release the fix this weekend. I didn't test this; let me know shall the bug still occur.
