### ISSUE TITLE
Can't build with latest Vuetify and variable overrides

### ISSUE THREAD

**Issue by DenisLug** [brillout/vite-plugin-ssr#379]
### Description

I get the following error when I add the latest Vuetify (3.0.0-beta.5) to the vite-plugin-ssr vue example and try to build it:

```
'vue' is imported as an external by node_modules/vuetify/lib/components/VApp/VApp.mjs, but is already an existing non-external module id.
error during build:
Error: 'vue' is imported as an external by node_modules/vuetify/lib/components/VApp/VApp.mjs, but is already an existing non-external module id.
    at error (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.fetchResolvedDependency (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:22355:24)
    at /Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:22362:189
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:22362:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModuleDependencies (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:22339:9)
    at async ModuleLoader.fetchModule (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:22327:13)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:22362:34)
```

A difference to the [existing vite-plugin-ssr-vuetify example](https://github.com/brillout/vite-plugin-ssr-vuetify) is that I also want to override some Vuetify variables. The dev server doesn't throw any errors and works as expected.

You can find the project here: https://github.com/DenisLug/vite-plugin-ssr-vuetify

**Comment by brillout** [comment]
https://brillout.github.io/rules/

**Comment by DenisLug** [comment]
I have created an [issue in the vuetify repository](https://github.com/vuetifyjs/vuetify/issues/15510#issuecomment-1193978103) and got the answer that my imports were bad. 

With the updated repository I get this error which seems to be more related to the vite-plugin-ssr:
```
'useSSRContext' is not exported by vue, imported by pages/about/index.page.vue
file: /Users/myuser/Projekte/vite-plugin-ssr-vuetify/pages/about/index.page.vue:9:9
 7: import "/Users/myuser/Projekte/vite-plugin-ssr-vuetify/pages/about/index.page.vue?vue&type=style&index=0&lang.css"
 8: 
 9: import { useSSRContext as __vite_useSSRContext } from 'vue'
             ^
10: const _sfc_setup = _sfc_main.setup
11: _sfc_main.setup = (props, ctx) => {
error during build:
Error: 'useSSRContext' is not exported by vue, imported by pages/about/index.page.vue
    at error (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:12542:16)
    at Module.traceVariable (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:12901:29)
    at ModuleScope.findVariable (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:11553:39)
    at ReturnValueScope.findVariable (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:6486:38)
    at ChildScope.findVariable (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:6486:38)
    at Identifier.bind (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:7553:40)
    at CallExpression.bind (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:5383:23)
    at CallExpression.bind (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:9049:15)
    at VariableDeclarator.bind (/Users/myuser/Projekte/vite-plugin-ssr-vuetify/node_modules/rollup/dist/shared/rollup.js:5383:23)
```

**Comment by brillout** [comment]
I'm fairly confident it's not related to vps.

But feel free to object with a *minimal* reproduction starting off `npm init vite-plugin-ssr@latest`.

**Comment by DenisLug** [comment]
@brillout: I have created a new project here: https://github.com/DenisLug/vite-plugin-ssr-0.4-vuetify

The error when building is now another one:
```
'vue' is imported as an external by renderer/Link.vue, but is already an existing non-external module id.
[vite-plugin-ssr:autoFullBuild] 'vue' is imported as an external by renderer/Link.vue, but is already an existing non-external module id.
error during build:
Error: 'vue' is imported as an external by renderer/Link.vue, but is already an existing non-external module id.
    at error (/Users/myuser/Projekte/vite-plugin-ssr-vuetify-2/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.fetchResolvedDependency (/Users/myuser/Projekte/vite-plugin-ssr-vuetify-2/node_modules/rollup/dist/shared/rollup.js:22355:24)
    at /Users/myuser/Projekte/vite-plugin-ssr-vuetify-2/node_modules/rollup/dist/shared/rollup.js:22362:189
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (/Users/myuser/Projekte/vite-plugin-ssr-vuetify-2/node_modules/rollup/dist/shared/rollup.js:22362:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModuleDependencies (/Users/myuser/Projekte/vite-plugin-ssr-vuetify-2/node_modules/rollup/dist/shared/rollup.js:22339:9)
    at async ModuleLoader.fetchModule (/Users/myuser/Projekte/vite-plugin-ssr-vuetify-2/node_modules/rollup/dist/shared/rollup.js:22327:13)
    at async Promise.all (index 3)

```

**Comment by brillout** [comment]
I still don't think it's a vps problem.

For example, if you remove vuetify the error goes away, right? That's a strong signal that it's not related to vps. It could be a Vite/Rollup problem but since Vite/Rollup has become fairly stable, I'm leaning towards thinking it's a Vuetify problem.

Dig more into the error and you'll eventually find the root cause of this.
