### ISSUE TITLE
[0.4.12] Calling `prerender` programatically now crashes

### ISSUE THREAD

**Issue by magne4000** [brillout/vite-plugin-ssr#380]
### Description

On [vite-plugin-vercel vercel-api-v3-stable branch](https://github.com/magne4000/vite-plugin-vercel/tree/vercel-api-v3-stable) I upgraded to `vite-plugin-ssr@0.4.12`, and now calling `prerender` crashes. After investigation, it seems related to the [new `collectDoNoPrerenderList` that now checks `fileType` prop](https://github.com/brillout/vite-plugin-ssr/commit/409b6253ae494ab1f95c9172c30161a2696244d9#diff-d767748bbb67e42bf07c4ca8a091649fbe4dc804f2c3b4ef5f49572f4147f8d6R206). 

At this point `_pageFilesAll` should contain all `fileType`s right, not just `.page.route` ones? Or should I update my code in some way now?

### Error Stack

```
[vite-plugin-vercel] [vite-plugin-ssr@0.4.12][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust.
[vite-plugin-ssr:autoFullBuild] [vite-plugin-ssr@0.4.12][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust.
error during build:
Error: [vite-plugin-ssr@0.4.12][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust.
    at /home/magne/workspace/vite-plugin-vercel/node_modules/.pnpm/vite-plugin-ssr@0.4.12_vite@3.0.2/node_modules/vite-plugin-ssr/dist/cjs/node/prerender.js:100:32
    at Array.forEach (<anonymous>)
    at collectDoNoPrerenderList (/home/magne/workspace/vite-plugin-vercel/node_modules/.pnpm/vite-plugin-ssr@0.4.12_vite@3.0.2/node_modules/vite-plugin-ssr/dist/cjs/node/prerender.js:98:33)
    at prerender (/home/magne/workspace/vite-plugin-vercel/node_modules/.pnpm/vite-plugin-ssr@0.4.12_vite@3.0.2/node_modules/vite-plugin-ssr/dist/cjs/node/prerender.js:81:5)
    at async prerender (file:///home/magne/workspace/vite-plugin-vercel/packages/vite-plugin-ssr/dist/vite-plugin-ssr.js:204:3)
    at async Object.writeBundle (file:///home/magne/workspace/vite-plugin-vercel/packages/vercel/dist/index.js:376:25)
    at async Promise.all (index 1)
    at async file:///home/magne/workspace/vite-plugin-vercel/node_modules/.pnpm/rollup@2.77.0/node_modules/rollup/dist/es/shared/rollup.js:23717:13
    at async catchUnfinishedHookActions (file:///home/magne/workspace/vite-plugin-vercel/node_modules/.pnpm/rollup@2.77.0/node_modules/rollup/dist/es/shared/rollup.js:23040:20)
    at async doBuild (file:///home/magne/workspace/vite-plugin-vercel/node_modules/.pnpm/vite@3.0.2/node_modules/vite/dist/node/chunks/dep-1513d487.js:43473:20)
    at async Module.build (file:///home/magne/workspace/vite-plugin-vercel/node_modules/.pnpm/vite@3.0.2/node_modules/vite/dist/node/chunks/dep-1513d487.js:43297:16)
    at async Object.writeBundle (/home/magne/workspace/vite-plugin-vercel/node_modules/.pnpm/vite-plugin-ssr@0.4.12_vite@3.0.2/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/autoFullBuild.js:33:17)
    at async Promise.all (index 0)
    at async file:///home/magne/workspace/vite-plugin-vercel/node_modules/.pnpm/rollup@2.77.0/node_modules/rollup/dist/es/shared/rollup.js:23717:13
    at async catchUnfinishedHookActions (file:///home/magne/workspace/vite-plugin-vercel/node_modules/.pnpm/rollup@2.77.0/node_modules/rollup/dist/es/shared/rollup.js:23040:20)
    at async doBuild (file:///home/magne/workspace/vite-plugin-vercel/node_modules/.pnpm/vite@3.0.2/node_modules/vite/dist/node/chunks/dep-1513d487.js:43473:20)
    at async build (file:///home/magne/workspace/vite-plugin-vercel/node_modules/.pnpm/vite@3.0.2/node_modules/vite/dist/node/chunks/dep-1513d487.js:43297:16)
    at async CAC.<anonymous> (file:///home/magne/workspace/vite-plugin-vercel/node_modules/.pnpm/vite@3.0.2/node_modules/vite/dist/node/cli.js:747:9)
```

If you need to reproduce the error, you can checkout the `vercel-api-v3-stable` branch of `vite-plugin-vercel` and run `pnpm -w run build:all`.

**Comment by brillout** [comment]
See https://github.com/brillout/vite-plugin-ssr/commit/4084c5aad2925a994cf4eeae0441dfa33a163fb2 and https://github.com/magne4000/vite-plugin-vercel/pull/6/files.

**Comment by brillout** [comment]
FYI, I'm actually going to revert the changes that lead to this problem (because of https://github.com/brillout/vite-plugin-ssr/issues/382 and https://github.com/brillout/vite-plugin-ssr/issues/381).

**Comment by brillout** [comment]
In the meantime, my PR should fix the situation.
