### ISSUE TITLE
Can't start vite dev-server for Cypress Component testing

### ISSUE THREAD

**Issue by alyaothman14** [brillout/vite-plugin-ssr#386]
### Description

Adding component test for Cypress and running cypress vite-ssr throws an error
module.exports = defineConfig({
  chromeWebSecurity: false,
  component: {
    devServer: {
      bundler: 'vite',
      framework: 'react',
    },
   
  },

### Error Stack

Error: [vite-plugin-ssr@0.4.13][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust. 
    at Object.configResolved (/.../node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/devConfig.js:33:36)
    at file:///.../node_modules/vite/dist/node/chunks/dep-c6273c7a.js:62630:39
    at Array.map ()
    at resolveConfig (file:///.../node_modules/vite/dist/node/chunks/dep-c6273c7a.js:62630:10)
    at async Module.createServer (file:///.../node_modules/vite/dist/node/chunks/dep-c6273c7a.js:59000:20)
    at async AsyncFunction.createDevServer [as create] (/Users/alya/Library/Caches/Cypress/10.3.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/vite-dev-server/dist/devServer.js:34:16)
    at async devServer (/Users/alya/Library/Caches/Cypress/10.3.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/vite-dev-server/dist/devServer.js:14:20)
From previous event:
    at Object.wrapChildPromise (/Users/alya/Library/Caches/Cypress/10.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:58:23)
    at Object.wrap (/Users/alya/Library/Caches/Cypress/10.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/dev-server.js:18:8)
    at RunPlugins.execute (/Users/alya/Library/Caches/Cypress/10.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:150:26)
    at EventEmitter. (/Users/alya/Library/Caches/Cypress/10.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:257:12)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at process. (/Users/alya/Library/Caches/Cypress/10.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:527:28)
    at process.emit (node:domain:475:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/alya/Library/Caches/Cypress/10.3.1/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:613:40)
    at emit (node:internal/child_process:936:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by brillout** [comment]
Thanks for opening the ticket. I'll have a look at it.

**Comment by brillout** [comment]
It seems like some Vite plugin is setting [`optimizeDeps.entries`](https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-entries)?

If you remove the assertion at `node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/devConfig.js:33`, does it work then?

**Comment by alyaothman14** [comment]
Yes that works now and does not throw the error
