### ISSUE TITLE
Build process breaks when base is set to "" or "./"

### ISSUE THREAD

**Issue by piyook** [brillout/vite-plugin-ssr#394]
### Description

Setting the base in vite.config.js to "" or "./" breaks the pre-render build process in both Vue and React. 

import react from '@vitejs/plugin-react'
import ssr from 'vite-plugin-ssr/plugin'
import {defineConfig} from 'vite';

export default defineConfig({
  plugins: [react(), ssr({ prerender: true })],
  base: "./",
});

### Error Stack

```shell
[vite-plugin-ssr:pluginManifest] [vite-plugin-ssr@0.4.13][Bug] You stumbled upon a 
bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new 
or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust.
error during build:
Error: [vite-plugin-ssr@0.4.13][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust.
    at assertPluginManifest (E:\LEIGH_STORE\PROJECTS\2-PROJECTS\2-VUE\16-PRERENDER\react-vite-ssr-project\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\manifest\assertPluginManifest.js:8:24)
    at Object.generateBundle (E:\LEIGH_STORE\PROJECTS\2-PROJECTS\2-VUE\16-PRERENDER\react-vite-ssr-project\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\manifest.js:32:65)
    at E:\LEIGH_STORE\PROJECTS\2-PROJECTS\2-VUE\16-PRERENDER\react-vite-ssr-project\node_modules\rollup\dist\shared\rollup.js:22826:37
```

**Comment by brillout** [comment]
👍. The error message should be improved.

Only Base URLs starting with `/` and `https://` are supported.
