### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by erktime** [brillout/vite-plugin-ssr#405]
### Description

In upgrading to the latest version of vite-plugin-ssr (0.4.17)  and the most recent version of vite (3.0.4), I've been fighting issues loading modules in my project.

In previous builds (2.3.3), I was able to import the following [vue3-daterange-picker](https://www.npmjs.com/package/vue3-daterange-picker) dependency into my vue project without fail. But now I'm getting errors about "Cannot use import statement outside a module". I realize this dependency isn't built as an ESM module and is just raw vue, code, but it used to work. 

Additionally I've seen issues with other dependencies that do offer native ESM versions. For example with the [chart.js](https://www.chartjs.org/) library, the following use to work:

```js
import {  BarController } from 'chart.js';
```

And i've had to alter it to the following to work for both dev mode and production where we run as a node.js app via express:

```js
import {  BarController } from 'chart.js/dist/chart.mjs';
```

Any ideas? It feels like there are issues running my app, which is ESM, but the VPS code when running on the server is CJS. Thanks.

### Error Stack

```shell
/Users/erk/Documents/gitCode/mywt-parrot/ui/node_modules/vue3-daterange-picker/src/index.js:1
"import DateRangePicker from './components/DateRangePicker.vue'

SyntaxError: Cannot use import statement outside a module     
     at Object.compileFunction (node:vm:352:18) 
     at wrapSafe (node:internal/modules/cjs/loader:1032:15)     
     at Module._compile (node:internal/modules/cjs/loader:1067:27)     
     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)     
     at Module.load (node:internal/modules/cjs/loader:981:32)     
     at Function.Module._load (node:internal/modules/cjs/loader:822:12)     
     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)     
     at ModuleJob.run (node:internal/modules/esm/module_job:197:25)     
     at async Promise.all (index 0)     
     at async ESMLoader.import (node:internal/modules/esm/loader:337:24)     
     at async nodeImport (file:///Users/erk/Documents/gitCode/mywt-parrot/ui/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:50457:21)     
     at async eval (/admin/pages/site/edit-site.page.vue:30:32)     
     at async instantiateModule (file:///Users/erk/Documents/gitCode/mywt-parrot/ui/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:50386:9
```

**Comment by brillout** [comment]
Unrelated to vps, see https://brillout.github.io/rules/.

That said:
 - That's likley because Vite is now outputting ESM code.
 - First upgrade Vite, then vps. You'll have a much easier time doing it one step at a time.

I didn't read the whole ticket; let me know if you do believe something to be related to vps.
