### ISSUE TITLE
How can i run with mode

### ISSUE THREAD

**Issue by boh001** [brillout/vite-plugin-ssr#424]
### Question / Discussion

I want to use it like this `vite --mode qa`.  It works when remove `vite-plugin-ssr` or `--mode`.  Furthermore when i build with `--mode` and preview, `import.meta.env.mode` comes out properly in client side but it is  always `production` in server side.

What could be wrong?

**Comment by brillout** [comment]
See https://github.com/brillout/vite-plugin-ssr/issues/169#issuecomment-1199321785.

Keep me updated if that helps resolving your problem.

**Comment by boh001** [comment]
> See [#169 (comment)](https://github.com/brillout/vite-plugin-ssr/issues/169#issuecomment-1199321785).
> 
> Keep me updated if that helps resolving your problem.

i tried example/custom-server-render-integration for using vanila nodejs and it works when `vite build --mode qa` and run in production. but still not works in development. i get error when i write mode manually in inlineConfig of `vite.createServer`  

`vite.createServer({
      root,
      server: { middlewareMode: 'ssr' },
      mode: "qa"
    })`
    
Error: [vite-plugin-ssr@0.4.14][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust.

**Comment by brillout** [comment]
I'll need a reproduction for the `vite build --mode qa` problem (I don't understand what you are writing).

> Error: [vite-plugin-ssr@0.4.14][Bug] You stumbled upon a bug in vite-plugin-ssr's source code

Update to the latest version and paste the full stack trace here.

**Comment by boh001** [comment]
> I'll need a reproduction for the `vite build --mode qa` problem (I don't understand what you are writing).
> 
> > Error: [vite-plugin-ssr@0.4.14][Bug] You stumbled upon a bug in vite-plugin-ssr's source code
> 
> Update to the latest version and paste the full stack trace here.

same code as example except for adding 'mode' in inlineConfig
```js
viteDevServer = await vite.createServer({
  root,
  server: { middlewareMode: 'ssr' },
  mode: "qa",
})
```

```
kimsang@kimsangui-MacBookAir custom-server-render-integration % yarn dev
yarn run v1.22.19
warning package.json: No license field
$ npm run server

> server
> node ./server

Server running at http://localhost:3000
Error: [vite-plugin-ssr@0.4.14][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust. 
    at getRuntimeConfig (/Users/kimsang/code/vite-plugin-ssr/examples/custom-server-render-integration/node_modules/vite-plugin-ssr/dist/cjs/node/globalContext/runtimeConfig.js:16:24)
    at getGlobalContext (/Users/kimsang/code/vite-plugin-ssr/examples/custom-server-render-integration/node_modules/vite-plugin-ssr/dist/cjs/node/globalContext.js:46:64)
    at initializePageContext (/Users/kimsang/code/vite-plugin-ssr/examples/custom-server-render-integration/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:115:70)
    at renderPage_ (/Users/kimsang/code/vite-plugin-ssr/examples/custom-server-render-integration/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:30:47)
    at renderPage (/Users/kimsang/code/vite-plugin-ssr/examples/custom-server-render-integration/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:145:22)
    at /Users/kimsang/code/vite-plugin-ssr/examples/custom-server-render-integration/server/index.js:32:31
    at Layer.handle [as handle_request] (/Users/kimsang/code/vite-plugin-ssr/examples/custom-server-render-integration/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kimsang/code/vite-plugin-ssr/examples/custom-server-render-integration/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/kimsang/code/vite-plugin-ssr/examples/custom-server-render-integration/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/kimsang/code/vite-plugin-ssr/examples/custom-server-render-integration/node_modules/express/lib/router/layer.js:95:5)
    at /Users/kimsang/code/vite-plugin-ssr/examples/custom-server-render-integration/node_modules/express/lib/router/index.js:284:15
    at param (/Users/kimsang/code/vite-plugin-ssr/examples/custom-server-render-integration/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/kimsang/code/vite-plugin-ssr/examples/custom-server-render-integration/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/Users/kimsang/code/vite-plugin-ssr/examples/custom-server-render-integration/node_modules/express/lib/router/index.js:421:3)
    at Immediate.next [as _onImmediate] (/Users/kimsang/code/vite-plugin-ssr/examples/custom-server-render-integration/node_modules/express/lib/router/index.js:280:10)
```

**Comment by brillout** [comment]
`viteDevServer` is only used in development, that's why your inline config is not picked up in production.

As for the internal bug, please update to the latest version. As I told you.

> **Update to the latest version** and paste the full stack trace here

Please dig more before reaching out for help, see https://brillout.github.io/rules/.

**Comment by brillout** [comment]
Ok I see the problem now. Yes, indeed, `disableAutoFullBuild` is needed for the CLI argument `--mode` to be picked up. It shouldn't be needed though. Opening https://github.com/brillout/vite-plugin-ssr/issues/444.
