### ISSUE TITLE
Can't use default export for pages

### ISSUE THREAD

**Issue by kidonng** [brillout/vite-plugin-ssr#439]
### Description

[The docs](https://vite-plugin-ssr.com/Page) say `export default` can also be used, but in fact it doesn't support it and throw an error instead.

### Error Stack

```shell
Server running at http://localhost:3000
Error: [vite-plugin-ssr@0.4.30][Wrong Usage] The `export default` of /pages/index/index.page.tsx should be an object.
    at /workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/getExports.js:59:41
    at Array.forEach (<anonymous>)
    at getExportValues (/workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/getExports.js:51:10)
    at /workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/getExports.js:9:30
    at Array.forEach (<anonymous>)
    at getExports (/workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/getExports.js:8:15)
    at loadPageFilesServerSide (/workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/analyzePageServerSide/loadPageFilesServerSide.js:9:78)
    at async Promise.all (index 0)
    at async loadPageFilesServer (/workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:364:69)
    at async renderPageContext (/workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:65:23)
    at async renderPage (/workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:151:16)
    at async /workspaces/.github/vite-ssr-project/server/index.ts:33:25
Error: [vite-plugin-ssr@0.4.30][Wrong Usage] The `export default` of /pages/index/index.page.tsx should be an object.
    at /workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/getExports.js:59:41
    at Array.forEach (<anonymous>)
    at getExportValues (/workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/getExports.js:51:10)
    at /workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/getExports.js:9:30
    at Array.forEach (<anonymous>)
    at getExports (/workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/getExports.js:8:15)
    at loadPageFilesServerSide (/workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/analyzePageServerSide/loadPageFilesServerSide.js:9:78)
    at async Promise.all (index 0)
    at async loadPageFilesServer (/workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:364:69)
    at async renderPageContext (/workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:65:23)
    at async renderPage (/workspaces/.github/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:151:16)
    at async /workspaces/.github/vite-ssr-project/server/index.ts:33:25
```

**Comment by brillout** [comment]
Docs updated. Thanks.
