### ISSUE TITLE
solid spa error when navigate is called

### ISSUE THREAD

**Issue by JonnyRodriguez** [brillout/vite-plugin-ssr#441]
`###` Description

i cloned th solid-spa example, y added a simple new page and from the index page example i imported the navigate function
and simple try to navigate to the other page

pages/index/index.page.client.jsx
```
import { navigate } from "vite-plugin-ssr/client/router";
import { Counter } from './Counter'

export function Page() {
  navigate('/one');
  return (
    <>
      <h1>About</h1>
      <p>Solid JS SPA</p>
      <Counter></Counter>
      <button onClick={() => navigate('/one')}>One</button>
    </>
  )
}
```

pages/one/index.page.client.jsx
```
export function Page() {
    return (
        <>
            <h1>Page One</h1>
        </>
    );
}
```

in both calls the same error

### Error Stack

```shell
Uncaught (in promise) Error: [vite-plugin-ssr@0.4.31][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust. 
    at navigate (useClientRouter.js?v=642eb382:170:5)
    at Page (index.page.client.tsx:6:3)
    at @solid-refresh:10:42
    at untrack (dev.js:425:12)
    at Object.fn (@solid-refresh:10:28)
    at runComputation (dev.js:694:22)
    at updateComputation (dev.js:679:3)
    at createMemo (dev.js:238:10)
    at hmrCompWrapper (@solid-refresh:7:20)
    at dev.js:519:12
    at untrack (dev.js:425:12)
    at Object.fn (dev.js:515:37)
    at runComputation (dev.js:694:22)
    at updateComputation (dev.js:679:3)
    at devComponent (dev.js:525:3)
    at createComponent (dev.js:1227:10)
    at _default.page.client.tsx:23:37
    at dev.js:99:53
    at updateFn (dev.js:168:15)
    at runUpdates (dev.js:786:17)
    at createRoot (dev.js:176:12)
    at render (dev.js:97:3)
    at Object.render (_default.page.client.tsx:23:25)
    at hydrate (entry.js:12:31)


createErrorWithCleanStackTrace | @ | createErrorWithClean…ace.js?v=642eb382:7
-- | -- | --
  | assert | @ | assert.js?v=642eb382:25
  | navigate | @ | useClientRouter.js?v=642eb382:170
  | Page | @ | index.page.client.tsx:6
  | (anonymous) | @ | @solid-refresh:10
  | untrack | @ | dev.js:425
  | (anonymous) | @ | @solid-refresh:10
  | runComputation | @ | dev.js:694
  | updateComputation | @ | dev.js:679
  | createMemo | @ | dev.js:238
  | hmrCompWrapper | @ | @solid-refresh:7
  | (anonymous) | @ | dev.js:519
  | untrack | @ | dev.js:425
  | (anonymous) | @ | dev.js:515
  | runComputation | @ | dev.js:694
  | updateComputation | @ | dev.js:679
  | devComponent | @ | dev.js:525
  | createComponent | @ | dev.js:1227
  | (anonymous) | @ | _default.page.client.tsx:23
  | (anonymous) | @ | dev.js:99
  | updateFn | @ | dev.js:168
  | runUpdates | @ | dev.js:786
  | createRoot | @ | dev.js:176
  | render | @ | dev.js:97
  | render | @ | _default.page.client.tsx:23
  | hydrate | @ | entry.js:12
  | await in hydrate (async) |   |  
  | (anonymous) | @ | entry.js:7


```

**Comment by brillout** [comment]
`navigate()` is only meant to be used with Client Routing, see https://vite-plugin-ssr.com/navigate.

Let me fix that error message though.

**Comment by JonnyRodriguez** [comment]
thanks, i added 'export const clientRouting = true' to 'renderer/_default.page.client.tsx' and is working as expected now
