### ISSUE TITLE
Stumbled upon bug after upgrading to 0.4.34

### ISSUE THREAD

**Issue by Pautomagi** [brillout/vite-plugin-ssr#455]
### Description

**Stack trace / error from cli**
```
Error: [vite-plugin-ssr@0.4.34][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust. Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): /src/renderer/_default.page.client.ts.
    at Object.pageFile.loadExportNames (/Users/username/Code/application-name/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/parseGlobResults.js:39:36)
    at async /Users/username/Code/application-name/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/analyzePageClientSide.js:40:9
    at async Promise.all (index 1)
    at async analyzePageClientSideInit (/Users/username/Code/application-name/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/analyzePageClientSide.js:30:5)
    at async Promise.all (index 1)
    at async loadPageFilesServer (/Users/username/Code/application-name/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:365:69)
    at async renderPageContext (/Users/username/Code/application-name/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:66:23)
    at async renderPage (/Users/username/Code/application-name/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:152:16)
    at async /Users/username/Code/application-name/server/index.js:32:29
```

**server/index.js**

```javascript
const express = require('express')
require('dotenv').config()
const compression = require('compression')
const { renderPage } = require('vite-plugin-ssr')

const isProduction = process.env.NODE_ENV === 'production'
const root = `${__dirname}/..`

startServer()

async function startServer() {
    const app = express()

    app.use(compression())

    let viteDevServer
    if (isProduction) {
        app.use(express.static(`${root}/dist/client`))
    } else {
        const vite = require('vite')
        viteDevServer = await vite.createServer({
            root,
            server: { middlewareMode: 'ssr' },
        })
        app.use(viteDevServer.middlewares)
    }

    app.get('*', async (req, res, next) => {
        const pageContextInit = { urlOriginal: req.originalUrl }
        const pageContext = await renderPage(pageContextInit)

        const { httpResponse, redirectTo, redirectCode } = pageContext

        if (redirectTo && redirectCode) {
            res.redirect(pageContext.redirectCode, pageContext.redirectTo);
            return next();
        }

        if (!httpResponse) return next()
        const { body, statusCode, contentType } = httpResponse
        res.status(statusCode).type(contentType).send(body)
    })

    const port = process.env.PORT || 3000
    app.listen(port)
    console.log(`Server running at http://localhost:${port}`)
}
```

**_default.page.client.ts**
```typescript
import { createApp } from '@/app'
import type { PageContext } from '@/entities/PageContext';
import type { PageContextBuiltIn } from 'vite-plugin-ssr';
import Bugsnag from '@bugsnag/js';
import BugsnagPluginVue from '@bugsnag/plugin-vue';
import { DatadogClient } from '@/services/DatadogClient.service';

export { render }

async function render(pageContext: PageContext & PageContextBuiltIn) {
    const {app, store} = createApp(pageContext)
    const datadog = new DatadogClient(pageContext);
    datadog.init(import.meta.env.VITE_DATADOG_CLIENT_TOKEN);

    Bugsnag.start({
        apiKey: import.meta.env.VITE_BUGSNAG_CLIENT_KEY as string,
        plugins: [new BugsnagPluginVue()]
    })
    const bugsnagVue = Bugsnag.getPlugin('vue')

    store.state.value = pageContext.initialStoreState

    app.use(bugsnagVue)
    app.mount('#app')
}
```

**Comment by brillout** [comment]
I'll need a reproduction for this one. Ideally a minimal one.
