### ISSUE TITLE
callHookWithTimeout error and warning timeouts swapped

### ISSUE THREAD

**Issue by vedranmviu** [brillout/vite-plugin-ssr#468]
### Description

We have this error originating from vite-plugin-ssr.
```
Error: [vite-plugin-ssr@0.4.39][Hook Timeout] The onBeforeRender() hook of /pages/all.page.server.js didn't finish after 4 seconds
    at Timeout._onTimeout (/Users/vedranmilic/Documents/projects/viu-web-site/node_modules/vite-plugin-ssr/dist/cjs/utils/callHookWithTimeout.js:29:50)
```
I've traced the issue to the file: https://github.com/brillout/vite-plugin-ssr/commit/1f5be92b09a33d290908da0d24913ca556370036#diff-c010b7cf4d0f9933efab99f66a4989d89f1604c491cdcf0107c108cbdbd2e941
It looks like the warning and error timeout logic is replaced.
In the lines between 28 and 39
```
const t1 = setTimeout(() => {
    const msg = `${errorPrefix}[Slow Hook] The ${hookName}() hook of ${hookFilePath} is taking more than ${humanizeTime(
      timeoutErr
    )}`
    console.warn(msg)
  }, timeoutErr)
  const t2 = setTimeout(() => {
    const err = getProjectError(
      `[Hook Timeout] The ${hookName}() hook of ${hookFilePath} didn't finish after ${humanizeTime(timeoutWarn)}`
    )
    reject(err)
  }, timeoutWarn)
  ```
  `timeoutErr` is in the place of the `timeoutWarn` and vice versa.
  

### Error Stack

```shell
Error: [vite-plugin-ssr@0.4.39][Hook Timeout] The onBeforeRender() hook of /pages/all.page.server.js didn't finish after 4 seconds
    at Timeout._onTimeout (/Users/vedranmilic/Documents/projects/viu-web-site/node_modules/vite-plugin-ssr/dist/cjs/utils/callHookWithTimeout.js:29:50)
```

**Comment by vedranmviu** [comment]
Tried to fix it and it was already fixed as I was editing the file.

**Comment by brillout** [comment]
Btw, in case your company is interested: https://github.com/sponsors/brillout
