### ISSUE TITLE
yarn build command fails with styled components in ssg mode

### ISSUE THREAD

**Issue by Kadchenko** [brillout/vite-plugin-ssr#472]
### Description

When running `yarn build`

**with babel-plugin-styled-components** it fails with error:
`[vite-plugin-ssr:autoFullBuild] Cannot read properties of undefined (reading 'withConfig')
[vite-plugin-ssr:autoFullBuild] Cannot read properties of undefined (reading 'withConfig') (x2)
error during build:
TypeError: Cannot read properties of undefined (reading 'withConfig')
`

**without babel-plugin-styled-components** it fails with error:
`[vite-plugin-ssr:autoFullBuild] styled.div is not a function
[vite-plugin-ssr:autoFullBuild] styled.div is not a function (x2)
error during build:
TypeError: styled.div is not a function
`

### vite.config.ts
<img width="677" alt="Снимок экрана 2022-10-12 в 17 20 55" src="https://user-images.githubusercontent.com/23073216/195368466-2d86add8-2242-41ff-bd8c-c972b6021805.png">

### /renderer/_default.server.page.tsx
<img width="671" alt="Снимок экрана 2022-10-12 в 17 24 25" src="https://user-images.githubusercontent.com/23073216/195369364-da31792f-83db-4a47-b99d-7af444413c1b.png">

**Comment by brillout** [comment]
It doesn't seem related to vite-plugin-ssr.

I will get rid of the confusing `[vite-plugin-ssr:autoFullBuild]` prefix.

**Comment by okomarov** [comment]
@brillout We've recreated a MWE at: https://replit.com/@DmitriiKadchien/React-styled-components-SSG (@Kadchenko is that public?)

Here's a .gif of what happens, any help would be appreciated (we've really exhausted any resources on the web...):
![styled_components_ssg](https://user-images.githubusercontent.com/3731173/195726742-9e2aeca7-0399-4fd8-9bb7-17be1b4feb13.gif)

<details>
  <summary> Output of <code>yarn vite build -d</code> </summary>
  
 ```
 ~/React-styled-components-SSG$ yarn vite build -d
yarn run v1.22.17
$ /home/runner/React-styled-components-SSG/node_modules/.bin/vite build -d
  vite:config bundled config file loaded in 968.38ms +0ms
  vite:esbuild init tsconfck (root: /home/runner/React-styled-components-SSG) +0ms
  vite:esbuild init tsconfck (root: /home/runner/React-styled-components-SSG) +17ms
  vite:esbuild init tsconfck (root: /home/runner/React-styled-components-SSG) +1ms
  vite:esbuild init tsconfck (root: /home/runner/React-styled-components-SSG) +1ms
  vite:esbuild init tsconfck end +71ms
  vite:esbuild init tsconfck end +1ms
  vite:esbuild init tsconfck end +0ms
  vite:esbuild init tsconfck end +1ms
  vite:config using resolved config: {
  vite:config   server: {
  vite:config     preTransformRequests: true,
  vite:config     host: '0.0.0.0',
  vite:config     middlewareMode: false,
  vite:config     fs: { strict: true, allow: [Array], deny: [Array] },
  vite:config     port: 3000
  vite:config   },
  vite:config   build: {
  vite:config     target: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari13' ],
  vite:config     polyfillModulePreload: true,
  vite:config     outDir: 'dist/client',
  vite:config     assetsDir: 'assets',
  vite:config     assetsInlineLimit: 4096,
  vite:config     cssCodeSplit: false,
  vite:config     cssTarget: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari13' ],
  vite:config     sourcemap: false,
  vite:config     rollupOptions: {
  vite:config       output: [Object],
  vite:config       onwarn: [Function (anonymous)],
  vite:config       input: [Object]
  vite:config     },
  vite:config     minify: 'esbuild',
  vite:config     terserOptions: {},
  vite:config     write: true,
  vite:config     emptyOutDir: null,
  vite:config     manifest: true,
  vite:config     lib: {
  vite:config       entry: '/home/runner/React-styled-components-SSG/pages/index.page.tsx',
  vite:config       name: 'StyledComponentsSSG'
  vite:config     },
  vite:config     ssr: false,
  vite:config     ssrManifest: false,
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit: 500,
  vite:config     watch: null,
  vite:config     polyfillDynamicImport: false,
  vite:config     commonjsOptions: { include: [Array], extensions: [Array] },
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] }
  vite:config   },
  vite:config   plugins: [
  vite:config     'vite:build-metadata',
  vite:config     'vite:pre-alias',
  vite:config     'alias',
  vite:config     'vite:react-babel',
  vite:config     'vite:react-refresh',
  vite:config     'vite:react-jsx',
  vite:config     'vite-plugin-ssr:setVitePluginSsrConfig',
  vite:config     'vite-plugin-ssr:extractAssets-2',
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:resolve',
  vite:config     'vite:html-inline-proxy',
  vite:config     'vite:css',
  vite:config     'vite:esbuild',
  vite:config     'vite:json',
  vite:config     'vite:wasm-helper',
  vite:config     'vite:worker',
  vite:config     'vite:asset',
  vite:config     'vite-plugin-ssr:commonConfig',
  vite:config     'vite-plugin-ssr:virtualModulePageFiles',
  vite:config     'vite-plugin-ssr:buildConfig',
  vite:config     'vite-plugin-ssr:autoFullBuild',
  vite:config     'vite-plugin-ssr:pluginManifest',
  vite:config     'vite-plugin-ssr:packageJsonFile',
  vite:config     'vite-plugin-ssr:removeRequireHookPlugin',
  vite:config     'vite-plugin-ssr:extractAssets-3',
  vite:config     'vite-plugin-ssr:retrieveDevServer',
  vite:config     'vite:wasm-fallback',
  vite:config     'vite:define',
  vite:config     'vite:css-post',
  vite:config     'vite:build-html',
  vite:config     'vite:worker-import-meta-url',
  vite:config     'vite:force-systemjs-wrap-complete',
  vite:config     'vite:watch-package-data',
  vite:config     'commonjs',
  vite:config     'vite:data-uri',
  vite:config     'vite:asset-import-meta-url',
  vite:config     'vite:dynamic-import-vars',
  vite:config     'vite:import-glob',
  vite:config     'vite-plugin-ssr:distFileNames',
  vite:config     'vite-plugin-ssr:extractAssets-1',
  vite:config     'vite-plugin-ssr:extractExportNames',
  vite:config     'vite-plugin-ssr:suppressRollupWarning',
  vite:config     'vite-plugin-ssr:importBuild:config',
  vite:config     'vite:build-import-analysis',
  vite:config     'vite:esbuild-transpile',
  vite:config     'vite:terser',
  vite:config     'vite:manifest',
  vite:config     'vite:reporter',
  vite:config     'vite:load-fallback'
  vite:config   ],
  vite:config   optimizeDeps: {
  vite:config     disabled: 'build',
  vite:config     force: undefined,
  vite:config     include: [ 'react/jsx-runtime', 'react/jsx-dev-runtime', 'react' ],
  vite:config     esbuildOptions: { preserveSymlinks: undefined }
  vite:config   },
  vite:config   resolve: { dedupe: [ 'react', 'react-dom' ], alias: [ [Object], [Object] ] },
  vite:config   vitePluginSsr: {
  vite:config     disableAutoFullBuild: false,
  vite:config     pageFiles: { include: [] },
  vite:config     prerender: {
  vite:config       partial: false,
  vite:config       noExtraDir: false,
  vite:config       parallel: true,
  vite:config       disableAutoRun: false
  vite:config     },
  vite:config     includeCSS: [],
  vite:config     includeAssetsImportedByServer: false
  vite:config   },
  vite:config   appType: 'custom',
  vite:config   experimental: { importGlobRestoreExtension: true, hmrPartialAccept: false },
  vite:config   ssr: {
  vite:config     format: 'esm',
  vite:config     target: 'node',
  vite:config     external: [ 'vite-plugin-ssr' ],
  vite:config     optimizeDeps: { disabled: true, esbuildOptions: [Object] }
  vite:config   },
  vite:config   configFile: '/home/runner/React-styled-components-SSG/vite.config.ts',
  vite:config   configFileDependencies: [ '/home/runner/React-styled-components-SSG/vite.config.ts' ],
  vite:config   inlineConfig: {
  vite:config     root: undefined,
  vite:config     base: undefined,
  vite:config     mode: undefined,
  vite:config     configFile: undefined,
  vite:config     logLevel: undefined,
  vite:config     clearScreen: undefined,
  vite:config     optimizeDeps: { force: undefined },
  vite:config     build: {}
  vite:config   },
  vite:config   root: '/home/runner/React-styled-components-SSG',
  vite:config   base: '/',
  vite:config   publicDir: '/home/runner/React-styled-components-SSG/public',
  vite:config   cacheDir: '/home/runner/React-styled-components-SSG/node_modules/.vite',
  vite:config   command: 'build',
  vite:config   mode: 'production',
  vite:config   isWorker: false,
  vite:config   mainConfig: null,
  vite:config   isProduction: true,
  vite:config   preview: {
  vite:config     port: 3000,
  vite:config     strictPort: undefined,
  vite:config     host: '0.0.0.0',
  vite:config     https: undefined,
  vite:config     open: undefined,
  vite:config     proxy: undefined,
  vite:config     cors: undefined,
  vite:config     headers: undefined
  vite:config   },
  vite:config   env: { BASE_URL: '/', MODE: 'production', DEV: false, PROD: true },
  vite:config   assetsInclude: [Function: assetsInclude],
  vite:config   logger: {
  vite:config     hasWarned: false,
  vite:config     info: [Function: info],
  vite:config     warn: [Function: warn],
  vite:config     warnOnce: [Function: warnOnce],
  vite:config     error: [Function: error],
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(0) { set: [Function (anonymous)] },
  vite:config   createResolver: [Function: createResolver],
  vite:config   worker: {
  vite:config     format: 'iife',
  vite:config     plugins: [
  vite:config       'vite:build-metadata',
  vite:config       'vite:pre-alias',
  vite:config       'alias',
  vite:config       'vite:modulepreload-polyfill',
  vite:config       'vite:resolve',
  vite:config       'vite:html-inline-proxy',
  vite:config       'vite:css',
  vite:config       'vite:esbuild',
  vite:config       'vite:json',
  vite:config       'vite:wasm-helper',
  vite:config       'vite:worker',
  vite:config       'vite:asset',
  vite:config       'vite:wasm-fallback',
  vite:config       'vite:define',
  vite:config       'vite:css-post',
  vite:config       'vite:build-html',
  vite:config       'vite:worker-import-meta-url',
  vite:config       'vite:force-systemjs-wrap-complete',
  vite:config       'vite:watch-package-data',
  vite:config       'commonjs',
  vite:config       'vite:data-uri',
  vite:config       'vite:asset-import-meta-url',
  vite:config       'vite:dynamic-import-vars',
  vite:config       'vite:import-glob',
  vite:config       'vite:build-import-analysis',
  vite:config       'vite:esbuild-transpile',
  vite:config       'vite:terser',
  vite:config       'vite:manifest',
  vite:config       'vite:reporter',
  vite:config       'vite:load-fallback'
  vite:config     ],
  vite:config     rollupOptions: {},
  vite:config     getSortedPlugins: [Function: getSortedPlugins],
  vite:config     getSortedPluginHooks: [Function: getSortedPluginHooks]
  vite:config   },
  vite:config   getSortedPlugins: [Function: getSortedPlugins],
  vite:config   getSortedPluginHooks: [Function: getSortedPluginHooks]
  vite:config } +182ms
vite v3.1.7 building for production...
✓ 156 modules transformed.
dist/client/vite-plugin-ssr.json       0.13 KiB
dist/client/manifest.json              1.68 KiB
dist/client/azava-landing.mjs          0.32 KiB / gzip: 0.26 KiB
dist/client/azava-landing3.mjs         0.04 KiB / gzip: 0.06 KiB
dist/client/azava-landing5.mjs         2.57 KiB / gzip: 1.12 KiB
dist/client/assets/chunk-f4ca50e2.js   22.99 KiB / gzip: 6.97 KiB
dist/client/azava-landing4.mjs         38.23 KiB / gzip: 11.31 KiB
dist/client/assets/chunk-0555f750.js   70.77 KiB / gzip: 17.37 KiB
dist/client/assets/chunk-5594f375.js   58.71 KiB / gzip: 17.95 KiB
  vite:config bundled config file loaded in 98.83ms +21s
  vite:esbuild init tsconfck (root: /home/runner/React-styled-components-SSG) +21s
  vite:esbuild init tsconfck (root: /home/runner/React-styled-components-SSG) +11ms
  vite:esbuild init tsconfck (root: /home/runner/React-styled-components-SSG) +0ms
  vite:esbuild init tsconfck (root: /home/runner/React-styled-components-SSG) +0ms
  vite:esbuild init tsconfck end +73ms
  vite:esbuild init tsconfck end +0ms
  vite:esbuild init tsconfck end +1ms
  vite:esbuild init tsconfck end +0ms
  vite:config using resolved config: {
  vite:config   server: {
  vite:config     preTransformRequests: true,
  vite:config     host: '0.0.0.0',
  vite:config     middlewareMode: false,
  vite:config     fs: { strict: true, allow: [Array], deny: [Array] },
  vite:config     port: 3000
  vite:config   },
  vite:config   build: {
  vite:config     target: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari13' ],
  vite:config     polyfillModulePreload: true,
  vite:config     outDir: 'dist/server',
  vite:config     assetsDir: 'assets',
  vite:config     assetsInlineLimit: 4096,
  vite:config     cssCodeSplit: false,
  vite:config     cssTarget: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari13' ],
  vite:config     sourcemap: false,
  vite:config     rollupOptions: {
  vite:config       output: [Object],
  vite:config       onwarn: [Function (anonymous)],
  vite:config       input: [Object]
  vite:config     },
  vite:config     minify: false,
  vite:config     terserOptions: {},
  vite:config     write: true,
  vite:config     emptyOutDir: null,
  vite:config     manifest: false,
  vite:config     lib: {
  vite:config       entry: '/home/runner/React-styled-components-SSG/pages/index.page.tsx',
  vite:config       name: 'StyledComponentsSSG'
  vite:config     },
  vite:config     ssr: true,
  vite:config     ssrManifest: false,
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit: 500,
  vite:config     watch: null,
  vite:config     polyfillDynamicImport: false,
  vite:config     commonjsOptions: { include: [Array], extensions: [Array] },
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] }
  vite:config   },
  vite:config   plugins: [
  vite:config     'vite:build-metadata',
  vite:config     'vite:pre-alias',
  vite:config     'alias',
  vite:config     'vite:react-babel',
  vite:config     'vite:react-refresh',
  vite:config     'vite:react-jsx',
  vite:config     'vite-plugin-ssr:setVitePluginSsrConfig',
  vite:config     'vite-plugin-ssr:extractAssets-2',
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:resolve',
  vite:config     'vite:html-inline-proxy',
  vite:config     'vite:css',
  vite:config     'vite:esbuild',
  vite:config     'vite:json',
  vite:config     'vite:wasm-helper',
  vite:config     'vite:worker',
  vite:config     'vite:asset',
  vite:config     'vite-plugin-ssr:commonConfig',
  vite:config     'vite-plugin-ssr:virtualModulePageFiles',
  vite:config     'vite-plugin-ssr:buildConfig',
  vite:config     'vite-plugin-ssr:autoFullBuild',
  vite:config     'vite-plugin-ssr:pluginManifest',
  vite:config     'vite-plugin-ssr:packageJsonFile',
  vite:config     'vite-plugin-ssr:removeRequireHookPlugin',
  vite:config     'vite-plugin-ssr:extractAssets-3',
  vite:config     'vite-plugin-ssr:retrieveDevServer',
  vite:config     '@brillout/vite-plugin-import-build:vite-plugin-ssr',
  vite:config     'vite:wasm-fallback',
  vite:config     'vite:define',
  vite:config     'vite:css-post',
  vite:config     'vite:build-html',
  vite:config     'vite:worker-import-meta-url',
  vite:config     'vite:force-systemjs-wrap-complete',
  vite:config     'vite:watch-package-data',
  vite:config     'commonjs',
  vite:config     'vite:data-uri',
  vite:config     'vite:asset-import-meta-url',
  vite:config     'vite:dynamic-import-vars',
  vite:config     'vite:import-glob',
  vite:config     'vite-plugin-ssr:distFileNames',
  vite:config     'vite-plugin-ssr:extractAssets-1',
  vite:config     'vite-plugin-ssr:extractExportNames',
  vite:config     'vite-plugin-ssr:suppressRollupWarning',
  vite:config     'vite-plugin-ssr:importBuild:config',
  vite:config     'vite:build-import-analysis',
  vite:config     'vite:esbuild-transpile',
  vite:config     'vite:reporter',
  vite:config     'vite:load-fallback'
  vite:config   ],
  vite:config   configFile: '/home/runner/React-styled-components-SSG/vite.config.ts',
  vite:config   root: '/home/runner/React-styled-components-SSG',
  vite:config   __triggedByAutoFullBuild: true,
  vite:config   resolve: { dedupe: [ 'react', 'react-dom' ], alias: [ [Object], [Object] ] },
  vite:config   optimizeDeps: {
  vite:config     disabled: 'build',
  vite:config     include: [ 'react/jsx-runtime', 'react/jsx-dev-runtime', 'react' ],
  vite:config     esbuildOptions: { preserveSymlinks: undefined }
  vite:config   },
  vite:config   vitePluginSsr: {
  vite:config     disableAutoFullBuild: false,
  vite:config     pageFiles: { include: [] },
  vite:config     prerender: {
  vite:config       partial: false,
  vite:config       noExtraDir: false,
  vite:config       parallel: true,
  vite:config       disableAutoRun: false
  vite:config     },
  vite:config     includeCSS: [],
  vite:config     includeAssetsImportedByServer: false
  vite:config   },
  vite:config   appType: 'custom',
  vite:config   experimental: { importGlobRestoreExtension: true, hmrPartialAccept: false },
  vite:config   ssr: {
  vite:config     format: 'esm',
  vite:config     target: 'node',
  vite:config     external: [ 'vite-plugin-ssr' ],
  vite:config     optimizeDeps: { disabled: true, esbuildOptions: [Object] }
  vite:config   },
  vite:config   configFileDependencies: [ '/home/runner/React-styled-components-SSG/vite.config.ts' ],
  vite:config   inlineConfig: {
  vite:config     build: { ssr: true },
  vite:config     configFile: '/home/runner/React-styled-components-SSG/vite.config.ts',
  vite:config     root: '/home/runner/React-styled-components-SSG',
  vite:config     __triggedByAutoFullBuild: true
  vite:config   },
  vite:config   base: '/',
  vite:config   publicDir: '/home/runner/React-styled-components-SSG/public',
  vite:config   cacheDir: '/home/runner/React-styled-components-SSG/node_modules/.vite',
  vite:config   command: 'build',
  vite:config   mode: 'production',
  vite:config   isWorker: false,
  vite:config   mainConfig: null,
  vite:config   isProduction: true,
  vite:config   preview: {
  vite:config     port: 3000,
  vite:config     strictPort: undefined,
  vite:config     host: '0.0.0.0',
  vite:config     https: undefined,
  vite:config     open: undefined,
  vite:config     proxy: undefined,
  vite:config     cors: undefined,
  vite:config     headers: undefined
  vite:config   },
  vite:config   env: { BASE_URL: '/', MODE: 'production', DEV: false, PROD: true },
  vite:config   assetsInclude: [Function: assetsInclude],
  vite:config   logger: {
  vite:config     hasWarned: false,
  vite:config     info: [Function: info],
  vite:config     warn: [Function: warn],
  vite:config     warnOnce: [Function: warnOnce],
  vite:config     error: [Function: error],
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(0) { set: [Function (anonymous)] },
  vite:config   createResolver: [Function: createResolver],
  vite:config   worker: {
  vite:config     format: 'iife',
  vite:config     plugins: [
  vite:config       'vite:build-metadata',
  vite:config       'vite:pre-alias',
  vite:config       'alias',
  vite:config       'vite:modulepreload-polyfill',
  vite:config       'vite:resolve',
  vite:config       'vite:html-inline-proxy',
  vite:config       'vite:css',
  vite:config       'vite:esbuild',
  vite:config       'vite:json',
  vite:config       'vite:wasm-helper',
  vite:config       'vite:worker',
  vite:config       'vite:asset',
  vite:config       'vite:wasm-fallback',
  vite:config       'vite:define',
  vite:config       'vite:css-post',
  vite:config       'vite:build-html',
  vite:config       'vite:worker-import-meta-url',
  vite:config       'vite:force-systemjs-wrap-complete',
  vite:config       'vite:watch-package-data',
  vite:config       'commonjs',
  vite:config       'vite:data-uri',
  vite:config       'vite:asset-import-meta-url',
  vite:config       'vite:dynamic-import-vars',
  vite:config       'vite:import-glob',
  vite:config       'vite:build-import-analysis',
  vite:config       'vite:esbuild-transpile',
  vite:config       'vite:reporter',
  vite:config       'vite:load-fallback'
  vite:config     ],
  vite:config     rollupOptions: {},
  vite:config     getSortedPlugins: [Function: getSortedPlugins],
  vite:config     getSortedPluginHooks: [Function: getSortedPluginHooks]
  vite:config   },
  vite:config   getSortedPlugins: [Function: getSortedPlugins],
  vite:config   getSortedPluginHooks: [Function: getSortedPluginHooks],
  vite:config   vitePluginDistImporter: {
  vite:config     libraries: [ [Object] ],
  vite:config     importerAlreadyGenerated: false,
  vite:config     disableAutoImporter: null,
  vite:config     configVersion: 1
  vite:config   }
  vite:config } +103ms
vite v3.1.7 building SSR bundle for production...
dist/client/azava-landing2.mjs         638.07 KiB / gzip: 148.61 KiB
✓ 14 modules transformed.
vite-plugin-ssr 0.4.40 pre-rendering HTML...
dist/server/package.json                              0.02 KiB
dist/server/importBuild.cjs                           0.32 KiB
dist/server/pageFiles.mjs                             2.80 KiB
dist/server/importBuild.mjs                           0.22 KiB
dist/server/assets/index.page.a4d18177.js             0.34 KiB
dist/server/assets/chunk-b3d8d8f2.js                  0.14 KiB
dist/server/assets/_error.page.7aeea150.js            0.03 KiB
dist/server/assets/_default.page.server.05af44d5.js   1.79 KiB
  vite:config bundled config file loaded in 15.24ms +904ms
  vite:esbuild init tsconfck (root: /home/runner/React-styled-components-SSG) +908ms
  vite:esbuild init tsconfck (root: /home/runner/React-styled-components-SSG) +1ms
  vite:esbuild init tsconfck end +3ms
  vite:esbuild init tsconfck end +0ms
  vite:config using resolved config: {
  vite:config   server: {
  vite:config     preTransformRequests: true,
  vite:config     host: '0.0.0.0',
  vite:config     middlewareMode: false,
  vite:config     fs: { strict: true, allow: [Array], deny: [Array] },
  vite:config     port: 3000
  vite:config   },
  vite:config   build: {
  vite:config     target: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari13' ],
  vite:config     polyfillModulePreload: true,
  vite:config     outDir: 'dist',
  vite:config     assetsDir: 'assets',
  vite:config     assetsInlineLimit: 4096,
  vite:config     cssCodeSplit: false,
  vite:config     cssTarget: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari13' ],
  vite:config     sourcemap: false,
  vite:config     rollupOptions: {},
  vite:config     minify: 'esbuild',
  vite:config     terserOptions: {},
  vite:config     write: true,
  vite:config     emptyOutDir: null,
  vite:config     manifest: false,
  vite:config     lib: {
  vite:config       entry: '/home/runner/React-styled-components-SSG/pages/index.page.tsx',
  vite:config       name: 'StyledComponentsSSG'
  vite:config     },
  vite:config     ssr: false,
  vite:config     ssrManifest: false,
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit: 500,
  vite:config     watch: null,
  vite:config     commonjsOptions: { include: [Array], extensions: [Array] },
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] }
  vite:config   },
  vite:config   plugins: [
  vite:config     'vite:pre-alias',
  vite:config     'alias',
  vite:config     'vite:react-babel',
  vite:config     'vite:react-refresh',
  vite:config     'vite:react-jsx',
  vite:config     'vite-plugin-ssr:setVitePluginSsrConfig',
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:optimized-deps',
  vite:config     'vite:resolve',
  vite:config     'vite:html-inline-proxy',
  vite:config     'vite:css',
  vite:config     'vite:esbuild',
  vite:config     'vite:json',
  vite:config     'vite:wasm-helper',
  vite:config     'vite:worker',
  vite:config     'vite:asset',
  vite:config     'vite-plugin-ssr:commonConfig',
  vite:config     'vite-plugin-ssr:virtualModulePageFiles',
  vite:config     'vite-plugin-ssr:retrieveDevServer',
  vite:config     'vite:wasm-fallback',
  vite:config     'vite:define',
  vite:config     'vite:css-post',
  vite:config     'vite:worker-import-meta-url',
  vite:config     'vite:dynamic-import-vars',
  vite:config     'vite:import-glob',
  vite:config     'vite-plugin-ssr:extractExportNames',
  vite:config     'vite-plugin-ssr:importBuild:config',
  vite:config     'vite:client-inject',
  vite:config     'vite:import-analysis'
  vite:config   ],
  vite:config   configFile: '/home/runner/React-styled-components-SSG/vite.config.ts',
  vite:config   root: '/home/runner/React-styled-components-SSG',
  vite:config   resolve: { dedupe: [ 'react', 'react-dom' ], alias: [ [Object], [Object] ] },
  vite:config   optimizeDeps: {
  vite:config     disabled: 'build',
  vite:config     include: [ 'react/jsx-runtime', 'react/jsx-dev-runtime', 'react' ],
  vite:config     esbuildOptions: { preserveSymlinks: undefined }
  vite:config   },
  vite:config   vitePluginSsr: {
  vite:config     disableAutoFullBuild: false,
  vite:config     pageFiles: { include: [] },
  vite:config     prerender: {
  vite:config       partial: false,
  vite:config       noExtraDir: false,
  vite:config       parallel: true,
  vite:config       disableAutoRun: false
  vite:config     },
  vite:config     includeCSS: [],
  vite:config     includeAssetsImportedByServer: false
  vite:config   },
  vite:config   appType: 'custom',
  vite:config   experimental: { importGlobRestoreExtension: true, hmrPartialAccept: false },
  vite:config   configFileDependencies: [ '/home/runner/React-styled-components-SSG/vite.config.ts' ],
  vite:config   inlineConfig: {
  vite:config     configFile: '/home/runner/React-styled-components-SSG/vite.config.ts',
  vite:config     root: '/home/runner/React-styled-components-SSG'
  vite:config   },
  vite:config   base: '/',
  vite:config   publicDir: '/home/runner/React-styled-components-SSG/public',
  vite:config   cacheDir: '/home/runner/React-styled-components-SSG/node_modules/.vite',
  vite:config   command: 'vite-plugin-ssr pre-rendering',
  vite:config   mode: 'production',
  vite:config   ssr: {
  vite:config     format: 'esm',
  vite:config     target: 'node',
  vite:config     optimizeDeps: { disabled: true, esbuildOptions: [Object] }
  vite:config   },
  vite:config   isWorker: false,
  vite:config   mainConfig: null,
  vite:config   isProduction: true,
  vite:config   preview: {
  vite:config     port: 3000,
  vite:config     strictPort: undefined,
  vite:config     host: '0.0.0.0',
  vite:config     https: undefined,
  vite:config     open: undefined,
  vite:config     proxy: undefined,
  vite:config     cors: undefined,
  vite:config     headers: undefined
  vite:config   },
  vite:config   env: { BASE_URL: '/', MODE: 'production', DEV: false, PROD: true },
  vite:config   assetsInclude: [Function: assetsInclude],
  vite:config   logger: {
  vite:config     hasWarned: false,
  vite:config     info: [Function: info],
  vite:config     warn: [Function: warn],
  vite:config     warnOnce: [Function: warnOnce],
  vite:config     error: [Function: error],
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(0) {},
  vite:config   createResolver: [Function: createResolver],
  vite:config   worker: {
  vite:config     format: 'iife',
  vite:config     plugins: [
  vite:config       'vite:pre-alias',
  vite:config       'alias',
  vite:config       'vite:modulepreload-polyfill',
  vite:config       'vite:optimized-deps',
  vite:config       'vite:resolve',
  vite:config       'vite:html-inline-proxy',
  vite:config       'vite:css',
  vite:config       'vite:esbuild',
  vite:config       'vite:json',
  vite:config       'vite:wasm-helper',
  vite:config       'vite:worker',
  vite:config       'vite:asset',
  vite:config       'vite:wasm-fallback',
  vite:config       'vite:define',
  vite:config       'vite:css-post',
  vite:config       'vite:worker-import-meta-url',
  vite:config       'vite:dynamic-import-vars',
  vite:config       'vite:import-glob',
  vite:config       'vite:client-inject',
  vite:config       'vite:import-analysis'
  vite:config     ],
  vite:config     rollupOptions: {},
  vite:config     getSortedPlugins: [Function: getSortedPlugins],
  vite:config     getSortedPluginHooks: [Function: getSortedPluginHooks]
  vite:config   },
  vite:config   getSortedPlugins: [Function: getSortedPlugins],
  vite:config   getSortedPluginHooks: [Function: getSortedPluginHooks]
  vite:config } +9ms
[vite-plugin-ssr:autoFullBuild] Cannot read property 'withConfig' of undefined
[vite-plugin-ssr:autoFullBuild] Cannot read property 'withConfig' of undefined (x2)
error during build:
TypeError: Cannot read property 'withConfig' of undefined
    at file:///home/runner/React-styled-components-SSG/dist/server/assets/index.page.a4d18177.js:4:22
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.pageFile.loadFile (/home/runner/React-styled-components-SSG/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/parseGlobResults.js:25:40)
    at async Promise.all (index 0)
    at async loadPageFilesServerSide (/home/runner/React-styled-components-SSG/node_modules/vite-plugin-ssr/dist/cjs/shared/getPageFiles/analyzePageServerSide/loadPageFilesServerSide.js:8:5)
    at async Promise.all (index 0)
    at async loadPageFilesServer (/home/runner/React-styled-components-SSG/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:375:69)
    at async /home/runner/React-styled-components-SSG/node_modules/vite-plugin-ssr/dist/cjs/node/prerender.js:203:48
error Command failed with exit code 1.
 ```
  
</details>

**Comment by okomarov** [comment]
@brillout Hey, totally understand and I can say we did the homework!
In fact, the linked replit is basically a minimal reproduction of one of your examples + styled components, so it could become a React + Styled Components example here. If not of interest (and btw, if you think styled components for SSG is a bad idea, that's valuable feedback), would you spare your 2 cents of where the issue might be coming from? I've got a couple of ideas:
* tsconfig
* put styled components into ssr.external

**Comment by brillout** [comment]
It's likely a styled-components bug, so I'd reach out to these guys.

**Comment by brillout** [comment]
> Apologies for the confusing `[vite-plugin-ssr:autoFullBuild]` prefix, I'll try to fix this (it's a Rollup thing so not sure I'll be able to get rid of the prefix).

Done.
