### ISSUE TITLE
`{"url":"undefined"}`

### ISSUE THREAD

**Issue by StevenWhygo** [brillout/vite-plugin-ssr#505]
### Description

Error: [vite-plugin-ssr@0.4.46][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust. Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): `{"url":"undefined"}`.

### Error Stack

```shell
at parseUrl (/Users/wukeying/Project/ieltstaipei/node_modules/vite-plugin-ssr/dist/cjs/utils/parseUrl.js:17:25)
    at hasSuffix (/Users/wukeying/Project/ieltstaipei/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage/handlePageContextRequestUrl.js:15:65)
    at handlePageContextRequestUrl (/Users/wukeying/Project/ieltstaipei/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage/handlePageContextRequestUrl.js:8:10)
    at _urlProcessor (/Users/wukeying/Project/ieltstaipei/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:144:99)
    at getUrlParsed (/Users/wukeying/Project/ieltstaipei/node_modules/vite-plugin-ssr/dist/cjs/shared/addComputedUrlProps.js:45:15)
    at Object.urlPathnameGetter [as urlPathname] (/Users/wukeying/Project/ieltstaipei/node_modules/vite-plugin-ssr/dist/cjs/shared/addComputedUrlProps.js:50:26)
    at route (/Users/wukeying/Project/ieltstaipei/node_modules/vite-plugin-ssr/dist/cjs/shared/route.js:52:13)
    at async renderPage_ (/Users/wukeying/Project/ieltstaipei/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:39:25)
    at async renderPage (/Users/wukeying/Project/ieltstaipei/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:155:16)
    at async Object.<anonymous> (file:///Users/wukeying/Project/ieltstaipei/server/index.mjs:52:25)
```

**Comment by brillout** [comment]
I can't reproduce.

I'd need a reproduction. I'll re-open then.
