### ISSUE TITLE
Latest version (0.4.49) breaks Vite build when `root` and `outDir` options are used

### ISSUE THREAD

**Issue by micah-redwood** [brillout/vite-plugin-ssr#518]
### Description

First off, thanks for maintaining this awesome plugin! Has been wonderful to work with thus far. 

I have my Vite project setup so that all the React-related files are in a `src` folder, and it builds to a `dist` folder (as [recommended on Stackoverflow](https://stackoverflow.com/a/66867648/1546808)). It's based on the `react-full` example.

```ts
// vite-config.ts
export default defineConfig({
  plugins: [svgr(), react(), ssr({ prerender: true })],
  root: 'src',
  build: {
    outDir: '../dist',
  },
  // We manually add a list of dependencies to be pre-bundled, in order to avoid a page reload at dev start which breaks vite-plugin-ssr's CI
  optimizeDeps: { include: ['cross-fetch'] },
});
```

My project structure looks like this:
```
node_modules/
dist/
src/
    pages, components, renderer, assets
package.json
vite.config.ts
..other config files
```
<img width="415" alt="image" src="https://user-images.githubusercontent.com/117694460/202544365-4a592020-b592-4893-a7ba-38225bdfc17e.png">

My `vite` and `vite build` commands are working perfectly in version `0.4.48`, but when I upgraded to the next patch release (`0.4.49`) my builds started to break. Reverting to `0.4.48` fixed the issue. 

### Error Stack

```shell
my-app git:(form-improvements) ✗ npm run dev

> vite-react-ts-tailwind@0.0.0 dev
> vite

error when starting dev server:
Error: No package.json found at /../my-app/src
    at getUserPackageJson (/../my-app/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config/stemUtils.js:65:15)
    at getStemPackages (/../my-app/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config/stemUtils.js:13:25)
    at findConfigVpsFromStemPackages (/../my-app/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config/findConfigVpsFromStemPackages.js:8:64)
    at resolveConfigVps (/../my-app/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config.js:29:102)
    at configResolved (/../my-app/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config.js:12:38)
    at file:///../my-app/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62578:28
    at Array.map (<anonymous>)
    at resolveConfig (file:///../my-app/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62578:14)
    at async createServer (file:///../my-app/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:61641:20)
    at async CAC.<anonymous> (file:///../my-app/node_modules/vite/dist/node/cli.js:707:24)
```

**Comment by brillout** [comment]
I see. Let me fix this.

**Comment by brillout** [comment]
Fix released in `0.4.50`. I didn't test but it should work. Let me know if it doesn't.

**Comment by brillout** [comment]
Also, in case your company is up for it: https://github.com/sponsors/brillout.

**Comment by micah-redwood** [comment]
Awesome, that fixed it, thanks @brillout !

I'll check in about the sponsorship.

**Comment by brillout** [comment]
> I'll check in about the sponsorship.

Thanks 👌. Keep me updated, even if it's a no. I'm interested in how companies react.
