### ISSUE TITLE
Prerendering with an extension & pageFilesDist crashes

### ISSUE THREAD

**Issue by r0m4n27** [brillout/vite-plugin-ssr#550]
### Description

This happened to me when using the new `extensions` config option with the `pageFilesDist`. 
I can build a normal project where no prerendering is used but when the `prerender` option
is enabled, it crashes. When I used the `pageFilesSrc` option instead, both building
with or without, `prerender` worked as expected.

### Error Message + Error Stack

```shell
Error: [vite-plugin-ssr@0.4.55][Bug] You stumbled upon a bug in vite-plugin-ssr's source code.
    at assertPageContextProvidedByUser (/<path_to_project>/node_modules/.pnpm/vite-plugin-ssr@0.4.55_vite@3.2.5/node_modules/vite-plugin-ssr/dist/cjs/shared/assertPageContextProvidedByUser.js:9:28)
    at assertHookResult (/<path_to_project>/node_modules/.pnpm/vite-plugin-ssr@0.4.55_vite@3.2.5/node_modules/vite-plugin-ssr/dist/cjs/shared/assertHookResult.js:15:79)
    at executeRenderHook (/<path_to_project>/node_modules/.pnpm/vite-plugin-ssr@0.4.55_vite@3.2.5/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage/renderPageContext.js:180:49)
    at async prerenderPageContext (/<path_to_project>/node_modules/.pnpm/vite-plugin-ssr@0.4.55_vite@3.2.5/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage/renderPageContext.js:84:30)
    at async /<path_to_project>/node_modules/.pnpm/vite-plugin-ssr@0.4.55_vite@3.2.5/node_modules/vite-plugin-ssr/dist/cjs/node/prerender.js:324:57
```

**Comment by brillout** [comment]
Curious: what is it you're building?

**Comment by r0m4n27** [comment]
It's nothing special, I just have some personal projects where I wanted to share the default renderers for the pages.
Also thank you for the fix. The build worked now for me with the `prerender` option enabled.

**Comment by brillout** [comment]
Have a look at `examples/stem-react/`. If you believe your renderer to be generic enough, you may want to open source it.
