### ISSUE TITLE
Unable to build while using Vitest

### ISSUE THREAD

**Issue by MrFoxPro** [brillout/vite-plugin-ssr#561]
### Description

Including vitest dependency in source files breaks build:
```js
const VAR = 5;
if (import.meta.vitest) {
  const { expect, it } = await import('vitest');
  it('renders correctly', () => {
    expect(VAR).toEqual(5);
  });
}
```

Reproduction: 
https://stackblitz.com/edit/solidjs-templates-8t9sys?file=project/src/vite.config.js
`cd ./project && pnpm i && pnpm test && pnpm build`

### Error Message + Error Stack

```shell
'fileURLToPath' is not exported by __vite-browser-external, imported by node_modules/.pnpm/local-pkg@0.4.2/node_modules/local-pkg/dist/shared.mjs
file: /home/projects/solidjs-templates-8t9sys/project/node_modules/.pnpm/local-pkg@0.4.2/node_modules/local-pkg/dist/shared.mjs:41:9
39: import path from "path";
40: import fs, { promises as fsPromises } from "fs";
41: import { fileURLToPath } from "url";
             ^
42: 
43: // node_modules/.pnpm/yocto-queue@1.0.0/node_modules/yocto-queue/index.js
error during build:
Error: 'fileURLToPath' is not exported by __vite-browser-external, imported by node_modules/.pnpm/local-pkg@0.4.2/node_modules/local-pkg/dist/shared.mjs
    at error (file://file:///home/projects/solidjs-templates-8t9sys/project/node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:1888:30)
    at Module.error (file://file:///home/projects/solidjs-templates-8t9sys/project/node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:12442:16)
    at Module.traceVariable (file://file:///home/projects/solidjs-templates-8t9sys/project/node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:12801:29)
    at ModuleScope.findVariable (file://file:///home/projects/solidjs-templates-8t9sys/project/node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:11453:39)
    at ReturnValueScope.findVariable (file://file:///home/projects/solidjs-templates-8t9sys/project/node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:6385:38)
    at Identifier.bind (file://file:///home/projects/solidjs-templates-8t9sys/project/node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:7452:40)
    at CallExpression.bind (file://file:///home/projects/solidjs-templates-8t9sys/project/node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:5282:23)
    at CallExpression.bind (file://file:///home/projects/solidjs-templates-8t9sys/project/node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:8948:15)
    at ConditionalExpression.bind (file://file:///home/projects/solidjs-templates-8t9sys/project/node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:5282:23)
    at ArrowFunctionExpression.bind (file://file:///home/projects/solidjs-templates-8t9sys/project/node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:5282:23)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by brillout** [comment]
I'd guess it's more related to Vitest than VPS.

**Comment by brillout** [comment]
Closing but let me know if you have some evidence that it's related to VPS, I'll re-open then.
