### ISSUE TITLE
stumbled upon a bug in vite-plugin-ssr's source code.

### ISSUE THREAD

**Issue by techniath** [brillout/vite-plugin-ssr#583]
### Error Message + Error Stack

```shell
Error: [vite-plugin-ssr@0.4.65][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer 
will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at assertConfig (C:\Techniath\sa-garage-door\node_modules\vite-plugin-ssr\dist\cjs\utils\getOutDirs.js:92:29)
    at determineOutDir (C:\Techniath\sa-garage-door\node_modules\vite-plugin-ssr\dist\cjs\utils\getOutDirs.js:34:9)
    at Object.config (C:\Techniath\sa-garage-door\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\buildConfig.js:22:57)
    at resolveConfig (C:\Techniath\sa-garage-door\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:61175:33)
    at async doBuild (C:\Techniath\sa-garage-door\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:39023:20)
    at async build (C:\Techniath\sa-garage-door\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:39011:16)
    at async triggerFullBuild (C:\Techniath\sa-garage-door\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\autoFullBuild.js:50:5)
    at async Object.writeBundle (C:\Techniath\sa-garage-door\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\autoFullBuild.js:24:17)
    at async Promise.all (index 0)
    at async handleGenerateWrite (C:\Techniath\sa-garage-door\node_modules\rollup\dist\shared\rollup.js:23589:9)
    at async doBuild (C:\Techniath\sa-garage-door\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:39185:20)
    at async build (C:\Techniath\sa-garage-door\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:39011:16)
    at async CAC.<anonymous> (C:\Techniath\sa-garage-door\node_modules\vite\dist\node\cli.js:738:9)
[!] Error: unfinished hook action(s) on exit:
(vite-plugin-ssr:autoFullBuild) writeBundle

ERROR: "build:vite:client" exited with 1.
ERROR: "build:vite" exited with 1.
```

**Comment by techniath** [comment]
Please ignore, I was running incorrect build command. I have another issue. I will open the ticket for that
