### ISSUE TITLE
Build command error

### ISSUE THREAD

**Issue by iiio2** [brillout/vite-plugin-ssr#595]
### Description

I am using React-SSR using Vite. After running npm run build in React-SSR on vite, I am getting the error. 
after installing vite-plugin-ssr and @netlify/functions Inside vite.config.ts i have added 

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import VitePluginSSR from "vite-plugin-ssr/plugin";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    VitePluginSSR({
      prerender: true,
      includeAssetsImportedByServer: true,
    }),
  ],
});

my package.json

{
  "name": "vidly-ssr",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "node server",
    "build": "npm run build:client && npm run build:server",
    "build:client": "vite build --ssrManifest --outDir dist/client",
    "build:server": "vite build --ssr src/entry-server.tsx --outDir dist/server",
    "preview": "cross-env NODE_ENV=production node server"
  },
  "dependencies": {
    "@netlify/functions": "^1.4.0",
    "bootstrap": "^5.2.3",
    "bootstrap-icons": "^1.10.3",
    "compression": "^1.7.4",
    "express": "^4.18.2",
    "lodash": "^4.17.21",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "sirv": "^2.0.2",
    "vite-plugin-ssr": "^0.4.69"
  },
  "devDependencies": {
    "@types/lodash": "^4.14.191",
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.9",
    "@vitejs/plugin-react-swc": "^3.0.0",
    "cross-env": "^7.0.3",
    "typescript": "^4.9.4",
    "vite": "^4.0.0"
  }
}

functions/index.ts also added. netlify.toml also added.

### Error Message + Error Stack

```shell
When I run npm run build, I get the error in the terminal 

Error: [vite-plugin-ssr@0.4.69][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at assertConfig (C:\Users\Admin\Desktop\vidly-ssr\node_modules\vite-plugin-ssr\dist\cjs\utils\getOutDirs.js:92:29)
    at determineOutDir (C:\Users\Admin\Desktop\vidly-ssr\node_modules\vite-plugin-ssr\dist\cjs\utils\getOutDirs.js:34:9)
    at config (C:\Users\Admin\Desktop\vidly-ssr\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\buildConfig.js:22:57)
    at runConfigHook (file:///C:/Users/Admin/Desktop/vidly-ssr/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62122:31)
    at async resolveConfig (file:///C:/Users/Admin/Desktop/vidly-ssr/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:61623:14)
    at async doBuild (file:///C:/Users/Admin/Desktop/vidly-ssr/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44358:20)
    at async Module.build (file:///C:/Users/Admin/Desktop/vidly-ssr/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44347:16)
    at async triggerFullBuild (C:\Users\Admin\Desktop\vidly-ssr\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\autoFullBuild.js:50:5)
    at async Object.writeBundle (C:\Users\Admin\Desktop\vidly-ssr\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\autoFullBuild.js:24:17)
    at async Promise.all (index 0)
    at async PluginDriver.hookParallel (file:///C:/Users/Admin/Desktop/vidly-ssr/node_modules/rollup/dist/es/shared/rollup.js:23588:9)
    at async file:///C:/Users/Admin/Desktop/vidly-ssr/node_modules/rollup/dist/es/shared/rollup.js:24990:13
    at async catchUnfinishedHookActions (file:///C:/Users/Admin/Desktop/vidly-ssr/node_modules/rollup/dist/es/shared/rollup.js:24022:20)
    at async doBuild (file:///C:/Users/Admin/Desktop/vidly-ssr/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44518:22)
    at async build (file:///C:/Users/Admin/Desktop/vidly-ssr/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44347:16)
    at async CAC.<anonymous> (file:///C:/Users/Admin/Desktop/vidly-ssr/node_modules/vite/dist/node/cli.js:808:9)
```

**Comment by iiio2** [comment]
@brillout , Get OutDir => dist/client

**Comment by brillout** [comment]
Hm, that's quite unexpected. I'll need a reproduction for this one.

**Comment by iiio2** [comment]
@brillout , this is my project. check please : https://github.com/iiio2/vidly-ssr

**Comment by brillout** [comment]
Your scripts are wrong, see `examples/`.

I'll improve the error message thrown by VPS.

**Comment by iiio2** [comment]
@brillout , can you tell me where i have done wrong ? it would be easy for me actually. What i need to change.

**Comment by iiio2** [comment]
Actually Vite has introduced server-side rendering i have seen. I have used vite's react-ssr.

**Comment by brillout** [comment]
See `examples/` and https://brillout.github.io/rules/.

**Comment by iiio2** [comment]
@brillout . oh. thanks. 
by the way, there you have said, "Your prolem is clearly related to our tool". I think it would be "Your problem is clearly related to our tool"

![Untitled](https://user-images.githubusercontent.com/47961062/212320959-04437e61-3b4c-4ff5-9ff6-f611f68b96ec.jpg)

**Comment by brillout** [comment]
👍 PR welcome.

**Comment by iiio2** [comment]
@brillout pls check - https://github.com/brillout/rules/pull/1

**Comment by brillout** [comment]
> I'll improve the error message thrown by VPS.

IIRC it's already done.
