### ISSUE TITLE
Solid Framework

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#607]
### Description

There is an increasing interest in using VPS with Solid, including building Solid frameworks.

I'm creating this ticket to centralize dicussions around Solid.

CC @XiNiHa @vchirikov @nksaraf.

**Comment by brillout** [comment]
👍 Looking forward to it.

**Comment by ivanhofer** [comment]
@vchirikov great to see you are using `typesafe-i18n` 🎉
Let me know if you need any help/tipps on that integration.

**Comment by ryoid** [comment]
I have been using vps + solid in production, deployed to Vercel. The biggest benefit right now would be to have per-page rendering modes which is not possible with Solid Start. Did not have any major issues migrating our SPA over. This is on `v0.3`, have not had the time to upgrade.

Quite surprised that there aren't more people using it.

**Comment by samuelstroschein** [comment]
We are also using VPS + SolidJS in production for anyone curious https://github.com/inlang/inlang/tree/main/source-code/website.

**Comment by rtritto** [comment]
Similar related alternatives using Fastify + SolidJS:
- [@fastify/vite](https://www.npmjs.com/package/@fastify/vite) ([repo](https://github.com/fastify/fastify-vite))
- [fastify-dx-solid](https://www.npmjs.com/package/fastify-dx-solid) ([repo](https://github.com/fastify/fastify-dx))

Maybe they are usefull to support/collaborate or get ideas or compare them with this.

**Comment by brillout** [comment]
Some new Solid discussions:
 - https://github.com/solidjs/solid/discussions/1631
 - https://github.com/solidjs/solid/discussions/1633
 - [Tweet "Solid has only 4 known bugs [...] That's awesome."](https://twitter.com/brillout/status/1636682370890838016)

**Comment by ivanhofer** [comment]
Hi,
we tried to add the solid devtools to the inlang project but we run into the issue you see in the stack trace below.
We have used the official getting started guide and have not enabled any options https://github.com/thetarnav/solid-devtools/tree/main/packages/extension#getting-started

It would be great if the devtools would work too when official solid support is here.

```
Error: [vite-plugin-ssr@0.4.70][Wrong Usage] You are using a Vite Plugin that transforms the HTML in a way that conflicts with vite-plugin-ssr. Create a new GitHub ticket to discuss a solution.
    at getViteDevScripts (/home/inlang/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/html/injectAssets/getViteDevScripts.js:2:1121)
    at async getMergedScriptTag (/home/inlang/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/html/injectAssets/getHtmlTags.js:2:3685)
    at async getHtmlTags (/home/inlang/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/html/injectAssets/getHtmlTags.js:2:2903)
    at async injectHtmlTagsToString (/home/inlang/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/html/injectAssets.js:2:601)
    at async renderDocumentHtml (/home/inlang/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/html/renderHtml.js:2:1654)
    at async executeRenderHook (/home/inlang/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/renderPageContext.js:2:10396)
    at async renderPageContext (/home/inlang/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/renderPageContext.js:2:2755)
    at async renderPage (/home/inlang/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:2:1202)
```

**Comment by brillout** [comment]
@ivanhofer I'll have a look at it. Tracking ticket: https://github.com/brillout/vite-plugin-ssr/issues/761.

**Comment by brillout** [comment]
Done: https://github.com/magne4000/vike-solid.

An official release is coming after the Vike rebranding and the V1 design stable release (both coming soon). Feel free to already start using it and give feedback.
