### ISSUE TITLE
renderPage issue (0, utils_1.assert)(globalObject.globalContext);

### ISSUE THREAD

**Issue by thernandezcolon** [brillout/vite-plugin-ssr#625]
### Description

My goal is to do SSR with EJS and Express

From https://vite-plugin-ssr.com/renderPage:
```
    const pageContextInit = {
      urlOriginal: req.originalUrl,
    };
    const pageContext = await renderPage(pageContextInit);
    const { httpResponse } = pageContext;

    if (!httpResponse) return next();
    const { body, statusCode, contentType, earlyHints } = httpResponse;
    if (res.writeEarlyHints) res.writeEarlyHints({ link: earlyHints.map((e) => e.earlyHintLink) });
    res.status(statusCode).type(contentType).send(body);
```
On this line 
`    
const pageContext = await renderPage(pageContextInit);
`

Dont know where to look at from the error
    

### Error Message + Error Stack

```shell
node_modules/vite-plugin-ssr/dist/cjs/node/runtime/globalContext.js:12
    (0, utils_1.assert)(globalObject.globalContext);
                       ^
Error: [vite-plugin-ssr@0.4.73][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust. 
    at getGlobalContext (node_modules/vite-plugin-ssr/dist/cjs/node/runtime/globalContext.js:12:24)
    at viteAlreadyLoggedError (node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/viteLogging.js:18:68)
    at logError (node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/logError.js:13:50)
    at renderPage (node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:26:33)
    at async src/server/main.ts:157:25
```

**Comment by brillout** [comment]
I'll need a reproduction for that one.

**Comment by iMrDJAi** [comment]
@brillout I confirm that I'm getting it as well on my `node:16` docker container in production.

```
Error: [vite-plugin-ssr@0.4.73][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust. 
    at getGlobalContext (/usr/src/app/server/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/globalContext.js:12:24)
    at viteAlreadyLoggedError (/usr/src/app/server/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/viteLogging.js:18:68)
    at logError (/usr/src/app/server/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/logError.js:13:50)
    at Object.renderPage (/usr/src/app/server/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:26:33)
    at async /usr/src/app/server/index.js:2:3001
```

The issue isn't present on my windows development machine.

**Comment by brillout** [comment]
Let me have a closer look.

**Comment by brillout** [comment]
Fix released in `0.4.77`. It was a bug in the error handling logic. This means you may stumble upon another error, create a new issue if you do.

**Comment by iMrDJAi** [comment]
@brillout I'll let you know if I stumble upon another bug. Thank you for your efforts!

**Comment by brillout** [comment]
Sure. And, if I didn't mention it already: https://github.com/sponsors/brillout in case your company is up for it.
