### ISSUE TITLE
UI Framework

### ISSUE THREAD

**Issue by folamy** [brillout/vite-plugin-ssr#64]
Well done for your work, I really appreciate your effort towards DX.
Is it possible to add a CSS/UI framework of choice?
PrimeVue, ant-design-vue, etc!

**Comment by brillout** [comment]
Yes most definitely.

The neat thing here is that *you* control how your pages are rendered. This means you can use whatever tool you want.

Closing but let me know if you have any further doubt/question.

**Comment by folamy** [comment]
Thanks for your response!
However, I am trying to have more control on routes. So, I am using the router example, but I am getting the  error below:
TypeError: Cannot use 'in' operator to search for 'path' in undefined
    at resolve (/home/folamy/Desktop/vue-router/node_modules/vue-router/dist/vue-router.cjs.js:2828:20)
    at pushWithRedirect (/home/folamy/Desktop/vue-router/node_modules/vue-router/dist/vue-router.cjs.js:2931:51)
    at Object.push (/home/folamy/Desktop/vue-router/node_modules/vue-router/dist/vue-router.cjs.js:2901:16)
    at Object.render (/pages/all.page.server.js:11:10)
    at renderHtmlDocument (/home/folamy/Desktop/vue-router/node_modules/vite-plugin-ssr/dist/renderPage.node.js:201:47)
    at renderPageId (/home/folamy/Desktop/vue-router/node_modules/vite-plugin-ssr/dist/renderPage.node.js:116:36)
    at async renderPage (/home/folamy/Desktop/vue-router/node_modules/vite-plugin-ssr/dist/renderPage.node.js:96:24)
    at async /home/folamy/Desktop/vue-router/server/index.js:28:20
[vite-plugin-ssr@0.1.0-beta.43][Warning] No `_error.page.js` found. We recommend creating a `_error.page.js` file. (This warning is not shown in production.)

How do I fix this?

**Comment by brillout** [comment]
FYI, https://github.com/brillout/vite-plugin-ssr#other-tools goes in depth. You'll have confidence you can use whatever tool you want.
