### ISSUE TITLE
Vue-router! 

### ISSUE THREAD

**Issue by folamy** [brillout/vite-plugin-ssr#65]
Thanks one again!
However, I am trying to have more control on routes. So, I am using the router example, but I am getting the error below:
TypeError: Cannot use 'in' operator to search for 'path' in undefined
at resolve (/home/folamy/Desktop/vue-router/node_modules/vue-router/dist/vue-router.cjs.js:2828:20)
at pushWithRedirect (/home/folamy/Desktop/vue-router/node_modules/vue-router/dist/vue-router.cjs.js:2931:51)
at Object.push (/home/folamy/Desktop/vue-router/node_modules/vue-router/dist/vue-router.cjs.js:2901:16)
at Object.render (/pages/all.page.server.js:11:10)
at renderHtmlDocument (/home/folamy/Desktop/vue-router/node_modules/vite-plugin-ssr/dist/renderPage.node.js:201:47)
at renderPageId (/home/folamy/Desktop/vue-router/node_modules/vite-plugin-ssr/dist/renderPage.node.js:116:36)
at async renderPage (/home/folamy/Desktop/vue-router/node_modules/vite-plugin-ssr/dist/renderPage.node.js:96:24)

**Comment by brillout** [comment]
Hi again.

This a bug related to your code, it's not related to `vite-plugin-ssr`.

**Comment by folamy** [comment]
Hi only copy the source code here: 
[https://github.com/brillout/vite-plugin-ssr/tree/master/examples/vue-router](Router example) and I did yarn install!

**Comment by brillout** [comment]
Hm I see, let me have a look.

**Comment by folamy** [comment]
Alright, thanks!

**Comment by brillout** [comment]
Fixed, see https://github.com/brillout/vite-plugin-ssr/commit/4bf62a1f06f9dc6af3520eb9103f66089d034075.

Note that currently you have to completely replace vite-plugin-ssr's routing with Vue Router.

But there is PR that I will merge today/tomorrow which will enable you to use `vite-plugin-ssr`'s routing (Filesystem Routing and `.page.route.js`) *and* Vue Router at the same time. (Similarly to what Nuxt does.)

**Comment by folamy** [comment]
That would be great!
Thank you.

**Comment by brillout** [comment]
Got delayed by a higher prio ticket. I will, tentatively, merge the PR tomorrow.

**Comment by brillout** [comment]
The PR will be merged later. In case you want to get invovled: https://github.com/brillout/vite-plugin-ssr/pull/40
