### ISSUE TITLE
Error: vite-plugin-ssr tried to access esbuild, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

### ISSUE THREAD

**Issue by bryanjtc** [brillout/vite-plugin-ssr#659]
### Description

I tried to use this package with yarn pnp, and the following error appeared.
### Error Message + Error Stack

```shell
failed to load config from /home/bryan/projects/landing-page-pilando-ando/packages/pilando-ando/vite.config.ts
error when starting dev server:
Error: vite-plugin-ssr tried to access esbuild, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: esbuild
Required by: vite-plugin-ssr@virtual:5383bdd3cca0e6d695e17f4419dad3d5ecb29595bbd36082d1dc6357f901ae43f90f48abc8560272258de209ab01540308806fafe00583b78aba4eec30ca16ef#npm:0.4.84 (via /home/bryan/projects/landing-page-pilando-ando/.yarn/__virtual__/vite-plugin-ssr-virtual-a17a0622a2/0/cache/vite-plugin-ssr-npm-0.4.84-3e25d2d7d1-b16480b319.zip/node_modules/vite-plugin-ssr/dist/cjs/utils/)

Require stack:
- /home/bryan/projects/landing-page-pilando-ando/.yarn/__virtual__/vite-plugin-ssr-virtual-a17a0622a2/0/cache/vite-plugin-ssr-npm-0.4.84-3e25d2d7d1-b16480b319.zip/node_modules/vite-plugin-ssr/dist/cjs/utils/transpileAndLoadScriptFile.js
- /home/bryan/projects/landing-page-pilando-ando/.yarn/__virtual__/vite-plugin-ssr-virtual-a17a0622a2/0/cache/vite-plugin-ssr-npm-0.4.84-3e25d2d7d1-b16480b319.zip/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/utils.js
- /home/bryan/projects/landing-page-pilando-ando/.yarn/__virtual__/vite-plugin-ssr-virtual-a17a0622a2/0/cache/vite-plugin-ssr-npm-0.4.84-3e25d2d7d1-b16480b319.zip/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/index.js
    at require$$0.Module._resolveFilename (/home/bryan/projects/landing-page-pilando-ando/.pnp.cjs:23743:13)
    at require$$0.Module._load (/home/bryan/projects/landing-page-pilando-ando/.pnp.cjs:23593:42)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/bryan/projects/landing-page-pilando-ando/.yarn/__virtual__/vite-plugin-ssr-virtual-a17a0622a2/0/cache/vite-plugin-ssr-npm-0.4.84-3e25d2d7d1-b16480b319.zip/node_modules/vite-plugin-ssr/dist/cjs/utils/transpileAndLoadScriptFile.js:7:35)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at require$$0.Module._extensions..js (/home/bryan/projects/landing-page-pilando-ando/.pnp.cjs:23787:33)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at require$$0.Module._load (/home/bryan/projects/landing-page-pilando-ando/.pnp.cjs:23624:14)
```

**Comment by brillout** [comment]
Fix released in `0.4.86`.
