### ISSUE TITLE
Weird issue when importing prop-types file

### ISSUE THREAD

**Issue by pyrossh** [brillout/vite-plugin-ssr#678]
### Description

For some reason this error shows up when I tried to import a PropType defined in another file.
Here is the commit to reproduce it https://github.com/pyrossh/react-streaming-tigris/commit/fd795a4bc611c6577a0f33f955f80662fb80727a
The entire app stops working. Don't know if this is a telefunc or VPS issue or @grpc/grpc-js issue.

### Error Message + Error Stack

```shell
logging.ts:35 Uncaught (in promise) ReferenceError: process is not defined
    at node_modules/@grpc/grpc-js/build/src/logging.js (logging.ts:35:7)
    at __require2 (chunk-BHN6OJC3.js?v=c502038e:15:50)
    at node_modules/@grpc/grpc-js/build/src/metadata.js (metadata.ts:19:1)
    at __require2 (chunk-BHN6OJC3.js?v=c502038e:15:50)
    at node_modules/@grpc/grpc-js/build/src/call-credentials.js (call-credentials.ts:18:1)
    at __require2 (chunk-BHN6OJC3.js?v=c502038e:15:50)
    at node_modules/@grpc/grpc-js/build/src/index.js (index.ts:25:1)
    at __require2 (chunk-BHN6OJC3.js?v=c502038e:15:50)
    at node_modules/@tigrisdata/core/dist/utility.js (utility.js:30:19)
    at __require2 (chunk-BHN6OJC3.js?v=c502038e:15:50)
```

**Comment by pyrossh** [comment]
Let me know if you want a simpler reproduction or the .env file. I will see if I can reproduce this with a base react-streaming example.

**Comment by brillout** [comment]
> logging.ts:35 Uncaught (in promise) ReferenceError: process is not defined
>    at node_modules/@grpc/grpc-js/build/src/logging.js (logging.ts:35:7)

Seems like an issue on gRPC's side.

I don't think it's the case, but let me know if you believe if it's co-caused by a VPS issue, I'll re-open then.
