### ISSUE TITLE
Internal vite-plugin-ssr bug

### ISSUE THREAD

**Issue by nbrdx** [brillout/vite-plugin-ssr#729]
### Description

I stumbled upon a bug in vite-plugin-ssr's source code, the code is below.

Using `vite-plugin-ssr@0.4.99`

### Error Message + Error Stack

```shell
[vite] Internal server error: [vite-plugin-ssr@0.4.99][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error (the error alone is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
  Plugin: vite:import-analysis
  File: /Volumes/Develop/clubmed/digital-oidc/node_modules/vite-plugin-ssr/dist/esm/client/pageFiles.js
  1  |  import { setPageFiles } from '../shared/getPageFiles';
  2  |  // @ts-ignore
  3  |  import * as pageFilesExports from 'virtual:vite-plugin-ssr:importUserCode:client:server-routing';
     |                                     ^
  4  |  setPageFiles(pageFilesExports);
  5  |  
      at isVirtualFileId (/Volumes/Develop/clubmed/digital-oidc/node_modules/vite-plugin-ssr/dist/cjs/utils/virtual-files.js:13:25)
      at Context.resolveId (/Volumes/Develop/clubmed/digital-oidc/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/index.js:30:45)
      at Object.resolveId (file:///Volumes/Develop/clubmed/digital-oidc/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:35216:55)
      at ModuleGraph.resolveUrl (file:///Volumes/Develop/clubmed/digital-oidc/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:57822:26)
      at ModuleGraph.ensureEntryFromUrl (file:///Volumes/Develop/clubmed/digital-oidc/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:57775:41)
      at normalizeUrl (file:///Volumes/Develop/clubmed/digital-oidc/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:40223:43)
      at TransformContext.transform (file:///Volumes/Develop/clubmed/digital-oidc/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:40306:47)
      at Object.transform (file:///Volumes/Develop/clubmed/digital-oidc/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:35284:30)
      at loadAndTransform (file:///Volumes/Develop/clubmed/digital-oidc/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:39803:29)
```

**Comment by brillout** [comment]
That's quite unexpected. Are you using a Vite plugin that could be interfering with modules IDs?

**Comment by nbrdx** [comment]
Here are the plugins I use on the app
![image](https://user-images.githubusercontent.com/10615700/226882712-cb7cf8d0-0276-4821-9e0e-b2f2a6f6062f.png)
Maybe one of them is causing the problem ?

**Comment by brillout** [comment]
Maybe the eslint one. I'll need a minimal reproduction.

**Comment by nbrdx** [comment]
Worked fine after bumping vite@4 (previously vite@3)
