### ISSUE TITLE
You have following imports which are outdated:

### ISSUE THREAD

**Issue by rhildred** [brillout/vite-plugin-ssr#730]
### Description

My project worked last night (Eastern Time) with no errors or warnings.

My vite.config.js is 

import react from '@vitejs/plugin-react';
import mdx from '@mdx-js/rollup';
import ssr from 'vite-plugin-ssr/plugin';

export default {
  plugins: [
    react(),
    mdx(),
    ssr({
      prerender: true,
      includeAssetsImportedByServer: true,
    }),
  ],
  // We manually add a list of dependencies to be pre-bundled, in order to avoid a page reload at dev start which breaks vite-plugin-ssr's CI
  // (The 'react/jsx-runtime' entry is not needed in Vite 3 anymore.)
  optimizeDeps: { include: ['cross-fetch', 'react/jsx-runtime'] },
};

The whole project is at [diy-pwa/coming-soon](https://github.com/diy-pwa/coming-soon)

I tried changing `import ssr from 'vite-plugin-ssr/plugin';` to `import ssr from 'vite-plugin-ssr/server';`. This was how I read the error message.

I am a community college professor and I am really hoping to use this with my students tomorrow.

### Error Message + Error Stack

```shell
Error: [vite-plugin-ssr@0.4.100][Warning] You have following imports which are outdated:
  import { something } from 'vite-plugin-ssr'
Replace them with:
  import { something } from 'vite-plugin-ssr/server'
Or if `something` is a type:
  import type { something } from 'vite-plugin-ssr'
(Server exports now live at 'vite-plugin/server' while all types are now exported at 'vite-plugin-ssr'.)
    at assertWarning (file:///home/projects/node-bdiuay/node_modules/vite-plugin-ssr/dist/cjs/utils/assert.js:75:22)
    at Object.eval (file:///home/projects/node-bdiuay/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/index-deprecated.js:25:27)
    at Object.function (https://nodebdiuay-jvcc.w-credentialless.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:15:144744)
    at Module._compile (https://nodebdiuay-jvcc.w-credentialless.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:6:244076)
    at Module._extensions..js (https://nodebdiuay-jvcc.w-credentialless.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:6:244741)
    at Module.load (https://nodebdiuay-jvcc.w-credentialless.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:6:242766)
    at Module._load (https://nodebdiuay-jvcc.w-credentialless.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:6:240331)
    at _0x45be4e.executionFunctionOrLineOffset (https://nodebdiuay-jvcc.w-credentialless.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:6:1071537)
    at _0x45be4e._evaluate (https://nodebdiuay-jvcc.w-credentialless.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:15:307854)
    at _0x45be4e.evaluate (https://nodebdiuay-jvcc.w-credentialless.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:15:306934)
```

**Comment by brillout** [comment]
Follow the stack trace until you find the import triggering the warning.

Worst case: use `0.4.99` instead.

**Comment by diy-pwa** [comment]
You are right. My code wasn't in the stack trace, but I had an import in renderer/_default.page.server.jsx.
```
import { escapeInject } from 'vite-plugin-ssr';
```
which I had to change to 
```
import { escapeInject } from 'vite-plugin-ssr/server';
```
Thanks for putting me on the right track.

**Comment by brillout** [comment]
The error message has been improved in `0.4.102`. I recommend using that version for anyone struggling to get rid of the warning.
