### ISSUE TITLE
Error on modifying generated manifest.json

### ISSUE THREAD

**Issue by serajhqi** [brillout/vite-plugin-ssr#769]
### Description

Hi, 

To get PWA working (`vite-plugin-pwa`), I need to merge `public/manifest.json` to `dist/clinet/manifest.json` to make it work. Recently I updated to `vite-plugin-ssr` from `v0.4.53`, and it doesn't work anymore with the following message:

```
Error: [vite-plugin-ssr@0.4.111][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at /app/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/globalContext.js:101:28
    at Array.forEach (<anonymous>)
    at assertViteManifest (/app/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/globalContext.js:100:10)
    at initGlobalContext (/app/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/globalContext.js:40:9)
    at async renderPage (/app/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:24:9)
```

here is my `manifest.json`:

```json
{
    "version":"1",
    "name": "appName",
    "short_name": "appName",
    "manifest_version": 2,
    "description": "desc",
    "theme_color": "#ffffff",
    "background_color":"white",
    "start_url": "/",
    "id": "/",
    "scope": "/",
    "display": "standalone",
    "icons": [
      {
        "src": "android-chrome-192x192.png",
        "sizes": "192x192",
        "type": "image/png"
      },
      {
        "src": "android-chrome-512x512.png",
        "sizes": "512x512",
        "type": "image/png"
      }
    ],
    "app": {
      "launch": {
        "web_url": "/"
      },
      "background": {
        "scripts": [
          "chrome.js"
        ]
      },
      "permissions": [
        "unlimitedStorage",
        "notifications",
        "fullscreen"
      ]
    }
  }
```

This problem occurs even if I add a single property to `dist/client/manifest.json`

### Error Message + Error Stack

```shell
Error: [vite-plugin-ssr@0.4.111][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at /app/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/globalContext.js:101:28
    at Array.forEach (<anonymous>)
    at assertViteManifest (/app/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/globalContext.js:100:10)
    at initGlobalContext (/app/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/globalContext.js:40:9)
    at async renderPage (/app/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:24:9)
```

**Comment by brillout** [comment]
If you remove the assertion, does everything work then?

**Comment by serajhqi** [comment]
It should resolve the issue. Currently, I don't have access to the company's source code. I will inform you within 16 hours.

**Comment by brillout** [comment]
👍 No rush.

**Comment by serajhqi** [comment]
Hello, good day

I removed `assertViteManifest(clientManifest)` from `globalContext.js`. Now it works.

**Comment by brillout** [comment]
Released as `0.4.112`.

In case you think you can convince your employer: https://github.com/sponsors/brillout.

**Comment by serajhqi** [comment]
I appreciate your efforts 🙏 . And sure I will 🙂

By the way I updated the project, but the same problem still occurs. Am I missing something?

```
Error: [vite-plugin-ssr@0.4.112][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at /home/seraj/Projects/Safargam/WebClient/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/globalContext.js:109:28
    at Array.forEach (<anonymous>)
    at assertViteManifest (/home/seraj/Projects/Safargam/WebClient/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/globalContext.js:100:10)
    at initGlobalContext (/home/seraj/Projects/Safargam/WebClient/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/globalContext.js:40:9)
    at async renderPage (/home/seraj/Projects/Safargam/WebClient/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:24:9)
```

**Comment by brillout** [comment]
I see. Should be fixed with `vite-plugin-ssr@0.4.112-draft.48745` (until I release `vite-plugin-ssr@0.4.113` which may take a little while as I don't plan to do another release in the next coming days).

> I appreciate your efforts 🙏 . And sure I will 🙂

Thank you! Let me know how it goes, also if your employer says no 🙂.

**Comment by serajhqi** [comment]
Hello, Good day

To just put you in the picture. I tried to convince the manager, but he didn't go with it. But I will try to talk our boss whenever I could see him.

**Comment by brillout** [comment]
Thanks for reporting back! While it isn't easy, the general arguments are:
 1. Sponsoring makes the tool the company depends on more robust.
 2. No employee wants to work for a greedy company that isn't even able to show a little sign of appreciation.

But, yea, many managers don't appreciate these arguments and it's often a fight (even somtimes a power play) to get companies to sponsor.

Thanks for trying and let me know what your boss says 💚.
