### ISSUE TITLE
[react - prerender issue] vite-plugin-ssr + tanstack query

### ISSUE THREAD

**Issue by YannBirba** [brillout/vite-plugin-ssr#773]
### Description

# SSG issue with tanstack query

## Explanation

I was investigating how to implement tanstack query with vite-plugin-ssr with react, so I found an interesting repo on github, so I forked it. 

SSR is looking to work correctly in development as in production.
When you turn on "prerender" option in ssr plugin in vite config to switch to ssg rendering, the "npm run prod" command never ends and stuck just after the static rendering logs. All is working if I abort the command line and run "npm run server:prod" but ...

Then, I tried to run the build without prerender and then switch prerender option to true to finaly launch prerender only with "npx vite-plugin-ssr prerender" and I got the error.

The error appen every time I try to prerender a page with a tanstack-query data prefetching in it.

## Environnement:

I'm using wsl and pnpm with latest node version

- WSL version : 1.1.6.0
- Node.js : v19.8.1
- npm version : 9.5.1
- pnpm version : 8.1.1

## Repo

You can look at my fork here if it can help : https://github.com/YannBirba/vite-ssr-with-react-query

Maybe i'm missing something idk ...
Thank you for the amazing job with this plugin !
Hope I can make an example with tanstack-query for the plugin in the future.

### Error Message + Error Stack

```shell
$ pnpm vite-plugin-ssr prerender

vite-plugin-ssr v0.4.112 pre-rendering HTML...

/home/yann/dev/react/vite-ssr-with-react-query/node_modules/.pnpm/vite-plugin-ssr@0.4.112_vite@4.2.1/node_modules/vite-plugin-ssr/dist/cjs/node/cli/bin.js:43
    throw rejectValue;
    ^

Error: [vite-plugin-ssr@0.4.112][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust. Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): /renderer/_error.page.tsx
    at assertExportNames (/home/yann/dev/react/vite-ssr-with-react-query/node_modules/.pnpm/vite-plugin-ssr@0.4.112_vite@4.2.1/node_modules/vite-plugin-ssr/dist/cjs/node/prerender/runPrerender.js:127:24)
    at Array.forEach (<anonymous>)
    at runPrerender (/home/yann/dev/react/vite-ssr-with-react-query/node_modules/.pnpm/vite-plugin-ssr@0.4.112_vite@4.2.1/node_modules/vite-plugin-ssr/dist/cjs/node/prerender/runPrerender.js:47:32)
    at async CAC.<anonymous> (/home/yann/dev/react/vite-ssr-with-react-query/node_modules/.pnpm/vite-plugin-ssr@0.4.112_vite@4.2.1/node_modules/vite-plugin-ssr/dist/cjs/node/cli/bin.js:15:5)
```

**Comment by brillout** [comment]
I cannot reproduce `[Bug] You stumbled upon a bug in vite-plugin-ssr's source code.`. What are your exact reproduction steps?

**Comment by YannBirba** [comment]
You just need to build with prerender false in vite config and then only run the prerender script to throw the error.

**Comment by brillout** [comment]
I could reproduce the fact that `$ pnpm exec vite-plugin-ssr prerender` doesn't exit. But I suspect that some of your dependency is pushing something to the event loop that doesn't yield. I'd inspect why the event queue isn't emtpy after VPS has finished pre-rendering. (VPS's prerender script lives at `node_modules/vite-plugin-ssr/dist/cjs/node/prerender/runPrerender.js`.)

**Comment by brillout** [comment]
> You just need to build with prerender false in vite config and then only run the prerender script to throw the error.

I could reproduce indeed. Although I'm not sure what you expect `$ vite-plugin-ssr prerender` to do when `prerender` is `false`. Although the error message should be improved.

**Comment by brillout** [comment]
> Although the error message should be improved.

Done.
