### ISSUE TITLE
V1 Cannot Override Config via Convenience File

### ISSUE THREAD

**Issue by dajinchu** [brillout/vite-plugin-ssr#812]
### Description

Possibly I am misunderstanding V1 design, but it appears impossible to override default configs. Eg. if I have `pages/+onRenderHtml` then any other file like `pages/about/+onRenderHtml` will throw an error.

Reproduction:

https://github.com/brillout/vite-plugin-ssr/compare/main...dajinchu:vite-plugin-ssr:v1-renderer-bug

### Error Message + Error Stack

```shell
at resolveConfigElement (/workspaces/vite-plugin-ssr/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:215:32)
    at /workspaces/vite-plugin-ssr/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:135:35
    at Array.forEach (<anonymous>)
    at /workspaces/vite-plugin-ssr/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:134:63
    at Array.forEach (<anonymous>)
    at loadConfigData (/workspaces/vite-plugin-ssr/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:115:13)
    at async getVirtualFileImportPageConfigs (/workspaces/vite-plugin-ssr/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getVirtualFileImportPageConfigs.js:11:51)
    at async generateGlobImports (/workspaces/vite-plugin-ssr/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/getVirtualFileImportUserCode.js:149:3)
    at async getCode (/workspaces/vite-plugin-ssr/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/getVirtualFileImportUserCode.js:32:20)
    at async getVirtualFileImportUserCode (/workspaces/vite-plugin-ssr/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/getVirtualFileImportUserCode.js:19:18)
    at async Context.load (/workspaces/vite-plugin-ssr/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/index.js:46:30)
    at async Object.load (file:///workspaces/vite-plugin-ssr/node_modules/.pnpm/vite@4.0.3_@types+node@17.0.31/node_modules/vite/dist/node/chunks/dep-0bae2027.js:41453:32)
    at async loadAndTransform (file:///workspaces/vite-plugin-ssr/node_modules/.pnpm/vite@4.0.3_@types+node@17.0.31/node_modules/vite/dist/node/chunks/dep-0bae2027.js:39225:24)
```

**Comment by brillout** [comment]
That seems unexpected indeed. Let me have a look.

**Comment by brillout** [comment]
Let me know if you need the fix to be released.

**Comment by brillout** [comment]
Fix released in `0.4.117`.
