### ISSUE TITLE
Wrongly formatted path: ${path}

### ISSUE THREAD

**Issue by enri90** [brillout/vite-plugin-ssr#817]
### Description

After update 116 now i get this error
is there any configuration for node on path?
thx

### Error Message + Error Stack

```shell
/Users/enri/urql/node_modules/vite-plugin-ssr/dist/cjs/utils/filesystemPathHandling.js:18
    (0, assert_1.assert)(path && !path.includes(sepWin32), `Wrongly formatted path: ${path}`);
                        ^
Error: [vite-plugin-ssr@0.4.117][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust. Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): Wrongly formatted path: 
    at assertPosixPath (/Users/enri/urql/node_modules/vite-plugin-ssr/dist/cjs/utils/filesystemPathHandling.js:18:25)
    at toPosixPath (/Users/enri/urql/node_modules/vite-plugin-ssr/dist/cjs/utils/filesystemPathHandling.js:13:5)
    at getCodeFilePath (/Users/enri/urql/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:298:77)
    at resolveConfigElement (/Users/enri/urql/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:238:22)
    at /Users/enri/urql/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:134:35
    at Array.forEach (<anonymous>)
    at /Users/enri/urql/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:133:63
    at Array.forEach (<anonymous>)
    at loadConfigData (/Users/enri/urql/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:114:13)
    at async resolveConfig (/Users/enri/urql/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config/index.js:28:48)
```

**Comment by brillout** [comment]
Insert the following at line `298` of `node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js`:
```diff
    else {
        // TODO: remove
+       console.log(configName, pageConfigFilePath)
        const vitePath = getVitePathFromConfigValue((0, utils_1.toPosixPath)(configValue), pageConfigFilePath);
        codeFilePath = path_1.default.posix.join(userRootDir, vitePath);
        configValueFileExport = 'default';
    }
```
And report back the log result.

**Comment by enri90** [comment]
```typescript

title /pages/dashboard/users/+config.ts
description /pages/dashboard/users/+config.ts

/Users/enri/urql/node_modules/vite-plugin-ssr/dist/cjs/utils/filesystemPathHandling.js:18
    (0, assert_1.assert)(path && !path.includes(sepWin32), `Wrongly formatted path: ${path}`);
``` 

wow removed the +config.ts file in dashboard and now it works

**Comment by brillout** [comment]
What was the content of `/pages/dashboard/users/+config.ts`?

**Comment by enri90** [comment]
```typescript

export default {
  title: 'User List',
  description: ''
}

``` 

it was by title and description page

**Comment by enri90** [comment]
/renderer/+config.ts

```typescript
 meta: {
    title: {
      // The value of 'title' should only be loaded on the server
      env: 'server-only'
    },
    description: {
      env: 'server-only'
    },
    Layout: {
      env: 'server-and-client'
    },
    documentProps: {
      env: 'server-and-client'
    }
```

**Comment by enri90** [comment]
using the layout on the dashboard page
it doesn't inherit me urql client

if i move the component on page client urql work
Is it possible it's a bug?

```typescript
No client has been specified using urql's Provider. please create a client and add a Provider.
Error: No client has been specified using urql's Provider. please create a client and add a Provider.
    at useClient (/Users/enri/crm-vite/urql/node_modules/urql/src/context.ts:75:1)
    at Proxy.useQuery (/Users/enri/crm-vite/urql/node_modules/urql/src/hooks/useQuery.ts:214:1)
    at Module.useNotificationListQuery (notification.query.generated.ts:141:14)
    at DropdownNotifications (DropdownNotifications.tsx:44:38)
    at renderWithHooks (/Users/enri/crm-vite/urql/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5662:16)
```
