### ISSUE TITLE
Test Build vite

### ISSUE THREAD

**Issue by enri90** [brillout/vite-plugin-ssr#820]
### Description

run command 
vite build && cross-env NODE_ENV=production ts-node ./server/index.ts

```typescript
"ts-node": {
    "transpileOnly": true,
    "esm": true,
    "compilerOptions": {
      "moduleResolution": "Node16"
    }
  },
``` 

### Error Message + Error Stack

```shell
Error: [vite-plugin-ssr@0.4.117][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust. Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard
    at getManifestEntry (/Users/enri/Code/urql/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/getPageAssets/getManifestEntry.js:34:28)
    at /Users/enri/Code/urql/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/getPageAssets/retrieveAssetsProd.js:25:73
    at Array.forEach (<anonymous>)
    at retrieveAssetsProd (/Users/enri/Code/urql/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/getPageAssets/retrieveAssetsProd.js:11:24)
    at getPageAssets (/Users/enri/Code/urql/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/getPageAssets.js:26:65)
    at Object.__getPageAssets (/Users/enri/Code/urql/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/loadPageFilesServer.js:38:76)
    at getHtmlTags (/Users/enri/Code/urql/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/html/injectAssets/getHtmlTags.js:17:42)
    at injectHtmlTagsToString (/Users/enri/Code/urql/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/html/injectAssets.js:9:58)
    at renderDocumentHtml (/Users/enri/Code/urql/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/html/renderHtml.js:35:80)
    at async executeOnRenderHtmlHook (/Users/enri/Code/urql/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/executeOnRenderHtmlHook.js:116:24)
    at async renderPageContext (/Users/enri/Code/urql/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/renderPageContext.js:60:30)
    at async renderPageAttempt (/Users/enri/Code/urql/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:163:36)
    at async renderPage (/Users/enri/Code/urql/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:41:35)
    at async file:///Users/enri/Code/urql/server/index.ts:152:25
```

```typescript

  const [Widget, setWidget] = useState(() => Loading)
  useEffect(() => {
    setWidget(() => lazy(() => import('@/partials/dashboard/widgets/user/UsersAnalytics')))
  }, [])

  return (
    <Suspense fallback={<Loading />}>
      <Widget {...props} />
    </Suspense>
  )

```

**Comment by enri90** [comment]
```typescript
{
  "_chunk-0a45efda.js": {
    "file": "assets/chunks/chunk-0a45efda.js",
    "imports": [
      "_chunk-ba188e44.js"
    ]
  },
  "_chunk-17f65d35.js": {
    "file": "assets/chunks/chunk-17f65d35.js",
    "imports": [
      "_chunk-ba188e44.js"
    ]
  },
  "_chunk-184ade92.js": {
    "file": "assets/chunks/chunk-184ade92.js",
    "imports": [
      "_chunk-ba188e44.js"
    ]
  },
  "_chunk-18bb620d.js": {
    "file": "assets/chunks/chunk-18bb620d.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-8596e6b9.js"
    ]
  },
  "_chunk-1dd97119.js": {
    "file": "assets/chunks/chunk-1dd97119.js",
    "imports": [
      "_chunk-ba188e44.js"
    ]
  },
  "_chunk-2a02fee3.js": {
    "file": "assets/chunks/chunk-2a02fee3.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-17f65d35.js"
    ]
  },
  "_chunk-2cabcd5e.js": {
    "assets": [
      "assets/static/auth-image.b4a9973b.jpg",
      "assets/static/auth-decoration.a3f89aec.png"
    ],
    "file": "assets/chunks/chunk-2cabcd5e.js"
  },
  "_chunk-4d766f0d.js": {
    "file": "assets/chunks/chunk-4d766f0d.js",
    "imports": [
      "_chunk-ba188e44.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js"
    ]
  },
  "_chunk-53a63cfc.js": {
    "file": "assets/chunks/chunk-53a63cfc.js",
    "imports": [
      "_chunk-d3446c59.js",
      "_chunk-1dd97119.js",
      "_chunk-184ade92.js",
      "_chunk-ba188e44.js",
      "_chunk-17f65d35.js"
    ]
  },
  "_chunk-83a814e3.js": {
    "file": "assets/chunks/chunk-83a814e3.js",
    "imports": [
      "_chunk-ba188e44.js"
    ]
  },
  "_chunk-8596e6b9.js": {
    "file": "assets/chunks/chunk-8596e6b9.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-aea99bf9.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js"
    ]
  },
  "_chunk-aa3d7166.js": {
    "file": "assets/chunks/chunk-aa3d7166.js",
    "imports": [
      "_chunk-ba188e44.js"
    ]
  },
  "_chunk-aea99bf9.js": {
    "file": "assets/chunks/chunk-aea99bf9.js",
    "imports": [
      "_chunk-ba188e44.js"
    ]
  },
  "_chunk-b10798d2.js": {
    "file": "assets/chunks/chunk-b10798d2.js",
    "imports": [
      "_chunk-ba188e44.js"
    ]
  },
  "_chunk-ba188e44.js": {
    "assets": [
      "assets/static/loading.ade72bfe.svg"
    ],
    "css": [
      "assets/static/onPageTransitionEnd.741339ea.css"
    ],
    "file": "assets/chunks/chunk-ba188e44.js",
    "imports": [
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js"
    ]
  },
  "_chunk-bbdd996e.js": {
    "assets": [
      "assets/static/404-illustration.a20d59b6.svg"
    ],
    "file": "assets/chunks/chunk-bbdd996e.js"
  },
  "_chunk-c0928806.js": {
    "file": "assets/chunks/chunk-c0928806.js"
  },
  "_chunk-d3446c59.js": {
    "file": "assets/chunks/chunk-d3446c59.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-8596e6b9.js"
    ]
  },
  "_chunk-eed5ecf2.js": {
    "file": "assets/chunks/chunk-eed5ecf2.js",
    "imports": [
      "_chunk-ba188e44.js"
    ]
  },
  "_chunk-f6301419.js": {
    "dynamicImports": [
      "src/partials/dashboard/widgets/user/UsersAnalytics.tsx"
    ],
    "file": "assets/chunks/chunk-f6301419.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-8596e6b9.js",
      "_chunk-aea99bf9.js",
      "_chunk-f6e2fe3a.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-17f65d35.js"
    ],
    "isDynamicEntry": true
  },
  "_chunk-f6e2fe3a.js": {
    "file": "assets/chunks/chunk-f6e2fe3a.js",
    "imports": [
      "_chunk-18bb620d.js",
      "_chunk-ba188e44.js",
      "_chunk-17f65d35.js",
      "_chunk-b10798d2.js",
      "_chunk-1dd97119.js"
    ]
  },
  "_onPageTransitionEnd.css": {
    "file": "assets/static/onPageTransitionEnd.741339ea.css",
    "src": "_onPageTransitionEnd.css"
  },
  "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js": {
    "dynamicImports": [
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/index",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/_error",
      "_chunk-f6301419.js",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/login",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/privacy",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/register",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/reset-password",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/terms",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/authorized",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/faqs",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/users",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/calendar",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/register/verify",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/reset-password/verify",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/account",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/billing",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/crm",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/feedback",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/media",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/notifications",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/plugins",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/privacy",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/template",
      "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/users/@userId"
    ],
    "file": "assets/entry-client-routing.3df930dd.js",
    "isEntry": true,
    "src": "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js"
  },
  "src/images/404-illustration.svg": {
    "file": "assets/static/404-illustration.a20d59b6.svg",
    "src": "src/images/404-illustration.svg"
  },
  "src/images/auth-decoration.png": {
    "file": "assets/static/auth-decoration.a3f89aec.png",
    "src": "src/images/auth-decoration.png"
  },
  "src/images/auth-image.jpg": {
    "file": "assets/static/auth-image.b4a9973b.jpg",
    "src": "src/images/auth-image.jpg"
  },
  "src/images/icon-01.svg": {
    "file": "assets/static/icon-01.e89d7385.svg",
    "src": "src/images/icon-01.svg"
  },
  "src/images/loading.svg": {
    "file": "assets/static/loading.ade72bfe.svg",
    "src": "src/images/loading.svg"
  },
  "src/images/modal-image.jpg": {
    "file": "assets/static/modal-image.f36b2fb4.jpg",
    "src": "src/images/modal-image.jpg"
  },
  "src/partials/dashboard/widgets/user/UsersAnalytics.tsx": {
    "assets": [
      "assets/static/icon-01.e89d7385.svg"
    ],
    "file": "assets/src/partials/dashboard/widgets/user/UsersAnalytics.5d2e6f89.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-f6301419.js",
      "_chunk-8596e6b9.js",
      "_chunk-17f65d35.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-aea99bf9.js",
      "_chunk-f6e2fe3a.js",
      "_chunk-18bb620d.js",
      "_chunk-b10798d2.js",
      "_chunk-1dd97119.js"
    ],
    "isDynamicEntry": true,
    "src": "src/partials/dashboard/widgets/user/UsersAnalytics.tsx"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/_error": {
    "file": "assets/chunks/chunk-1d62521d.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-aea99bf9.js",
      "_chunk-bbdd996e.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/_error"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/authorized": {
    "file": "assets/chunks/chunk-173e98bf.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-bbdd996e.js",
      "_chunk-aea99bf9.js",
      "_chunk-8596e6b9.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/authorized"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/calendar": {
    "file": "assets/chunks/chunk-9ebbb0c5.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-8596e6b9.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-aea99bf9.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/calendar"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/faqs": {
    "file": "assets/chunks/chunk-b473ef3b.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-8596e6b9.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-aea99bf9.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/faqs"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/account": {
    "file": "assets/chunks/chunk-d397bfcc.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-184ade92.js",
      "_chunk-b10798d2.js",
      "_chunk-53a63cfc.js",
      "_chunk-17f65d35.js",
      "_chunk-8596e6b9.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-d3446c59.js",
      "_chunk-1dd97119.js",
      "_chunk-aea99bf9.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/account"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/billing": {
    "file": "assets/chunks/chunk-d0901e21.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-aa3d7166.js",
      "_chunk-8596e6b9.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-aea99bf9.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/billing"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/crm": {
    "file": "assets/chunks/chunk-fc695483.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-d3446c59.js",
      "_chunk-2a02fee3.js",
      "_chunk-83a814e3.js",
      "_chunk-8596e6b9.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-17f65d35.js",
      "_chunk-aea99bf9.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/crm"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/feedback": {
    "file": "assets/chunks/chunk-1ee19ef6.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-aa3d7166.js",
      "_chunk-8596e6b9.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-aea99bf9.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/feedback"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/media": {
    "assets": [
      "assets/static/modal-image.f36b2fb4.jpg"
    ],
    "file": "assets/chunks/chunk-306d7d14.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-18bb620d.js",
      "_chunk-eed5ecf2.js",
      "_chunk-17f65d35.js",
      "_chunk-83a814e3.js",
      "_chunk-8596e6b9.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-aea99bf9.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/media"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/notifications": {
    "file": "assets/chunks/chunk-8b0f121b.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-aa3d7166.js",
      "_chunk-8596e6b9.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-aea99bf9.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/notifications"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/plugins": {
    "file": "assets/chunks/chunk-9c4ab7ce.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-83a814e3.js",
      "_chunk-8596e6b9.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-aea99bf9.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/plugins"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/privacy": {
    "file": "assets/chunks/chunk-f974e877.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-83a814e3.js",
      "_chunk-8596e6b9.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-aea99bf9.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/privacy"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/template": {
    "file": "assets/chunks/chunk-613e389a.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-83a814e3.js",
      "_chunk-eed5ecf2.js",
      "_chunk-c0928806.js",
      "_chunk-2a02fee3.js",
      "_chunk-8596e6b9.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-17f65d35.js",
      "_chunk-aea99bf9.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/settings/template"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/users": {
    "file": "assets/chunks/chunk-16ef2b7c.js",
    "imports": [
      "_chunk-ba188e44.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-c0928806.js",
      "_chunk-f6e2fe3a.js",
      "_chunk-8596e6b9.js",
      "_chunk-17f65d35.js",
      "_chunk-b10798d2.js",
      "_chunk-18bb620d.js",
      "_chunk-1dd97119.js",
      "_chunk-aea99bf9.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/users"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/users/@userId": {
    "file": "assets/chunks/chunk-39ea4e92.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-184ade92.js",
      "_chunk-b10798d2.js",
      "_chunk-53a63cfc.js",
      "_chunk-17f65d35.js",
      "_chunk-8596e6b9.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-d3446c59.js",
      "_chunk-1dd97119.js",
      "_chunk-aea99bf9.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/dashboard/users/@userId"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/index": {
    "file": "assets/chunks/chunk-a33a4e47.js",
    "imports": [
      "_chunk-ba188e44.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/index"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/login": {
    "file": "assets/chunks/chunk-c5acc024.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-2cabcd5e.js",
      "_chunk-aea99bf9.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js",
      "_chunk-1dd97119.js",
      "_chunk-4d766f0d.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/login"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/privacy": {
    "file": "assets/chunks/chunk-55b4b314.js",
    "imports": [
      "_chunk-ba188e44.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/privacy"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/register": {
    "file": "assets/chunks/chunk-6b62c6ab.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-2cabcd5e.js",
      "_chunk-aea99bf9.js",
      "_chunk-4d766f0d.js",
      "_chunk-1dd97119.js",
      "_chunk-0a45efda.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/register"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/register/verify": {
    "file": "assets/chunks/chunk-29a012f7.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-2cabcd5e.js",
      "_chunk-aea99bf9.js",
      "_chunk-0a45efda.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/register/verify"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/reset-password": {
    "file": "assets/chunks/chunk-20051464.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-2cabcd5e.js",
      "_chunk-aea99bf9.js",
      "_chunk-184ade92.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/reset-password"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/reset-password/verify": {
    "file": "assets/chunks/chunk-b9589e62.js",
    "imports": [
      "_chunk-ba188e44.js",
      "_chunk-2cabcd5e.js",
      "_chunk-aea99bf9.js",
      "_chunk-1dd97119.js",
      "_chunk-184ade92.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/reset-password/verify"
  },
  "virtual:vite-plugin-ssr:importPageCode:client:/pages/terms": {
    "file": "assets/chunks/chunk-04b1a2d9.js",
    "imports": [
      "_chunk-ba188e44.js",
      "node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js"
    ],
    "isDynamicEntry": true,
    "src": "virtual:vite-plugin-ssr:importPageCode:client:/pages/terms"
  }
}
```

**Comment by brillout** [comment]
I think I know what's going. Let me write a tentative fix.

**Comment by brillout** [comment]
Replace `^0.4.117` with `0.4.117-draft.13525` (make sure you remove `^`) in your package.json then install your deps again.

**Comment by enri90** [comment]
how do i handle that situation process.env.NODE_ENV doesn't work

ssr: {
    noExternal: process.env.NODE_ENV === 'production' ? ['react-flatpickr', 'react-ssr-prepass'] : [] 
},

thx

**Comment by enri90** [comment]
yeahh work 0.4.117-draft.13525

THX!!

**Comment by enri90** [comment]
```typescript
failed to load config from /Users/enri/urql/vite.config.ts
error during build:
TypeError: Cannot read properties of undefined (reading 'PROD')
    at file:///Users/enri/urql/vite.config.ts.timestamp-1682433164360-acb7674601c32.mjs:141:33
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by brillout** [comment]
I'd use `command === 'build'` instead.

**Comment by enri90** [comment]
perfect thanks!
