### ISSUE TITLE
500 error during onBeforeRender on catch-all route

### ISSUE THREAD

**Issue by eagleera** [brillout/vite-plugin-ssr#845]
### Description

```
Error: [vite-plugin-ssr@0.4.120][Bug]:
    at createHttpResponseObject (/Users/daguilera/dev/personal/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/createHttpResponseObject.js:21:32)
    at renderPageContext (/Users/daguilera/dev/personal/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/renderPageContext.js:67:92)
    at renderPageAttempt (/Users/daguilera/dev/personal/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:163:36)
    at renderPage (/Users/daguilera/dev/personal/vite-ssr-project/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:41:35)
    at file:///Users/daguilera/dev/personal/vite-ssr-project/server/index.ts:34:29 
```

server/index.ts:34:29 is where it does:
```
const vite = await import('vite')
    const viteDevMiddleware = (
      await vite.createServer({
        root,
        server: { middlewareMode: true }
      })
    ).middlewares
```

I started the scaffolding with `npm init vite-plugin-ssr@latest`and tried to create a catch-all route with feching data

**Comment by brillout** [comment]
Thanks for the bug report. Can you publish the reproduction as a GitHub repository?

**Comment by brillout** [comment]
> Can you publish the reproduction as a GitHub repository?

Closing in the meantime. I'll re-open if I can get my hands on a reproduction.
