### ISSUE TITLE
Error: [vite-plugin-ssr@0.4.121][Wrong Usage] /pages/index/+config.ts sets the config onBeforeRender to a value with an invalid type `function` but it should be a `string` instead

### ISSUE THREAD

**Issue by harrytran998** [brillout/vite-plugin-ssr#848]
### Description

After upgrading to the latest version of VPS, I move `+onBeforeRender` to `+config` like the docs said(https://vite-plugin-ssr.com/onBeforeRender).

```
import { IPageConfig } from "#/types";

export default {
  async onBeforeRender(pageContext) {
    return {
      pageContext: {
        documentProps: {
          title: "Page Title",
          description:            "Page Description"
        }
      }
    };
  }
} satisfies IPageConfig;
```

But this will occur the issue like bellow.

```bash
 Error: [vite-plugin-ssr@0.4.121][Wrong Usage] /pages/index/+config.ts sets the config onBeforeRender to a value with an invalid type `function` but it should be a `string` instead  
at getCodeFilePath (/project/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:286:33) 
at resolveConfigElement (/project/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:239:22)
```

What do I miss something?

Besides, in the old VPS version, I defined `meta` in /rendere/+config.ts` like the current, I defined some extra config like code bellow, and I in `/some-page/`, I define each file with meta like `/some-page/+Layout.ts` or `/some-page/+Head.ts` --> Work correctly. 

```ts
meta: {
    Head: {
      env: "server-and-client"
    },
    Layout: {
      env: "server-and-client"
    },
	lang: {
		env: "server-only"
	}
```

But after upgrading VPS's latest version, I move all of the meta config before to only one `/some-page/+config.ts` --> Did'nt work 🥹. What do I miss something?

Thank you <3

**Comment by brillout** [comment]
See https://vite-plugin-ssr.com/config-code-splitting and in particular https://vite-plugin-ssr.com/config-code-splitting#rule.

FYI throwing a helpful error message isn't implement yet. But it's on the V1 design stable release to-do list which I'm currently working on. I'm leaving this ticket open to track progress.

>  Error: [vite-plugin-ssr@0.4.121][Wrong Usage] /pages/index/+config.ts sets the config onBeforeRender to a value with an invalid type `function` but it should be a `string` instead  

This error message is misleading and will be improved.
