### ISSUE TITLE
error when +Page file exist in booth renderer and pages folder

### ISSUE THREAD

**Issue by royalswe** [brillout/vite-plugin-ssr#858]
### Description

Error showed when +Page exist in renderer folder when pages folder exist.

error when starting dev server:
Error: [vite-plugin-ssr@0.4.122][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at C:\Users\royni\source\repos\JUNK\ssr-examples\examples\vue-router-v1\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData\filesystemRouting.js:109:36
    at Array.forEach (<anonymous>)
    at pickMostRelevantConfigValue (C:\Users\royni\source\repos\JUNK\ssr-examples\examples\vue-router-v1\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData\filesystemRouting.js:99:25)
    at resolveConfigElement (C:\Users\royni\source\repos\JUNK\ssr-examples\examples\vue-router-v1\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:215:72)
    at C:\Users\royni\source\repos\JUNK\ssr-examples\examples\vue-router-v1\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:93:35
    at Array.forEach (<anonymous>)
    at C:\Users\royni\source\repos\JUNK\ssr-examples\examples\vue-router-v1\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:92:63
    at Array.forEach (<anonymous>)
    at loadConfigData (C:\Users\royni\source\repos\JUNK\ssr-examples\examples\vue-router-v1\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:73:13)
    at async resolveConfig (C:\Users\royni\source\repos\JUNK\ssr-examples\examples\vue-router-v1\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\config\index.js:29:48)

**Comment by brillout** [comment]
Add the following before the line `109` of `C:\Users\royni\source\repos\JUNK\ssr-examples\examples\vue-router-v1\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData\filesystemRouting.js`:

```diff
            if ('plusValueFile' in candidate) {
+               console.log('candidate', candidate);
+               console.log('winnerNow', winnerNow);
                (0, utils_1.assert)('plusConfigFile' in winnerNow);
```

What are the logs?

**Comment by royalswe** [comment]
Here you go
```
candidate {
  plusValueFile: {
    configName: 'Page',
    pageId: '/pages',
    plusValueFilePath: '/pages/+Page.vue'
  }
}
winnerNow {
  plusValueFile: {
    configName: 'Page',
    pageId: '/renderer',
    plusValueFilePath: '/renderer/+Page.vue'
  }
}
```
I paste the same error again if I changed something else when recreating the error:

error when starting dev server:
Error: [vite-plugin-ssr@0.4.122][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at C:\Users\royni\source\repos\JUNK\vite-plugin-ssr_vue-server-v1\vite-plugin-ssr_vue-server-v1\vue-router-v1\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData\filesystemRouting.js:111:36
    at Array.forEach (<anonymous>)
    at pickMostRelevantConfigValue (C:\Users\royni\source\repos\JUNK\vite-plugin-ssr_vue-server-v1\vite-plugin-ssr_vue-server-v1\vue-router-v1\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData\filesystemRouting.js:99:25)
    at resolveConfigElement (C:\Users\royni\source\repos\JUNK\vite-plugin-ssr_vue-server-v1\vite-plugin-ssr_vue-server-v1\vue-router-v1\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:215:72)
    at C:\Users\royni\source\repos\JUNK\vite-plugin-ssr_vue-server-v1\vite-plugin-ssr_vue-server-v1\vue-router-v1\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:93:35   
    at Array.forEach (<anonymous>)
    at C:\Users\royni\source\repos\JUNK\vite-plugin-ssr_vue-server-v1\vite-plugin-ssr_vue-server-v1\vue-router-v1\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:92:63   
    at Array.forEach (<anonymous>)
    at loadConfigData (C:\Users\royni\source\repos\JUNK\vite-plugin-ssr_vue-server-v1\vite-plugin-ssr_vue-server-v1\vue-router-v1\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:73:13)
    at async resolveConfig (C:\Users\royni\source\repos\JUNK\vite-plugin-ssr_vue-server-v1\vite-plugin-ssr_vue-server-v1\vue-router-v1\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\config\index.js:29:48)

**Comment by brillout** [comment]
I see. Let me fix this.

**Comment by brillout** [comment]
Fix released in `0.4.123`.
