### ISSUE TITLE
Apparent Bug when using dayjs?

### ISSUE THREAD

**Issue by Techguy9078** [brillout/vite-plugin-ssr#879]
### Description

9:01:09 pm [vite] Error when evaluating SSR module /pages/bookclasses/index.page.tsx:
|- Error: [vite-plugin-ssr@0.4.123][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at get (C:\Users\Tyson\Desktop\Breakaway Personal Training\breakawayvite\node_modules\vite-plugin-ssr\dist\cjs\utils\require-shim.js:72:41)
    at eval (/pages/bookclasses/index.page.tsx:19:1)
    at async instantiateModule (file:///C:/Users/Tyson/Desktop/Breakaway%20Personal%20Training/breakawayvite/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:54360:9)

**Comment by brillout** [comment]
Thanks for the bug report, let me have a look at it.

**Comment by brillout** [comment]
What's your Node.js version?

Insert the following before line `72` of `C:\Users\Tyson\Desktop\Breakaway Personal Training\breakawayvite\node_modules\vite-plugin-ssr\dist\cjs\utils\require-shim.js`:

```diff
                    const caller = stack[1];
                    (0, assert_1.assert)(caller);
                    const fileName = caller.getFileName();
+                   console.log('err.stack', err.stack);
+                   console.log('fileName', fileName);
                    (0, assert_1.assert)(fileName);
```

What's the log output?

**Comment by Techguy9078** [comment]
This is the output:
```
err.stack [ CallSite {}, CallSite {}, CallSite {} ]
fileName undefined
```

**Comment by Techguy9078** [comment]
Figured out that I had to import it a different way for the errors to not occur it would have been how they were being handled.
```
import localizedFormat from "dayjs/plugin/localizedFormat";
dayjs.extend(localizedFormat);
```

**Comment by brillout** [comment]
Can you insert this:

```diff
                    // https://stackoverflow.com/questions/16697791/nodejs-get-filename-of-caller-function/66842927#66842927
+                   console.log('new Error().stack', new Error().stack);
                    const prepareStackTraceOrg = Error.prepareStackTrace;
                    Error.prepareStackTrace = (_, stack) => stack;
                    const err = new Error();
                    const stack = err.stack;
                    Error.prepareStackTrace = prepareStackTraceOrg;
                    const caller = stack[1];
                    (0, assert_1.assert)(caller);
                    const fileName = caller.getFileName();
                    (0, assert_1.assert)(fileName);
```

And report back.

Also, what's your Node.js version?

**Comment by Techguy9078** [comment]
The errors have now ceased by changing the var variables to import statements instead

**Comment by brillout** [comment]
That workarounds the bug but the bug itself is still there.

Can you reproduce and report back the new log?

**Comment by Techguy9078** [comment]
Output:
```
new Error().stack Error
    at get (C:\Users\Tyson\Desktop\Breakaway Personal Training\breakawayvite\node_modules\vite-plugin-ssr\dist\cjs\utils\require-shim.js:64:54)
    at assertRequireShim (C:\Users\Tyson\Desktop\Breakaway Personal Training\breakawayvite\node_modules\vite-plugin-ssr\dist\cjs\utils\require-shim.js:91:49)        
    at addRequireShim (C:\Users\Tyson\Desktop\Breakaway Personal Training\breakawayvite\node_modules\vite-plugin-ssr\dist\cjs\utils\require-shim.js:83:5)
    at Object.<anonymous> (C:\Users\Tyson\Desktop\Breakaway Personal Training\breakawayvite\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\index-common.js:44:28)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\Tyson\Desktop\Breakaway Personal Training\breakawayvite\node_modules\ts-node\src\index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
Server running at http://localhost:3000
new Error().stack Error
    at get (C:\Users\Tyson\Desktop\Breakaway Personal Training\breakawayvite\node_modules\vite-plugin-ssr\dist\cjs\utils\require-shim.js:64:54)
    at eval (/pages/bookclasses/index.page.tsx:19:23)
    at async instantiateModule (file:///C:/Users/Tyson/Desktop/Breakaway%20Personal%20Training/breakawayvite/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:54360:9)
```

**Comment by brillout** [comment]
Thanks, that's insightful.

I'll need a reproduction. Is importing dayjs all it takes to reproduce?

**Comment by Techguy9078** [comment]
Importing any of the custom modules will reproduce it:
```
var localizedFormat = require("dayjs/plugin/localizedFormat");
dayjs.extend(localizedFormat);
```

**Comment by brillout** [comment]
I could reproduce indeed. I'll fix this in a moment.

**Comment by brillout** [comment]
Fixed. In case you can convince your employer: https://github.com/sponsors/brillout.
