### ISSUE TITLE
onBeforeRoute errors with urlOriginal

### ISSUE THREAD

**Issue by royalswe** [brillout/vite-plugin-ssr#887]
### Description

Error occures when I added the +onBeforeRoute.js file from examples
```
function onBeforeRoute(pageContext: { urlOriginal: string }) {
  const { urlWithoutLocale, locale } = extractLocale(pageContext.urlOriginal);
  return {
    pageContext: {
      // We make `locale` available as `pageContext.locale`
      locale,
      // We overwrite `pageContext.urlOriginal`
      urlOriginal: urlWithoutLocale, // Here goes error
    },
  };
}
```

change name or remove urlOriginal key and no error occurs.

```
Error: [vite-plugin-ssr@0.4.123][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust. Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): `{"url":"se/om-sodra/var-historia"}`
    at parseUrl (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\utils\parseUrl.js:18:25)
    at hasSuffix (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage\handlePageContextRequestUrl.js:15:65)
    at handlePageContextRequestUrl (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage\handlePageContextRequestUrl.js:8:10)  
    at _urlHandler (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage.js:204:101)
    at getUrlParsed (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\addComputedUrlProps.js:44:17)
    at Object.urlPathnameGetter [as urlPathname] (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\addComputedUrlProps.js:50:26)
    at route (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\route\index.js:55:13)
    at async renderPageAttempt (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage.js:158:25)
    at async renderPage (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage.js:41:35)
    at async C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\shared\addSsrMiddleware.js:31:27
```

**Comment by brillout** [comment]
The URLs you return should be a valid URL. In your case, prerend `/` to the URLs and that should fix it.

I'll improve the error message.

**Comment by brillout** [comment]
> I'll improve the error message.

Done.

```
Error: [vite-plugin-ssr@0.4.123][Wrong Usage] The onBeforeRoute() hook defined by /renderer/+onBeforeRoute.js
returned `{ pageContext: { urlOriginal } }` but urlOriginal is 'about' and it should be '/about' instead (URL
pathnames should start with a leading slash)
```

Thanks for the bug report!
