### ISSUE TITLE
Error for multiple vue page entrypoints

### ISSUE THREAD

**Issue by felixhuttmann** [brillout/vite-plugin-ssr#890]
### Description

The error started to appear after I added in my vite.config.ts
```ts
export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        apple: resolve(__dirname, 'src/pages/apple/index.page.vue'),
        orange: resolve(__dirname, 'src/pages/orange/index.page.vue')
      }
    }
  },
```

In the error message below, `ple` is cutoff from `apple`.
```
Error: [vite-plugin-ssr@0.4.123][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust. Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): `{"url":"ple"}`
    at parseUrl (/home/path_to_repo/frontend/node_modules/vite-plugin-ssr/dist/cjs/utils/parseUrl.js:18:25)
    at getUrlParsed (/home/path_to_repo/frontend/node_modules/vite-plugin-ssr/dist/cjs/shared/addComputedUrlProps.js:47:33)
    at Object.urlPathnameGetter [as urlPathname] (/home/path_to_repo/frontend/node_modules/vite-plugin-ssr/dist/cjs/shared/addComputedUrlProps.js:50:26)
    at route (/home/path_to_repo/frontend/node_modules/vite-plugin-ssr/dist/cjs/shared/route/index.js:55:13)
    at async /home/path_to_repo/frontend/node_modules/vite-plugin-ssr/dist/cjs/node/prerender/runPrerender.js:390:29
```

**Comment by brillout** [comment]
Thanks for the bug report. I'll need a reproduction for that one. Can you publish one?

**Comment by felixhuttmann** [comment]
Thank you for the fast response.
A repro is here: https://github.com/felixhuttmann/vite-ssr-bug-repro
The repro is not very minimal (I just stripped proprietary info). Tell me if you need something more minimal.

**Comment by brillout** [comment]
```
Error: [vite-plugin-ssr@0.4.124][Wrong Usage] The onBeforeRoute() hook defined by
/src/renderer/_default.page.route.ts > `export { onBeforeRoute }` returned `{ pageContext: { urlOriginal } }`
but urlOriginal is 'foo-bar' and it should be '/foo-bar' instead (URL pathnames should start with a leading
slash)
```

(I will release the improved error message later today/tomorrow.)

Btw., if you can convince your employer: https://github.com/sponsors/brillout.
