### ISSUE TITLE
Error when upgrade Vue to 3.3.x

### ISSUE THREAD

**Issue by royalswe** [brillout/vite-plugin-ssr#891]
### Description

```
Error: [vite-plugin-ssr@0.4.123][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\assertPageConfigs.js:45:32
    at Array.forEach (<anonymous>)
    at assertConfigElements (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\assertPageConfigs.js:29:36)
    at C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\assertPageConfigs.js:19:9
    at Array.forEach (<anonymous>)
    at assertPageConfigs (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\assertPageConfigs.js:10:17)
    at parseGlobResults (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\parseGlobResults.js:32:47)
    at setPageFiles (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\setPageFiles.js:9:98)
    at globalObject.pageFilesGetter (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\setPageFiles.js:17:9)
    at async getPageFilesAll (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\setPageFiles.js:32:13)
    at async getRenderContext (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage\renderPageContext.js:144:73)
    at async renderPage (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage.js:25:25)
    at async C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\shared\addSsrMiddleware.js:31:27
Error: [vite-plugin-ssr@0.4.123][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\assertPageConfigs.js:45:32
    at Array.forEach (<anonymous>)
    at assertConfigElements (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\assertPageConfigs.js:29:36)
    at C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\assertPageConfigs.js:19:9
    at Array.forEach (<anonymous>)
    at assertPageConfigs (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\assertPageConfigs.js:10:17)
    at parseGlobResults (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\parseGlobResults.js:32:47)
    at setPageFiles (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\setPageFiles.js:9:98)
    at globalObject.pageFilesGetter (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\setPageFiles.js:17:9)
    at async getPageFilesAll (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\shared\getPageFiles\setPageFiles.js:32:13)
    at async getRenderContext (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage\renderPageContext.js:144:73)
    at async renderPage (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage.js:25:25)
    at async C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\shared\addSsrMiddleware.js:31:27
```

**Comment by royalswe** [comment]
I already use exact that version.
But I got it work now, I removed node_modules, lock file and cleaned the npm cache.
I also removed the vue-router that I do not use anymore.
