### ISSUE TITLE
Routes Defined in Extensions Fail

### ISSUE THREAD

**Issue by dajinchu** [brillout/vite-plugin-ssr#892]
### Description

Apologies if this is intentional behavior. 

As of `0.4.122`, It seems adding routes/page files as part of `extensions` in `vite.config.ts` fails. 

When running in dev mode, I get `No onRenderHtml() hook found` when visiting the page.

[Using the restack project for reproduction
](https://github.com/brillout/restack/compare/main...dajinchu:restack:extensions-page-repro)
full trace:
```
    at executeOnRenderHtmlHook (/workspaces/restack/node_modules/.pnpm/vite-plugin-ssr@0.4.123_vite@4.2.1/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/executeOnRenderHtmlHook.js:32:29)
    at renderPageContext (/workspaces/restack/node_modules/.pnpm/vite-plugin-ssr@0.4.123_vite@4.2.1/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/renderPageContext.js:60:90)
    at async renderPageAttempt (/workspaces/restack/node_modules/.pnpm/vite-plugin-ssr@0.4.123_vite@4.2.1/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:163:36)
    at async renderPage (/workspaces/restack/node_modules/.pnpm/vite-plugin-ssr@0.4.123_vite@4.2.1/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:41:35)
    at async /workspaces/restack/node_modules/.pnpm/vite-plugin-ssr@0.4.123_vite@4.2.1/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/shared/addSsrMiddleware.js:31:27
```

Works fine on `0.4.121`, though on all versions, running `vite build` fails with a different error.

```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: [vite-plugin-ssr@0.4.121][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at getEntryFromPageConfigData (/workspaces/restack/node_modules/.pnpm/vite-plugin-ssr@0.4.121_vite@4.2.1/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/buildConfig.js:134:24)
    at /workspaces/restack/node_modules/.pnpm/vite-plugin-ssr@0.4.121_vite@4.2.1/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/buildConfig.js:86:48
    at Array.forEach (<anonymous>)
    at analyzeClientEntries (/workspaces/restack/node_modules/.pnpm/vite-plugin-ssr@0.4.121_vite@4.2.1/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/buildConfig.js:77:21)
    at getEntries (/workspaces/restack/node_modules/.pnpm/vite-plugin-ssr@0.4.121_vite@4.2.1/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/buildConfig.js:52:69)
    at async configResolved (/workspaces/restack/node_modules/.pnpm/vite-plugin-ssr@0.4.121_vite@4.2.1/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/buildConfig.js:18:21)
    at async Promise.all (index 13)
    at async resolveConfig (file:///workspaces/restack/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.3/node_modules/vite/dist/node/chunks/dep-79892de8.js:63716:5)
    at async build (file:///workspaces/restack/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.3/node_modules/vite/dist/node/chunks/dep-79892de8.js:46088:20)
    at async main (file:///workspaces/restack/restack/dist/build-FWXHCI4U.js:9:3)
```

Its a weird use-case so I understand if this is not meant to be supported :)

**Comment by brillout** [comment]
What's your motivation for using `extensions`?
