### ISSUE TITLE
v1 regression after 0.4.124

### ISSUE THREAD

**Issue by vchirikov** [brillout/vite-plugin-ssr#897]
### Description

Hi, I have `/src/pages/renderer/+onBeforeRoute.ts` hook for i18n, but after after upgrading to 0.4.125 (after 0.4.124) I get:

```
Error: [vite-plugin-ssr@0.4.125][Wrong Usage] /src/pages/renderer/+onBeforeRoute.ts defines the config 'onBeforeRoute' which is global: create a global config (e.g. /pages/+config.js) and define 'onBeforeRoute' there instead
```

I tried to move this hook into `/src/pages/+config.ts` but after this I get the error:

```
Error: [vite-plugin-ssr@0.4.125][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at sortAfterInheritanceOrder (path\to\project\node_modules\.pnpm\vite-plugin-ssr@0.4.125_vite@4.3.8\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData\filesystemRouting.js:56:24)
    at path\to\project\node_modules\.pnpm\vite-plugin-ssr@0.4.125_vite@4.3.8\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:241:99
    at Array.sort (<anonymous>)
    at getInterfaceFilesRelevant (path\to\project\node_modules\.pnpm\vite-plugin-ssr@0.4.125_vite@4.3.8\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:241:10)
    at path\to\project\node_modules\.pnpm\vite-plugin-ssr@0.4.125_vite@4.3.8\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:152:40
    at Array.map (<anonymous>)
    at loadConfigData (path\to\project\node_modules\.pnpm\vite-plugin-ssr@0.4.125_vite@4.3.8\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:149:10)
    at async resolveConfig (path\to\project\node_modules\.pnpm\vite-plugin-ssr@0.4.125_vite@4.3.8\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\config\index.js:29:48)
```

Next I tried to move out `renderer` outside pages & define `/src/pages/+config.ts`:

```ts
import type { Config } from 'vite-plugin-ssr/types';

import onBeforeRoute from '../renderer/onBeforeRoute';

export default {
  onBeforeRoute,
} satisfies Config;
```

but got:

```
Error: [vite-plugin-ssr@0.4.125][Wrong Usage] /src/pages/+config.ts defines the config 'onBeforeRoute' which is global: create a global config (e.g. /pages/+config.js) and define 'onBeforeRoute' there instead
    at path\to\project\node_modules\.pnpm\vite-plugin-ssr@0.4.125_vite@4.3.8\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:216:45
    at Array.forEach (<anonymous>)
    at path\to\project\node_modules\.pnpm\vite-plugin-ssr@0.4.125_vite@4.3.8\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:212:50
    at Array.forEach (<anonymous>)
    at path\to\project\node_modules\.pnpm\vite-plugin-ssr@0.4.125_vite@4.3.8\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:211:24
    at Array.forEach (<anonymous>)
    at loadConfigData (path\to\project\node_modules\.pnpm\vite-plugin-ssr@0.4.125_vite@4.3.8\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:208:48)
    at async resolveConfig (path\to\project\node_modules\.pnpm\vite-plugin-ssr@0.4.125_vite@4.3.8\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\config\index.js:29:48)
```

Note that i18n-v1 example works as before with `+onBeforeRoute.ts` inside `renderer`:

https://github.com/brillout/vite-plugin-ssr/blob/main/examples/i18n-v1/renderer/+onBeforeRoute.js

**Comment by brillout** [comment]
The fixes are released in `0.4.125-draft.66209`. I'll release a non-draft version later today or tomorrow.

Btw. is working/freelancing for one of Vike's endeavours something you'd be up to?

**Comment by vchirikov** [comment]
> I'll release a non-draft version later today or tomorrow.

Nice, will test it later


> is working/freelancing for one of Vike's endeavours something you'd be up to?

Thanks, but I'm a devops / C# dev, so I'm a noob at frontend, although sometimes I do things in js world (like building libopus as wasm or audioworklet based player). I use Vike/solidjs in my free time in a pet-project to learn & get some modern frontend experience. I would take part in the development of an interesting service / application in my freetime, but not as a job

**Comment by brillout** [comment]
👍 I see.
