### ISSUE TITLE
[Bug] You stumbled upon a bug in vite-plugin-ssr's source code

### ISSUE THREAD

**Issue by SafaAlfulaij** [brillout/vite-plugin-ssr#898]
### Description

I get this error while starting the dev server, and so I'm reporting it :)
```

٧:٤٧:٤٩ ص [vite] Error when evaluating SSR module /node_modules/lodash/get.js:
|- Error: [vite-plugin-ssr@0.4.122][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at get (/home/safa/Documents/GitHub/my-project/node_modules/vite-plugin-ssr/dist/cjs/utils/require-shim.js:72:41)
    at eval (/node_modules/lodash/get.js:3:28)
    at instantiateModule (file:///home/safa/Documents/GitHub/my-project/node_modules/vite/dist/node/chunks/dep-33545781.js:54352:15)

٧:٤٧:٤٩ ص [vite] Error when evaluating SSR module /src/components/icon.jsx: failed to import "/node_modules/lodash/get.js"
|- Error: [vite-plugin-ssr@0.4.122][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at get (/home/safa/Documents/GitHub/my-project/node_modules/vite-plugin-ssr/dist/cjs/utils/require-shim.js:72:41)
    at eval (/node_modules/lodash/get.js:3:28)
    at instantiateModule (file:///home/safa/Documents/GitHub/my-project/node_modules/vite/dist/node/chunks/dep-33545781.js:54352:15)

٧:٤٧:٤٩ ص [vite] Error when evaluating SSR module /src/learn/components/utils.jsx: failed to import "/src/components/icon.jsx"
|- Error: [vite-plugin-ssr@0.4.122][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at get (/home/safa/Documents/GitHub/my-project/node_modules/vite-plugin-ssr/dist/cjs/utils/require-shim.js:72:41)
    at eval (/node_modules/lodash/get.js:3:28)
    at instantiateModule (file:///home/safa/Documents/GitHub/my-project/node_modules/vite/dist/node/chunks/dep-33545781.js:54352:15)

٧:٤٧:٤٩ ص [vite] Error when evaluating SSR module /src/components/utils.jsx: failed to import "/src/learn/components/utils.jsx"
|- Error: [vite-plugin-ssr@0.4.122][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at get (/home/safa/Documents/GitHub/my-project/node_modules/vite-plugin-ssr/dist/cjs/utils/require-shim.js:72:41)
    at eval (/node_modules/lodash/get.js:3:28)
    at instantiateModule (file:///home/safa/Documents/GitHub/my-project/node_modules/vite/dist/node/chunks/dep-33545781.js:54352:15)

٧:٤٧:٤٩ ص [vite] Error when evaluating SSR module /src/components/dialog.jsx: failed to import "/src/components/utils.jsx"
|- Error: [vite-plugin-ssr@0.4.122][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at get (/home/safa/Documents/GitHub/my-project/node_modules/vite-plugin-ssr/dist/cjs/utils/require-shim.js:72:41)
    at eval (/node_modules/lodash/get.js:3:28)
    at instantiateModule (file:///home/safa/Documents/GitHub/my-project/node_modules/vite/dist/node/chunks/dep-33545781.js:54352:15)

٧:٤٧:٤٩ ص [vite] Error when evaluating SSR module /src/contexts/generalDialog.jsx: failed to import "/src/components/dialog.jsx"
|- Error: [vite-plugin-ssr@0.4.122][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at get (/home/safa/Documents/GitHub/my-project/node_modules/vite-plugin-ssr/dist/cjs/utils/require-shim.js:72:41)
    at eval (/node_modules/lodash/get.js:3:28)
    at instantiateModule (file:///home/safa/Documents/GitHub/my-project/node_modules/vite/dist/node/chunks/dep-33545781.js:54352:15)

٧:٤٧:٤٩ ص [vite] Error when evaluating SSR module /src/renderer/_default.page.server.jsx: failed to import "/src/contexts/generalDialog.jsx"
|- Error: [vite-plugin-ssr@0.4.122][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at get (/home/safa/Documents/GitHub/my-project/node_modules/vite-plugin-ssr/dist/cjs/utils/require-shim.js:72:41)
    at eval (/node_modules/lodash/get.js:3:28)
    at instantiateModule (file:///home/safa/Documents/GitHub/my-project/node_modules/vite/dist/node/chunks/dep-33545781.js:54352:15)

٧:٤٧:٤٩ ص [vite] Error when evaluating SSR module /src/app.jsx: failed to import "/src/contexts/generalDialog.jsx"
|- Error: [vite-plugin-ssr@0.4.122][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at get (/home/safa/Documents/GitHub/my-project/node_modules/vite-plugin-ssr/dist/cjs/utils/require-shim.js:72:41)
    at eval (/node_modules/lodash/get.js:3:28)
    at instantiateModule (file:///home/safa/Documents/GitHub/my-project/node_modules/vite/dist/node/chunks/dep-33545781.js:54352:15)

٧:٤٧:٤٩ ص [vite] Error when evaluating SSR module /src/pages/all.page.jsx: failed to import "/src/app.jsx"
|- Error: [vite-plugin-ssr@0.4.122][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at get (/home/safa/Documents/GitHub/my-project/node_modules/vite-plugin-ssr/dist/cjs/utils/require-shim.js:72:41)
    at eval (/node_modules/lodash/get.js:3:28)
    at instantiateModule (file:///home/safa/Documents/GitHub/my-project/node_modules/vite/dist/node/chunks/dep-33545781.js:54352:15)

```

**Comment by brillout** [comment]
Can you try with the latest version? A fix related to to your issue has been released (see https://github.com/brillout/vite-plugin-ssr/blob/main/CHANGELOG.md#04124-2023-05-18).
