### ISSUE TITLE
Error when create +Layout file

### ISSUE THREAD

**Issue by royalswe** [brillout/vite-plugin-ssr#909]
### Description

```
16:14:02 [vite] page reload src/pages/index/@slug/+Layout.vue
Error: [vite-plugin-ssr@0.4.126][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust. Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): Layout
    at C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:160:32
    at Array.map (<anonymous>)
    at C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:153:72
    at Array.map (<anonymous>)
    at loadConfigData (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getConfigData.js:149:10)      
    at async getVirtualFileImportPageConfigs (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\v1-design\getVirtualFileImportPageConfigs.js:7:67)
    at async generateGlobImports (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\getVirtualFileImportUserCode.js:149:3)
    at async getCode (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\getVirtualFileImportUserCode.js:32:20)   
    at async getVirtualFileImportUserCode (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\getVirtualFileImportUserCode.js:19:18)
    at async Context.load (C:\Users\royni\source\repos\Sodra.Common.EpiServer.Website\Sodra.EK.WebSite.Web\WebUI\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\plugins\importUserCode\index.js:46:30)
    at async Object.load (file:///C:/Users/royni/source/repos/Sodra.Common.EpiServer.Website/Sodra.EK.WebSite.Web/WebUI/node_modules/vite/dist/node/chunks/dep-1f986b87.js:42892:32)
    at async loadAndTransform (file:///C:/Users/royni/source/repos/Sodra.Common.EpiServer.Website/Sodra.EK.WebSite.Web/WebUI/node_modules/vite/dist/node/chunks/dep-1f986b87.js:53318:24)

```

**Comment by brillout** [comment]
Released in `0.4.127`. (Also includes the fix for the previous error you opened.)
