### ISSUE TITLE
Bug at `createHttpResponseObject`

### ISSUE THREAD

**Issue by zyxkad** [brillout/vite-plugin-ssr#912]
### Description

```
Error: [vite-plugin-ssr@0.4.126][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at createHttpResponseObject (/Users/ckpn/Mine/projects/golang/src/github.com/kmcsr/PluginWebPoint/vue-project/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/createHttpResponseObject.js:21:32)
    at renderPageContext (/Users/ckpn/Mine/projects/golang/src/github.com/kmcsr/PluginWebPoint/vue-project/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage/renderPageContext.js:67:92)
    at async renderPageAttempt (/Users/ckpn/Mine/projects/golang/src/github.com/kmcsr/PluginWebPoint/vue-project/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:163:36)
    at async renderPage (/Users/ckpn/Mine/projects/golang/src/github.com/kmcsr/PluginWebPoint/vue-project/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:41:35)
    at async /Users/ckpn/Mine/projects/golang/src/github.com/kmcsr/PluginWebPoint/vue-project/server/index.js:36:25
```

`pages/all.page.server.jar`
```javascript

import { renderToNodeStream } from '@vue/server-renderer'
import { escapeInject } from 'vite-plugin-ssr/server'
import { createApp } from './app'

export const passToClient = ['pageProps', 'documentProps']

export async function render(pageContext){
	const { app, router } = await createApp(pageContext)

	router.push(pageContext.urlPathname)
	await router.isReady()
	const is404 = router.currentRoute.value.meta && router.currentRoute.value.meta.is404
	console.log('is404:', is404)

	const stream = await renderToNodeStream(app)

	var title = router.currentRoute.value.meta && router.currentRoute.value.meta.title
	if(typeof title === 'function'){
		title = title(router.currentRoute.value)
	}
	if(title){
		title += ' - '
	}else{
		title = ''
	}

	const documentHtml = escapeInject`<!DOCTYPE html>
		<html>
			<head>
				<title>${title}MCDReforged Plugin List</title>
				<meta charset="UTF-8">
				<link rel="icon" href="/assets/favicon.ico">
				<meta name="keywords" content="mcdr,mcdreforged,minecraft,plugin,api">
				<meta name="description" content="An MCDReforged plugin list access point">
				<meta name="viewport" content="width=device-width, initial-scale=1.0">
				<link rel="stylesheet" type="text/css" href="/assets/main.css">
			</head>
			<body>
				<div id="app">${stream}</div>
			</body>
		</html>
	`

	console.log('returned')

	return {
		documentHtml,
		pageContext: {
			enableEagerStreaming: true,
			is404: is404,
		},
	}
}
```

**Comment by zyxkad** [comment]
Reopen issue #845

**Comment by zyxkad** [comment]
Does is seems like MacOS issue? Anyway why there are none error information have showed. It just suddenly appeared, let me try to reset before the error occur

**Comment by zyxkad** [comment]
Yes I know what caused the issue now. I cannot pass the `is404` key to the `pageContext` in the return value

**Comment by zyxkad** [comment]
I'll leave this issue open, because I think you should give us the error information, not just let us guessing

**Comment by brillout** [comment]
You guessed right: you're not supposed to alter `is404`. Use a Route Function instead.

And, yes, the error message should be improved.

**Comment by brillout** [comment]
> I agree, the error message should be improved.

Fix released in `0.4.129`.

**Comment by brillout** [comment]
Btw. in case you can convince your employer: https://github.com/sponsors/brillout.

**Comment by zyxkad** [comment]
> Use `throw RenderErrorPage({ pageContext: { is404 }})` instead.

It's a good idea, but I'm using vue router. I only want to the express server return a 404 statue code, not a new error page

> Btw. in case you can convince your employer: https://github.com/sponsors/brillout.

Sorry I'm a student, I did my projects just because I am interesting on them (and they are all under GPL). I don't have extra money to donate. :(
But I will support you by give you a star :)

**Comment by brillout** [comment]
You can still use `throw RenderErrorPage()`. You can in fact make your current code work by replacing the `is404` part wih `throw RenderErrorPage()`.

Thanks for the star 😀.

FYI https://vite-plugin-ssr.com/vue-router-and-react-router. Bottom line being:

> If you want a feature provided by Vue Router or React Router that vite-plugin-ssr is missing, then open a new feature request.
