### ISSUE TITLE
Web components cause vite-ssr to collapse into a black hole

### ISSUE THREAD

**Issue by NinekoTheCat** [brillout/vite-plugin-ssr#923]
### Description

```shell
 `{"manifestKeys":["_chunk-9768c87f.js","node_modules/vite-plugin-ssr/dist/esm/client/entry.js","node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js","src/_default.page.client.ts"],"id":"/pages/index/index.page.server.ts?extractAssets&lang.ts"}`
    at getManifestEntry (C:\Users\cnots\Desktop\igag\server_division_2\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage\getPageAssets\getManifestEntry.js:42:28)
    at C:\Users\cnots\Desktop\igag\server_division_2\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage\getPageAssets\retrieveAssetsProd.js:25:73
    at Array.forEach (<anonymous>)
    at retrieveAssetsProd (C:\Users\cnots\Desktop\igag\server_division_2\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage\getPageAssets\retrieveAssetsProd.js:11:24)
    at getPageAssets (C:\Users\cnots\Desktop\igag\server_division_2\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage\getPageAssets.js:26:65)
    at Object.__getPageAssets (C:\Users\cnots\Desktop\igag\server_division_2\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage\loadPageFilesServer.js:38:76)
    at getHtmlTags (C:\Users\cnots\Desktop\igag\server_division_2\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\html\injectAssets\getHtmlTags.js:17:42)
    at injectHtmlTagsToString (C:\Users\cnots\Desktop\igag\server_division_2\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\html\injectAssets.js:9:58)
    at renderDocumentHtml (C:\Users\cnots\Desktop\igag\server_division_2\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\html\renderHtml.js:21:70)
    at executeOnRenderHtmlHook (C:\Users\cnots\Desktop\igag\server_division_2\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage\executeOnRenderHtmlHook.js:33:66)
    at async renderPageContext (C:\Users\cnots\Desktop\igag\server_division_2\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage\renderPageContext.js:60:30)
    at async renderPageAttempt (C:\Users\cnots\Desktop\igag\server_division_2\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage.js:163:36)
    at async renderPage (C:\Users\cnots\Desktop\igag\server_division_2\node_modules\vite-plugin-ssr\dist\cjs\node\runtime\renderPage.js:41:35)
    at async C:\Users\cnots\Desktop\igag\server_division_2\node_modules\vite-plugin-ssr\dist\cjs\node\plugin\shared\addSsrMiddleware.js:31:27
    ```

**Comment by brillout** [comment]
I'll need a reproduction.

**Comment by NinekoTheCat** [comment]
@brillout the project itself is pretty minimal so could I send it?

**Comment by brillout** [comment]
Yes, upload it to GitHub.

**Comment by brillout** [comment]
@NinekoTheCat Try `0.4.131` and let me know if it works.
