### ISSUE TITLE
"You stumbled upon a bug in vite-plugin-ssr's source code"

### ISSUE THREAD

**Issue by crummy** [brillout/vite-plugin-ssr#945]
### Description

```
error when starting dev server:
Error: [vite-plugin-ssr@0.4.131][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at /Users/crummy/code/earth/earth_dev/web/resources/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/replaceImportStatements.js:45:32
    at Array.forEach (<anonymous>)
    at /Users/crummy/code/earth/earth_dev/web/resources/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/replaceImportStatements.js:44:25
    at Array.forEach (<anonymous>)
    at replaceImportStatements (/Users/crummy/code/earth/earth_dev/web/resources/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/replaceImportStatements.js:17:13)
    at transpileAndLoadFile (/Users/crummy/code/earth/earth_dev/web/resources/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/transpileAndLoadFile.js:27:75)
    at async loadConfigFile (/Users/crummy/code/earth/earth_dev/web/resources/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:631:29)
    at async /Users/crummy/code/earth/earth_dev/web/resources/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:68:48
    at async Promise.all (index 5)
    at async loadInterfaceFiles (/Users/crummy/code/earth/earth_dev/web/resources/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:63:5)
    at async loadConfigData (/Users/crummy/code/earth/earth_dev/web/resources/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:147:40)
    at async resolveConfig (/Users/crummy/code/earth/earth_dev/web/resources/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/config/index.js:29:48)
```

Happy to provide whatever code you need.

**Comment by brillout** [comment]
In this file:

```
/Users/crummy/code/earth/earth_dev/web/resources/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/replaceImportStatements.js
```

Before line `45`, insert this:

```diff
        node.specifiers.forEach((specifier) => {
+           console.log('importStatementCode', importStatementCode);
+           console.log('specifier', specifier);
            (0, utils_1.assert)(specifier.type === 'ImportSpecifier' || specifier.type === 'ImportDefaultSpecifier');
```

What's the log output?

Thanks for the bug report.

**Comment by crummy** [comment]
```
importStatementCode import * as React from "react";
specifier Node {
  type: 'ImportNamespaceSpecifier',
  start: 7,
  end: 17,
  local: Node { type: 'Identifier', start: 12, end: 17, name: 'React' }
}
```

**Comment by brillout** [comment]
Fixed.

> Do you suggest just returning a string here?

See https://vite-plugin-ssr.com/header-file.

Let me know if something isn't clear (very much possible since this documentation is new).
