### ISSUE TITLE
Exception when running in production (not in dev) in renderPage.js

### ISSUE THREAD

**Issue by mcg1103** [brillout/vite-plugin-ssr#963]
### Description

I get this error when running using fastify as the server in production mode.  Not getting this when running with 'npx vite preview'  or just npx vite. or 

This is my call to renderPage:

`const pageContextInit = {
			urlOriginal: req.url,
			redirectTo: undefined
		}
		const pageContext = await renderPage(pageContextInit)`

in renderPage.js: 

async function renderPage(pageContextInit) {
    (0, assertArguments_1.assertArguments)(...arguments);
    (0, utils_1.assert)((0, utils_1.hasProp)(pageContextInit, 'urlOriginal', 'string'));
    // (0, utils_1.assertServerEnv)();  ------- this is the line that is causing the exception.  If I remove do not get exception. works as expected.
    let renderContext;
    try {
        await (0, globalContext_1.initGlobalContext)();
        renderContext = await (0, renderPageContext_1.getRenderContext)();
    }

`CAUGHT AN ERROR Error: [vite-plugin-ssr@0.4.131][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at assertServerEnv (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/utils/assertIsVitePluginCode.js:37:29)
    at renderPage (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:21:33)
    at Object.<anonymous> (/home/orderpt/work/webg3/otwebg3/src/ts/server/index.ts:61:39)
    at preHandlerCallback (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/handleRequest.js:128:37)
    at preValidationCallback (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/handleRequest.js:112:5)
    at handler (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/handleRequest.js:76:7)
    at handleRequest (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/l
[index.ts.txt](https://github.com/brillout/vite-plugin-ssr/files/11786407/index.ts.txt)
[index.ts.txt](https://github.com/brillout/vite-plugin-ssr/files/11786411/index.ts.txt)
ib/handleRequest.js:24:5)
    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:554:7)
    at Object.preParsing (/home/orderpt/work/webg3/otwebg3/node_modules/@fastify/compress/index.js:299:14)
    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:561:16)
    at preParsingHookRunner (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:584:3)
    at runPreParsing (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:535:5)
    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:173:7)
    at Object.onRequest (/home/orderpt/work/webg3/otwebg3/node_modules/@fastify/compress/index.js:205:5)
    at hookIterator (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:251:10)
    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:179:16)
    at Object.runMiddie (/home/orderpt/work/webg3/otwebg3/node_modules/@fastify/middie/index.js:44:7)
    at hookIterator (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:251:10)
    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:179:16)
    at hookRunner (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:201:3)
    at Object.routeHandler [as handler] (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:476:7)
    at Router.callHandler (/home/orderpt/work/webg3/otwebg3/node_modules/find-my-way/index.js:393:14)
    at Router.lookup (/home/orderpt/work/webg3/otwebg3/node_modules/find-my-way/index.js:371:17)
    at Server.preRouting (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/fastify.js:792:14)
    at Server.emit (node:events:513:28)
    at Server.emit (node:domain:489:12)
    at parserOnIncoming (node:_http_server:1072:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
  [stack]: "Error: [vite-plugin-ssr@0.4.131][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.\n" +
    '    at assertServerEnv (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/utils/assertIsVitePluginCode.js:37:29)\n' +
    '    at renderPage (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:21:33)\n' +
    '    at Object.<anonymous> (/home/orderpt/work/webg3/otwebg3/src/ts/server/index.ts:61:39)\n' +
    '    at preHandlerCallback (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/handleRequest.js:128:37)\n' +
    '    at preValidationCallback (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/handleRequest.js:112:5)\n' +
    '    at handler (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/handleRequest.js:76:7)\n' +
    '    at handleRequest (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/handleRequest.js:24:5)\n' +
    '    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:554:7)\n' +
    '    at Object.preParsing (/home/orderpt/work/webg3/otwebg3/node_modules/@fastify/compress/index.js:299:14)\n' +
    '    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:561:16)\n' +
    '    at preParsingHookRunner (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:584:3)\n' +
    '    at runPreParsing (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:535:5)\n' +
    '    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:173:7)\n' +
    '    at Object.onRequest (/home/orderpt/work/webg3/otwebg3/node_modules/@fastify/compress/index.js:205:5)\n' +
    '    at hookIterator (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:251:10)\n' +
    '    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:179:16)\n' +
    '    at Object.runMiddie (/home/orderpt/work/webg3/otwebg3/node_modules/@fastify/middie/index.js:44:7)\n' +
    '    at hookIterator (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:251:10)\n' +
    '    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:179:16)\n' +
    '    at hookRunner (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:201:3)\n' +
    '    at Object.routeHandler [as handler] (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:476:7)\n' +
    '    at Router.callHandler (/home/orderpt/work/webg3/otwebg3/node_modules/find-my-way/index.js:393:14)\n' +
    '    at Router.lookup (/home/orderpt/work/webg3/otwebg3/node_modules/find-my-way/index.js:371:17)\n' +
    '    at Server.preRouting (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/fastify.js:792:14)\n' +
    '    at Server.emit (node:events:513:28)\n' +
    '    at Server.emit (node:domain:489:12)\n' +
    '    at parserOnIncoming (node:_http_server:1072:12)\n' +
    '    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)',
  [message]: "[vite-plugin-ssr@0.4.131][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust."
`

**Comment by mcg1103** [comment]
The stack trace you asked me to add fires on startup. 

The other subsequent stack trace is called when rendering the page (a try/catch block).

I was not getting this error prior to upgrading vite package from 4.0.3 to 4.3.9 and vite-plugin-ssr from 0.4.71 to 0.4.131

Thanks,
-Mark


`assertIsVitePluginCode() stack trace Error
    at assertIsVitePluginCode (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/utils/assertIsVitePluginCode.js:13:54)
    at Object.<anonymous> (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/utils.js:20:53)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .js] (/home/orderpt/.nvm/versions/node/v18.15.0/lib/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/index.js:5:17)
assertIsVitePluginCode() stack trace Error
    at assertIsVitePluginCode (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/utils/assertIsVitePluginCode.js:13:54)
    at Object.<anonymous> (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/utils/getFilePathAbsolute.js:12:53)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .js] (/home/orderpt/.nvm/versions/node/v18.15.0/lib/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/utils.js:25:14)
assertIsVitePluginCode() stack trace Error
    at assertIsVitePluginCode (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/utils/assertIsVitePluginCode.js:13:54)
    at Object.<anonymous> (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/transpileAndLoadFile.js:15:36)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .js] (/home/orderpt/.nvm/versions/node/v18.15.0/lib/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:15:32)
assertIsVitePluginCode() stack trace Error
    at assertIsVitePluginCode (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/utils/assertIsVitePluginCode.js:13:54)
    at Object.<anonymous> (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importUserCode/v1-design/getConfigData.js:17:36)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .js] (/home/orderpt/.nvm/versions/node/v18.15.0/lib/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/buildConfig.js:6:25)
starting fastify
set the host and port to listen on in vite.config.ts
Server running at http://localhost:3000

PAGE VIEW '/'
CAUGHT AN ERROR Error: [vite-plugin-ssr@0.4.131][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at assertServerEnv (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/utils/assertIsVitePluginCode.js:38:29)
    at renderPage (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:21:33)
    at Object.<anonymous> (/home/orderpt/work/webg3/otwebg3/src/ts/server/index.ts:61:39)
    at preHandlerCallback (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/handleRequest.js:128:37)
    at preValidationCallback (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/handleRequest.js:112:5)
    at handler (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/handleRequest.js:76:7)
    at handleRequest (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/handleRequest.js:24:5)
    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:554:7)
    at Object.preParsing (/home/orderpt/work/webg3/otwebg3/node_modules/@fastify/compress/index.js:299:14)
    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:561:16)
    at preParsingHookRunner (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:584:3)
    at runPreParsing (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:535:5)
    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:173:7)
    at Object.onRequest (/home/orderpt/work/webg3/otwebg3/node_modules/@fastify/compress/index.js:205:5)
    at hookIterator (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:251:10)
    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:179:16)
    at Object.runMiddie (/home/orderpt/work/webg3/otwebg3/node_modules/@fastify/middie/index.js:44:7)
    at hookIterator (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:251:10)
    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:179:16)
    at hookRunner (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:201:3)
    at Object.routeHandler [as handler] (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:476:7)
    at Router.callHandler (/home/orderpt/work/webg3/otwebg3/node_modules/find-my-way/index.js:393:14)
    at Router.lookup (/home/orderpt/work/webg3/otwebg3/node_modules/find-my-way/index.js:371:17)
    at Server.preRouting (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/fastify.js:792:14)
    at Server.emit (node:events:513:28)
    at Server.emit (node:domain:489:12)
    at parserOnIncoming (node:_http_server:1072:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
  [stack]: "Error: [vite-plugin-ssr@0.4.131][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.\n" +
    '    at assertServerEnv (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/utils/assertIsVitePluginCode.js:38:29)\n' +
    '    at renderPage (/home/orderpt/work/webg3/otwebg3/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:21:33)\n' +
    '    at Object.<anonymous> (/home/orderpt/work/webg3/otwebg3/src/ts/server/index.ts:61:39)\n' +
    '    at preHandlerCallback (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/handleRequest.js:128:37)\n' +
    '    at preValidationCallback (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/handleRequest.js:112:5)\n' +
    '    at handler (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/handleRequest.js:76:7)\n' +
    '    at handleRequest (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/handleRequest.js:24:5)\n' +
    '    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:554:7)\n' +
    '    at Object.preParsing (/home/orderpt/work/webg3/otwebg3/node_modules/@fastify/compress/index.js:299:14)\n' +
    '    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:561:16)\n' +
    '    at preParsingHookRunner (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:584:3)\n' +
    '    at runPreParsing (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:535:5)\n' +
    '    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:173:7)\n' +
    '    at Object.onRequest (/home/orderpt/work/webg3/otwebg3/node_modules/@fastify/compress/index.js:205:5)\n' +
    '    at hookIterator (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:251:10)\n' +
    '    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:179:16)\n' +
    '    at Object.runMiddie (/home/orderpt/work/webg3/otwebg3/node_modules/@fastify/middie/index.js:44:7)\n' +
    '    at hookIterator (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:251:10)\n' +
    '    at next (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:179:16)\n' +
    '    at hookRunner (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/hooks.js:201:3)\n' +
    '    at Object.routeHandler [as handler] (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/lib/route.js:476:7)\n' +
    '    at Router.callHandler (/home/orderpt/work/webg3/otwebg3/node_modules/find-my-way/index.js:393:14)\n' +
    '    at Router.lookup (/home/orderpt/work/webg3/otwebg3/node_modules/find-my-way/index.js:371:17)\n' +
    '    at Server.preRouting (/home/orderpt/work/webg3/otwebg3/node_modules/fastify/fastify.js:792:14)\n' +
    '    at Server.emit (node:events:513:28)\n' +
    '    at Server.emit (node:domain:489:12)\n' +
    '    at parserOnIncoming (node:_http_server:1072:12)\n' +
    '    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)',
  [message]: "[vite-plugin-ssr@0.4.131][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust."
}
e.Message "[vite-plugin-ssr@0.4.131][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust."

`

**Comment by brillout** [comment]
VPS's Vite plugin is being loaded in your production server which shouldn't happen (see https://vite-plugin-ssr.com/renderPage). Any ideas why? You're the only one having that issue, so it's probably a setup problem on your side.

**Comment by mcg1103** [comment]
Thanks!
It was a setup issue on my part.   
import type { PageContextBuiltIn } from 'vite-plugin-ssr'
import type { PageContextBuiltInClient } from 'vite-plugin-ssr/client/router'

changed to:

import type { PageContextBuiltIn } from 'vite-plugin-ssr/types'
import type { PageContextBuiltInClientWithServerRouting } from 'vite-plugin-ssr/types' 

and 

type PageContextClient = PageContextBuiltInClient<Page> & PageContextCustom

to: 

type PageContextClient = PageContextBuiltInClientWithServerRouting<Page> & PageContextCustom

I also cleaned up my server/index.ts --> only import vite when development mode.

Do you have a recommendation for http server?  I am using fastify for no particular reason. 

Thanks for you help!
-Mark

**Comment by brillout** [comment]
👍 

> Do you have a recommendation for http server? I am using fastify for no particular reason.

Fastify is fine. For a modern deploy-agnostic alternative, see https://github.com/hattipjs/hattip and https://hono.dev/.

Btw, in case you can convince your employer: https://github.com/sponsors/brillout. Any help is hugely appreciated.
