### ISSUE TITLE
Unable to run in Yarn PnP with latest version 0.4.132

### ISSUE THREAD

**Issue by 0xHexE** [brillout/vite-plugin-ssr#976]
### Description

```
Required package: react-dom (via "react-dom/server.node")
Required by: @brillout/import@npm:0.2.3 (via /usr/src/app/.yarn/cache/@brillout-import-npm-0.2.3-f26964923d-90a0f39148.zip/node_modules/@brillout/import/dist/index.js)

    at makeError (/usr/src/app/.pnp.cjs:39679:34)
    at resolveToUnqualified (/usr/src/app/.pnp.cjs:41406:21)
    at resolveRequest (/usr/src/app/.pnp.cjs:41535:31)
    at Object.resolveRequest (/usr/src/app/.pnp.cjs:41598:26)
    at resolve$1 (file:///usr/src/app/.pnp.loader.mjs:1989:21)
    at nextResolve (node:internal/modules/esm/hooks:726:28)
    at resolve (file:///usr/src/app/modules/apps/anthaathi-auth/anthaathi-auth-web-client/patch.mjs:6:9)
    at nextResolve (node:internal/modules/esm/hooks:726:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:235:30)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:168:24)
```

Workaround

`.yarnrc.yml`
```yaml
packageExtensions:
  "@brillout/import@*":
    dependencies:
      "react-dom": "*"

```

**Comment by brillout** [comment]
Yarn seems a little bit too strict here 🤔 E.g. pnpm doesn't complain about this.

Thanks for sharing the workaround. I believe you use `react-streaming`, right? So it's more of a react-streaming issue than a VPS one.

**Comment by 0xHexE** [comment]
Sure, I'll update you with it!

**Comment by brillout** [comment]
Closing but I'll re-open once I can get my hands on a reproduction. Looking forward to it.
