### ISSUE TITLE
Simplify workaround for React libraries that aren't valid JavaScript

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#984]
### Description

As explained in https://vite-plugin-ssr.com/broken-npm-package#solution many React libraries ship npm packages that aren't valid JavaScript.

I've a plan in mind to make the workaround much simpler.

**Comment by snake-py** [comment]
> I've a plan in mind to make the workaround much simpler.

Can you maybe elaborate what your approach to the solution would be?

**Comment by brillout** [comment]
The plan is to make `vite-plugin-ssr` automatically set `ssr.noExternal` to `true` and show a warning if users override that.

**Comment by iMrDJAi** [comment]
> The plan is to make `vite-plugin-ssr` automatically set `ssr.noExternal` to `true` and show a warning if users override that.

@brillout

```
[commonjs--resolver] Cannot bundle Node.js built-in "path" imported from "index.ts". Consider disabling ssr.noExternal or remove the built-in dependency.
```

Setting `ssr.noExternal` to `true` would include everything, including node builtins.

**Comment by iMrDJAi** [comment]
@brillout Native node modules as well:

```
[commonjs--resolver] Unexpected character '' (Note that you need plugins to import files that are not JavaScript)
file: <project>/node_modules/linkedom/commonjs/canvas.cjs:1:0
1: ELF>�X@��@8@���� ...
   ^
2: @D0�$@����� �B       `(���
                                @��D$+�!B       ��D"��@H@��$�l...
 ! F���PL`��� ��@
                 0� ��
error during build:
RollupError: Unexpected character '' (Note that you need plugins to import files that are not JavaScript)
```

**Comment by iMrDJAi** [comment]
Also, `ssr.noExternal` breaks dev mode for some reason:

```
file:///<project>/node_modules/express/index.js:11
module.exports = require('./lib/express');
^

ReferenceError: module is not defined in ES module scope
    at file:///<project>/node_modules/express/index.js:11:1
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadEntry (file:///<project>/node_modules/@vavite/reloader/dist/index.mjs:35:5)
```

**Comment by brillout** [comment]
Also `react` cannot be `noExternal` (although it may be possible to make it work). A workaround is keep an internal list of modules/libraries that should be `external`.

Alternatively, instead of setting `ssr.noExternal: true`:
 - Maintain an internal list of libraries that should be `noExternal`.
 - Catch and add hints to CJS/ESM compat errors, telling the user how to solve the problem and/or to reach out and we'll fix the issue for him (also allowing us to update the internal list).

It isn't ideal, but it's the only way I see to provide a seamless DX.

**Comment by iMrDJAi** [comment]
@brillout Also this:

```
✓ 6633 modules transformed.
rendering chunks (102)...
Killed
```

For some reason the process crashes while rendering chunks.
It's getting so complicated. 😵‍💫😵‍💫

**Comment by brillout** [comment]
`ssr.noExternal: true` has too many problems, let's go for https://github.com/brillout/vite-plugin-ssr/issues/621 again.

**Comment by brillout** [comment]
FYI Bun's next release will support Vite and Bun includes a transpiler and is therefore able to process invalid JavaScript (whereas Node.js is strict which is "the cause" of most problems here).

**Comment by iMrDJAi** [comment]
I'm so excited about Bun but it still depends on compatibility of packages that use Node APIs.

**Comment by brillout** [comment]
Correct me if I'm wrong, but I believe Bun does aim to fully support Node.js APIs.
